### PR TITLE
Better Swiftlint precomment hook

### LINKED ISSUE #1770: Improve Swiftlint precommit hook
The recommit hook currently installed via `make artsy` lints all Swift files, not just changed ones. This can lead to linting errors that the developer is not responsible for. A better hook would only check changed/added files. Also, integration with spacecommander might be in order. I'll take a look.

### PR DESCRIPTION
**Pull request by ashfurrow**
This improves the precommit hook for swiftlint, only linting the specific added/changed files. I also ran the code through the linter to fix any existing issues so we can start from a clean slate.

Fixes #1770.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |239.6ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Artsy/View_Controllers/Auction/AuctionViewController.swift#L183) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
191.1ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
176.4ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
79.8ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
76.6ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
72.1ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
63.5ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L49) | @objc override func viewDidLoad()
63.4ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
61.4ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
60.3ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/ashfurrow-swiftlint-precommit-hook/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
screen shot 2016-06-28 at 9 13 43 am

Aww yeah, just under the changelog loc requirement.

**Comment by orta** [comment]
👍 

Probably won't be too much effort to move this into a Danger plugin too

**Comment by ashfurrow** [comment]
Swiftlint plugin sounds awesome. That's wrapped up, eh? Like `danger new_plugin` should work? I can take a stab.

**Comment by orta** [comment]
Roughly, aye, IMO, clone https://github.com/dbgrandi/danger-prose and do some re-naming, there's work I've done there WRT testing that's not migrated back upstream

**Pull request merged**
