### PR TITLE
chore: upgrade relay to 16 [future-friday]

### PR DESCRIPTION
**Pull request by MounirDhahri**
[future-friday]

### Description

This PR updates relay to version 16

The main difference here is that relay compiler generates types as `| null | undefined` instead of just `| null`. Hence the massive diff

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- upgrade relay to 16 - mounir

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by olerichter00 — COMMENTED** [review]
Amazing 🤩 

Have you tried upgrading the other relay packages as well?

```
"@types/relay-runtime"
"@types/relay-test-utils"
"babel-plugin-relay"
"relay-compiler": "14.0.0",
"relay-runtime": "14.1.0",
"relay-test-utils": "14.1.0",
```

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (upgrade relay to 16 - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d1502ffd96adbc3895f00fbef0e64baae86ad573
</p>

**Review by gkartalis — COMMENTED** [review]
Impressive and exciting! 

**Question:** Do we have to worry for the breaking changes for version [16](https://github.com/facebook/relay/releases/tag/v16.0.0) and [15](https://github.com/facebook/relay/releases/tag/v15.0.0)?

**Comment by MounirDhahri** [comment]
@olerichter00 Ci doesn't run on draft PR so I am trying to see if it will pass then fix the broken types if any

**Comment by gkartalis** [comment]
@MounirDhahri this is a great example on how the [canary](https://github.com/artsy/eigen/blob/main/docs/using_codepush.md#canary-builds) would help to see if we broke anything!

**Comment by gkartalis** [comment]
Will do a more thorough review tomorrow! Really excited 🔥🔥🔥🔥 Thanks for pushing this forwards!

**Comment by MounirDhahri** [comment]
We would need to merge this before the release to catch any issues that might be related to it

**Review by gkartalis — COMMENTED** [review]
**Question/concern:** Don't we have to update the rest of dependencies and types as well before we merge? (talking about every relay related dependency, thought they should be updated together)

Especially `relay-compiler`, `relay-runtime` and `relay-test-utils`

**Comment by MounirDhahri** [comment]
I could almost swear i updated them already following Ole's comment 😄 - will make this a draft and take a look again at it

**Comment by gkartalis** [comment]
> I could almost swear i updated them already following Ole's comment 😄 - will make this a draft and take a look again at it

No worries, thanks a lot!

**Comment by MounirDhahri** [comment]
@olerichter00 @gkartalis 
Done ✅ 126 Typescript issues 😩

**Comment by gkartalis** [comment]
😬 - happy to do a mob - maybe during mobile office hours (?) to address some in parallel?

**Comment by MounirDhahri** [comment]
I fixed them all already actually 😄

**Comment by gkartalis** [comment]
omg THANKS!!!

**Comment by MounirDhahri** [comment]
@gkartalis we don't need to worry about the breaking changes.

**Comment by MounirDhahri** [comment]
Let's merge this before it explodes again with merge conflicts - glad to address any comments later

**Pull request merged**
