### PR TITLE
fix(NX-3269): conversations list all shown on the list

### PR DESCRIPTION
**Pull request by araujobarret**
### Description

The last element of Inbox conversations wasn't fully shown on iOS and Android as well, this PR addresses this issue plus removes a border only shown on Android from the `Inbox` text element.

This PR resolves [NX-3269]

*Android*

https://user-images.githubusercontent.com/15792853/184616869-ad3b3a8e-22eb-4052-b376-dc855ccb8aaf.mov

*iOS*

https://user-images.githubusercontent.com/15792853/184616995-02aeb1d2-7f20-4ee0-8ba8-0c5c4d7befa5.mov

#### Acceptance Criteria

-

#### Setup Instructions

-

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- conversations items respect the bottom tab height - araujobarret

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[NX-3269]: https://artsyproduct.atlassian.net/browse/NX-3269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MrSltun — DISMISSED** [review]
Thank you @araujobarret! 🚀  I tested this on my phone and it works perfectly 🙌 
Just a suggestion (doesn't block merging this) which is updating the loading indicator padding, because I can see it in the code but it doesn't show on my phone (probably it is rendered behind the bottom tabs)

**Review by MounirDhahri — APPROVED** [review]

**Comment by MounirDhahri** [comment]
Thanks for the fix

**Comment by MounirDhahri** [comment]
#squashongreen

**Review by MrSltun — APPROVED** [review]
I can confirm that the loading indicator shows up 👍 🚀  Thank you for the fix @araujobarret

**Pull request merged**
