### PR TITLE
feat: add skeleton animation to loading placeholders

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR resolves [] 

### Description

Add skeleton animation to loading placeholders

https://user-images.githubusercontent.com/11945712/229451670-e6754e46-c3be-4d4f-80da-818f6bcb0a85.mov

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- add skeleton animation to loading placeholders - mounir, ole

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by olerichter00 — APPROVED** [review]
Looks good 🌟 

Maybe we can switch to palette-mobile's [Skeleton component](https://github.com/artsy/palette-mobile/blob/78af2429ec1b3450e7cb13b7e65f76345a2c0fa8/src/elements/Skeleton/Skeleton.tsx) in a next step.

**Comment by MounirDhahri** [comment]
@olerichter00 yes, I think we should do that but I would suggest keeping it separate though since both components are not interchangeable currently (`style` prop for example)

**Comment by damassi** [comment]
@olerichter00 - in the meantime (before using skeleton component) can we move this file to `utils/animations` so that we have a central place for animation-related code?

**Comment by MounirDhahri** [comment]
Good idea, I can do it as well as a follow-up on this PR

**Pull request merged**
