### PR TITLE
chore: bump version 7.4.0

### PR DESCRIPTION
**Pull request by araujobarret**
### Description

Bumps version to 7.4.0

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by MounirDhahri** [comment]
Thanks Carlos 🙏

**Comment by MounirDhahri** [comment]
Sorry I forgot to do that yesterday, I will create new builds now

**Comment by araujobarret** [comment]
nah no worries, do we have documented where to trigger the builds?

**Comment by MounirDhahri** [comment]
Yes, I am using the command here https://github.com/artsy/eigen/blob/main/docs/deploy_to_beta.md

**Pull request merged**
