### PR TITLE
fix(CX-3266): Update AddPhotos image URLs

### PR DESCRIPTION
**Pull request by MrSltun**
This PR resolves [CX-3266] 

### Description
This PR updates the url used in the AddPhotos component in My Collection Form to be the same as the one used in [My Collection artwork details screen](https://github.com/artsy/eigen/blob/main/src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx#L40), hence benefitting from the already loaded image on the device

### Video

https://user-images.githubusercontent.com/20655703/225285744-ebde1eed-e823-448b-bd24-9acec0302871.mp4

  

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Update image URL inside AddPhotos component in My Collection artwork form - mrsltun

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-3266]: https://artsyproduct.atlassian.net/browse/CX-3266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by olerichter00 — DISMISSED** [review]

**Review by MounirDhahri — APPROVED** [review]

**Comment by MounirDhahri** [comment]
@MrSltun Have you tried with the version that doesn't crop the images?

**Comment by MrSltun** [comment]
@MounirDhahri they all load, but because they are different versions, there's a loading delay (which is the reported issue), but we could update the version to load on the details screen to be the `large` one and use it in the AddPhotos component as well! I'll update it and test now!

**Comment by MounirDhahri** [comment]
Sounds good to me. Feel free to merge then when ready

**Comment by MrSltun** [comment]
@MounirDhahri I tested it to use the `large` version inside the AddPhotos component, and it seems that it loads the image again 🤷 but using different versions (`large` for the details screen, and `square` for the AddPhotos screen) seems to work quite well, I'll update the PR and update the video as well!

**Comment by MounirDhahri** [comment]
sounds good to me then

**Pull request merged**
