### PR TITLE
Corrects typo in dimension-setting #trivial

### LINKED ISSUE #1713: Artworks scale and zoom into weird mask, they should not
The aspect ratio of this work is portrait
image

But we seem to be squishing it into a square
img_8806

### PR DESCRIPTION
**Pull request by ashfurrow**
We subtracted 40 from the heights, but forgot to change the hundredths place:

screen shot 2016-06-14 at 2 29 19 pm

I noticed that portrait-orientation images were getting cut off when swiping back-and-forth on the live interface. Our tests (and mocktion test lots) are all landscape. Might be worth adding some portrait lots to our create-mocktion Jenkins job? /cc @devangt @acjay 

Fixes #1713.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">There were <a href="https://eigen-ci.s3.amazonaws.com/2965/index.html">snapshot errors</a></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |261.2ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-collection-view-fix/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
244.8ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-collection-view-fix/Artsy/View_Controllers/Auction/AuctionViewController.swift#L183) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
184.8ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-collection-view-fix/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
88.8ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-collection-view-fix/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
77.3ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/ashfurrow-collection-view-fix/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L49) | @objc override func viewDidLoad()
70.8ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-collection-view-fix/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
69.7ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-collection-view-fix/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, sideMargin: String)
69.6ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-collection-view-fix/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
67.6ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-collection-view-fix/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
Forgot to hit "swap" >.<

**Comment by ashfurrow** [comment]
🍏

**Comment by orta** [comment]
rockin'

**Pull request merged**
