### PR TITLE
feat: improve otp login experience(enable password managers autofill)

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves []

### Description

Enables pasting otp with password managers on otp screen

Tested my changes on iOS and it works great.

#### iOS Demo
https://user-images.githubusercontent.com/21178754/169819892-896e0131-4d91-49cd-9d4e-e74f3ee3c352.mov

Can somebody with an android device confirm that this works also on android?

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [x] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- enable otp autofill from password managers - gkartalis

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by pvinis — COMMENTED** [review]
nice nice. I can test this tomorrow on iOS. if others test, then even faster :)

**Review by dimatretyak — APPROVED** [review]

**Comment by gkartalis** [comment]
@pvinis already tested on iOS and attached a video in the description, on android though looks like onepassword is not working properly either way so I was thinking to just remove the android specific line for now and leave it with the ios one, and we can follow up on why 1password fails to autofill in android in another pr

**Comment by pvinis** [comment]
I assigned myself too. George is on holidays and we talked about this ticket before he left, I'll take this over until then.

**Comment by gkartalis** [comment]
closing this as it looks like autofill works on android now 💆‍♂️

**Pull request closed without merging**
