### PR TITLE
feat: add version / OS to volley tags

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [] 

### Description

Adds version / OS to Volley tags so we will be able to differentiate in [datadog dashboards](https://app.datadoghq.com/dashboard/yyp-59r-ehf/cx-main-queries-dashboard?tile_focus=2264222510213684&from_ts=1666750635684&to_ts=1676395575684&live=true) between version / OS.

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- add version / OS to volley tags - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by MrSltun — APPROVED** [review]
🌟 🔥 🚀

**Comment by gkartalis** [comment]
It is still in draft for checking how can we filter out in the datadog dashboard [here](https://app.datadoghq.com/dashboard/yyp-59r-ehf/cx-main-queries-dashboard?tile_focus=2264222510213684&from_ts=1666750635684&to_ts=1676395575684&live=true) if we are able to filter with tag

**Review by pvinis — APPROVED** [review]

**Review by joeyAghion — APPROVED** [review]
I suggest monitoring the [custom metrics quota](https://app.datadoghq.com/billing/usage?category=custom-metrics&data_source=billable&summary_month=2023-02&trends_start_date=2023-01-01&trends_time_frame=annually) to ensure this doesn't cause unexpected costs. If there are _N_ possible `OS` values and _M_ possible `appVersion` values, this could multiply the number of metrics by up to _N*M_.

**Review by brainbicycle — APPROVED** [review]
👍 💯

**Comment by gkartalis** [comment]
@joeyAghion Do you think that if the cost increases its actually worth it? Because it is really important if a screen doesn't load in the mobile app.

**Comment by joeyAghion** [comment]
I was just suggesting monitoring it after release, not blocking this. It's hard to know what the cost impact would be, and how useful the tags are, until then.

**Pull request merged**
