### PR TITLE
feat(DIA-806): Recaptcha mechanism

### PR DESCRIPTION
**Pull request by araujobarret**
This PR resolves [DIA-806] 

### Description

Adds a simple Recaptcha mechanism to be user within the verify email flow.
The hook is simple, just import it and place the recaptcha element in the component tree.

PS: citadel .env.shared was already updated 🔢 

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- feat: add recaptcha mechanism - araujobarret

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[DIA-806]: https://artsyproduct.atlassian.net/browse/DIA-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (feat: add recaptcha mechanism - araujobarret)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against be3b8b8b3c6776bdff301bcc0f4095c4ae02d97c
</p>

**Review by gkartalis — COMMENTED** [review]
Looking good but:

- Could you also fill in the PR checklist?
- Since it is a user facing feature could you also include screenshots or even better videos of the new flow?

**Review by damassi — APPROVED** [review]
Not sure of the overall behavior, but the code looks good 👍

**Review by iskounen — APPROVED** [review]

**Comment by araujobarret** [comment]
@gkartalis I could create a dummy video but the mechanism is not wired up yet, @iskounen is going to use it in his new signing flow PR so we can see if the recaptcha token is present or not. 
@iskounen might be nice to show a debugger network inspection once you create the videos for your PR to show if the recaptcha token is going or not

**Pull request merged**
