### PR TITLE
Attempt to cache fonts before loading the testing environment #trivial

### PR DESCRIPTION
**Pull request by orta**
I can't guarantee this will help, so if this fails with those errors, we can def not merge. Will run theses tests 3-4 times, if it's always green I'll merge.

### CODE REVIEW

**Comment by orta** [comment]
This has succeeded 3 times in a row so far, doing it one more time.

**Comment by alloy** [comment]
I think this was also a major reason for focussed tests to fail.

**Comment by orta** [comment]
OK, 4th time, I'm happy.

**Comment by alloy** [comment]
Ace :+1:

**Pull request merged**
