### PR TITLE
chore(fx-2372) fair teardown; fair2 => fair

### PR DESCRIPTION
**Pull request by dzucconi**
The type of this PR is: **Chore**

This PR resolves [FX-2372]

### Description

<del>I'd like to find a fair on staging with `sponsoredContent` tomorrow morning just to double check that aspect.</del> [(Is fine)](https://static.damonzucconi.com/_capture/6lAWlRXhGRLS.png)

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

[FX-2372]: https://artsyproduct.atlassian.net/browse/FX-2372

### CODE REVIEW

**Review by dblandin — APPROVED** [review]
Nice 🔥

**Review by MounirDhahri — APPROVED** [review]

**Review by MounirDhahri — APPROVED** [review]

**Comment by MounirDhahri** [comment]
Thanks for these changes Damon and sorry for the late review 🙏

**Comment by MounirDhahri** [comment]
#squashongreen

**Comment by MounirDhahri** [comment]
#squashongreen

**Comment by MounirDhahri** [comment]
Hmmm looks like the #SquashOnGreen is broken for some reason 🙈

**Pull request merged**
