### PR TITLE
[Analytics] Make ‘sign-up/connect with email/facebook/twitter’ -> ‘created account’ consistent.

### PR DESCRIPTION
**Pull request by alloy**
Fixes https://github.com/artsy/eigen/issues/1123#issuecomment-198306933.

### CODE REVIEW

**Comment by anipetrov** [comment]
Makes perfect sense, thank you!

**Comment by orta** [comment]
Should these provide a context dictionary?

**Comment by anipetrov** [comment]
Ideally we would want to have a single `tapped sign up` event that has properties around how the sign up was created (email, facebook, twitter). This works, too, for now -- it is on my team's radar to revisit all major flows (eg account creation, inquiry etc.) and make sure eventing is instrumented with a clear pattern that translates between apps, so we can do that pass later, too. If not too much trouble, we could do this at this pass.

Additionally, we could add context_type: [sign up splash, follow, bell etc.] but I think this might require more work on our end to sketch out all possible contexts.

**Comment by anipetrov** [comment]
Also not sure if more thorough event revamp is necessary for this round if we are moving through with obligatory sign ups.

**Comment by alloy** [comment]
Good point, in which case I'd opt for deferring more elaborate changes until the new onboarding is in place.

**Comment by anipetrov** [comment]
:+1:

**Pull request merged**
