### PR TITLE
Adds horizontal ARVIR

### PR DESCRIPTION
**Pull request by orta**
Takes a new ARVIR current prototype and moves it to be behind an admin flag. 

This PR:

* renames the `ARAugmentedVIRViewController.m` to `ARAugmentedFloorBasedVIRViewController.m` and `ARAugmentedVIRInteractionController.m` to `ARVIRVerticalWallInteractionController.m`

* Introduces a whole new VIR setup based on the floor detection inside `ARVIRHorizontalPlaneInteractionController.m`

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">No CHANGELOG changes made</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_travis">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
We now can render the point cloud of detected features.

img_2bf240930620-1

**Comment by orta** [comment]
Now starting to look like the [design specs](http://design.artsy.net/buy/ios-in-room-ar-viewer/v5/)

img_830624124716-1

**Comment by ashfurrow** [comment]
Nice, will take a look shortly 👍

**Pull request merged**
