### PR TITLE
Support updating the JS at runtime, and new Admin menu

### PR DESCRIPTION
**Pull request by orta**
I figured out a safe pattern for us to handle continuous deployment in the Emission beta app. So now that that is stable and working, I've brought this pattern over to Eigen. Now the JS can be updated independantly 🎉  

### How does this magic work?

Conceptually it's pretty simple. Every CI build of Emission triggers something:

* [On a master commit](https://github.com/artsy/emission/blob/master/scripts/deploy_master.sh) we ship a dev build of Emission to a known location on S3 - this script uploads the JS and a JSON file with enough metadata to show a useful UI.

* [On a PR commit](https://github.com/artsy/emission/blob/master/scripts/deploy_commit.sh) we ship a the compiled JS to a known location with the PR number in it. Clients can use the [GitHub API](https://github.com/artsy/emission/blob/master/Example/Emission/PRNetworkModel.m) to determine open PRs (as the repo is OSS) and then [choose one to use](https://github.com/artsy/emission/blob/master/Example/Emission/EmissionPRChooseViewController.m).

So we can bake assumptions into the client about the S3 details. In the Emission test app, it will [automatically download the new JS on launch](https://github.com/artsy/emission/pull/803)  whereas in Eigen there is an admin button to toggle staging JS which has an "update JS" button that brings you back to the latest master. 

So what can be updated? These screens: Consignments, Artist, Home, Gene, WorksForYou, User Settings, Inbox, Conversation, Inquiry.

How? If you use an _x_@artsymail.com email, then you can shake the phone and turn on "use staging JS".

---

### New Admin UI

I took some of the admin tricks from Emission back over to Eigen, as it had some good abstractions. Visually, it adds 2 lined text rows, and information only rows. I also took the time to make neater sections, and made sure it ignored the back button correctly.

Here it is in full:

screen shot 2017-11-02 at 5 40 41 pm
screen shot 2017-11-02 at 5 40 44 pm
screen shot 2017-11-02 at 5 40 50 pm
screen shot 2017-11-02 at 5 40 52 pm

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_travis">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
So many merge commits ( I was working on 5 separate branches: 1 for the 3.2.7 font fixes, master's font fixes and then the emission update )

**Comment by orta** [comment]
Damn, this was the 1000th closed PR on this repo since it went OSS

**Comment by ashfurrow** [comment]
Awesome!

giphy

**Pull request merged**
