### PR TITLE
@alloy -> constrain width of launch logo on iphone

### PR DESCRIPTION
**Pull request by 1aurabrown**
screen shot 2015-07-14 at 10 27 19 am
screen shot 2015-07-14 at 10 27 01 am

### CODE REVIEW

**Comment by orta** [comment]
The XML doesn't look specific to iPhone? Though it's probably not a problem on iPad either way.

**Comment by alloy** [comment]
Zack you :+1:

**Comment by 1aurabrown** [comment]
it uses size classes. idk how it indicates that in the xml.

**Comment by orta** [comment]
:sparkles: magick

**Pull request merged**
