### PR TITLE
chore: only track unable to loads from app wide error boundary

### PR DESCRIPTION
**Pull request by brainbicycle**
This PR resolves [] 

### Description

This updates our tracking of unable to loads to only track those that came from the app wide error boundary. 
We use this error boundary in some screens as well as app wide. Those in screens are mostly okay, some improvement maybe can be made to the error screens but priority is the app wide error boundary since when users hit this they have no access to navigation. So hopefully by removing these from tracking we get a better sense of real problem and it is easier to find the culprits. 

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- only track unable to loads from app wide error boundary - brian 

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (only track unable to loads from app wide error boundary - brian)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7e2adc4f1e94a352066e08a25ac05accb6eced1d
</p>

**Review by MounirDhahri — APPROVED** [review]
Let's try this out. Even if it means we will get less errors reported. 
I have a follow-up question though, will this affect thrown errors from mutations etc. will we still get those reported?

**Comment by brainbicycle** [comment]
> Let's try this out. Even if it means we will get less errors reported. I have a follow-up question though, will this affect thrown errors from mutations etc. will we still get those reported?

After testing some more, I think I need to make this a little more nuanced, will check on mutations (I think they will still get reported) but I found other unable to loads that aren't app wide but are also dead ends with no nav.

**Comment by MounirDhahri** [comment]
Sounds good to me - thanks for looking into it

**Pull request closed without merging**
