### PR TITLE
chore: retire AREnableCuratorsPickRail, AREnableSkeletonAnimation, AREnableArtworksLists, AREnableDoMoreOnArtsyRail

### PR DESCRIPTION
**Pull request by dariakoko**
This PR resolves [ONYX-331], [ONYX-327], [ONYX-324], [ONYX-326] 

### Description
Retire following feature flags: 
- AREnableCuratorsPickRail
- AREnableSkeletonAnimation
- AREnableArtworksLists
- AREnableDoMoreOnArtsyRail

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- retire old feature flags Retire following feature flags: AREnableCuratorsPickRail, AREnableSkeletonAnimation, AREnableArtworksLists, ARShowCollectedArtistOnboarding, AREnableDoMoreOnArtsyRail -daria

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-331]: https://artsyproduct.atlassian.net/browse/ONYX-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-327]: https://artsyproduct.atlassian.net/browse/ONYX-327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-324]: https://artsyproduct.atlassian.net/browse/ONYX-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-318]: https://artsyproduct.atlassian.net/browse/ONYX-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-326]: https://artsyproduct.atlassian.net/browse/ONYX-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (retire old feature flags Retire following feature flags: AREnableCuratorsPickRail, AREnableSkeletonAnimation, AREnableArtworksLists, ARShowCollectedArtistOnboarding, AREnableDoMoreOnArtsyRail -daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 447ccfb632d349a45b7ecab5b0eda73a30a12b15
</p>

**Review by olerichter00 — APPROVED** [review]
🌟

**Comment by dariakoko** [comment]
> Nice! LGTM! do you mind if you also remove the files that are related to `DoMoreOnArtsy` since that code is not released. Same for `ARShowCollectedArtistOnboarding`

Thanks for spotting it! Removed the code related to `DoMoreOnArtsy`
And the code related to `ARShowCollectedArtistOnboarding` will be removed in another PR to avoid conflicts

**Review by olerichter00 — APPROVED** [review]
🧹 🧹 🧹

**Pull request merged**
