### PR TITLE
chore(CX-2323): add my collection artwork screen feature flag

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **TYPE**

This PR resolves [CX-2323]

### Description

- This PR sets the foundation for the upcoming my collection artwork page redesign

**What I did**
- I added the feature flag
- I renamed the existing screen from `MyCollectionArtwork.tsx` to `OIdMyCollectionArtwork.tsx` same as for its associated tests
- I created the new screen which for now returns nothing

https://user-images.githubusercontent.com/11945712/152396054-a2046539-abd4-4bb0-be2b-109f9d4d9fdd.mov

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Add New My Collection Artwork Screen feature flag - mounir

</details>

[CX-2323]: https://artsyproduct.atlassian.net/browse/CX-2323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  We are trying to migrate away from `react-test-renderer` towards `@testing-library/react-native`, but found Test-Renderer imports in the following new unit test files:

- `src/lib/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tests.tsx`

See [`Pill.tests.tsx`](https://github.com/artsy/eigen/blob/2f32d462bb3b4ce358c8a14e3ed09b42523de8bd/src/palette/elements/Pill/__tests__/Pill-tests.tsx) as an example, or [the docs](https://callstack.github.io/react-native-testing-library/docs/api-queries).
  
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4605dc660acfcf02fab16e64e8cc0c2db64d359f
</p>

**Review by olerichter00 — DISMISSED** [review]
Great work 🎉

**Review by MrSltun — APPROVED** [review]
LGTM 🚀

**Review by dariakoko — COMMENTED** [review]
Looks good 🔥

**Pull request merged**
