### PR TITLE
fix(SWA-358): Bug fixes for SWA flow

### PR DESCRIPTION
**Pull request by AlicanAkyuz**
This PR resolves [SWA-358] 

### Description

There are 3 bugs reported in Slack: https://artsy.slack.com/archives/C02B4Q2TKGW/p1652964074639359 

Namely: 
1- In the 1st step of the flow, when city is selected and zip code input is rendered, the Continue button is out of the view
2- when you go to the 1st step from the navbar, there’s a warning about a key not being valid
3- when you go to the 1st step from myCollection, there’s an error about images not loading to Gemini

This PR is fixing these bugs by removing animated from Collapse component. 

### Video 

https://user-images.githubusercontent.com/42584148/169330779-42f7a3b7-2da2-4006-b8d4-171eef3ae393.mp4

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [x] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [x] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes
The changes are applicable to all users in all platforms. 

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[SWA-358]: https://artsyproduct.atlassian.net/browse/SWA-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by iskounen — APPROVED** [review]
These changes look good to me, but I am curious to know why the original implementation of the `Collapse` element was causing the 3 errors that we saw.

**Comment by pvinis** [comment]
Could you explain what you did to fix this? Basically removing the animations fixed this?

**Review by MounirDhahri — APPROVED** [review]
thanks for figuring this out @AlicanAkyuz

**Comment by MounirDhahri** [comment]
@iskounen @pvinis I think the animation for the collapse component was removed at some point and it was added again recently after we synched `palette`. The animation was actually really really nice before we removed it

**Comment by pvinis** [comment]
but i mean, was the animation the actual reason for these bugs?

**Comment by AlicanAkyuz** [comment]
@pvinis @iskounen apologies for the lack of context in the description. 

as Mounir said, the animation/spring is removed from the Collapse when the new SWA flow was being developed. here is [the PR](https://github.com/artsy/eigen/pull/6183) for that. as far as I remember, the reason for removing it was that it wasn't re-adapting to the dynamic height changes of its children. When energy's palette is synched [here](https://github.com/artsy/eigen/pull/6711), Collapse got back the animation stuff. 

I am sure that animated-collapse is the reason for the 1st problem (in the description). If you pass it a logging function in `onAnimationFrame` prop, it'll give back the height. This height never changes when additional content (such as edition number and size, zip code) is made visible in the children passed to it. 

I am not entirely sure how removing animation fixes the 2nd and 3rd problems, but it does. 

My initial attempt was to figure out the problem so that animated-Collapse responds to the height changes of its children. I could not figure that out. so I removed it again. The only other place where this component is used is in `CollapsibleArtworkDetails`. there, the passed child has a static height and therefore it's not affected by the lack of response to dynamic height changes. 

**Idea**: I can bring animated component back and comment it out for now, so that someone can fix it when they have time?

**Comment by pvinis** [comment]
thank you for the extra info. sorry I brought the animation back. it was accidental 😅.

I think it's cool as we have it now. when we extract palette mobile and if we decide to try the animation again, we will find the code 👍.

thanks again, and good work!

**Review by dariakoko — APPROVED** [review]
Thank you @AlicanAkyuz  🙌

**Pull request merged**
