### PR TITLE
Blank auctions controller

### PR DESCRIPTION
**Pull request by ashfurrow**
Basics – added a new view controller and bridging header, and Swift import header. Adding subsequent Swift files should be easier. 

I'm going to try later to merge the bridging header and PCH file somehow so we can auto-import those files into Swift and into ObjC :smiling_imp:

### CODE REVIEW

**Comment by orta** [comment]
> I'm going to try later to merge the bridging header and PCH file somehow so we can auto-import those files into Swift and into ObjC :smiling_imp:

Try to not do this ASAP, I'm interested in the seams for what a VC _really_ needs to exist in eigen.

**Comment by orta** [comment]
failure looks legit

**Comment by ashfurrow** [comment]
Cool coo, looking into it.

**Comment by orta** [comment]
and the danger thing was brought up in our notifications chat room earlier, I can look at that tomorrow

**Comment by ArtsyMobile** [comment]
:white_check_mark: | No errors found
  ------------- | ------------ 



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-07</i>
</p>

**Comment by ashfurrow** [comment]
:tada:

**Comment by orta** [comment]
Thanks :+1:

**Pull request merged**
