### PR TITLE
feat: share button in viewing rooms [GALL-3221]

### PR DESCRIPTION
**Pull request by mdole**
The type of this PR is: **feature**

This PR resolves [GALL-3221](https://artsyproduct.atlassian.net/browse/GALL-3221)

### Description

This PR adds a share button to viewing rooms. See screenshots for examples!

<details>
<summary>Screenshot: iPhone 8</summary>

</details>

<details>
<summary>Screenshot: iPhone 11 pro</summary>

</details>

<details>
<summary>Screenshot: iPad Pro 3</summary>

</details>

<details>
<summary>Screenshot: share menu</summary>

</details>

<details>
<summary>Screenshot: tracking (cc @louislecluse)</summary>

</details>

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

### CODE REVIEW

**Review by tinn — APPROVED** [review]
Visually, this looks good to me. Thanks for providing the screenshots.

**Review by pvinis — APPROVED** [review]
So good to see this implemented :D 



I wonder why the screenshot of the share sheet is showing the "text" icon 🤔, and no share to safari? strange, unless its a simulator thing.

**Comment by mdole** [comment]
@pvinis yeah I'm not sure! it's the same for artworks in simulator though too 🤷‍♂️ 
Screen Shot 2020-10-02 at 2 03 13 PM

**Comment by pvinis** [comment]
indeed. I tried now on beta and even though it has the text icon, it shares fine. so all good. 🤷‍♂️

**Comment by louislecluse** [comment]
Looks good thanks!

**Comment by mdole** [comment]
gonna go ahead and merge this since it's approved! then it'll be waiting for us in the beta on Monday :)

**Comment by louislecluse** [comment]
Added the event to the event master list here: https://docs.google.com/spreadsheets/d/1o1J8xs7R3wLY7MXAK28J2XKmYe4NSiKT0aNdwMkryZA/edit?usp=sharing

**Pull request merged**
