### PR TITLE
Update pull_request_template.md v2

### PR DESCRIPTION
**Pull request by patrinoua**
### Description

Some more small changes to the formatting:
- [x] Brief reminder text that's easy to read.
- [x] Order by what occurs more often in development.
- [x] Add ticket number on the PR name so it's visible in the list of open PRs.
- [x] **Provide Link to the documentation**

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]

**Comment by MounirDhahri** [comment]
Thanks Angela for linking the docs

**Review by rajsam003 — APPROVED** [review]
Awesome 👏

**Review by MounirDhahri — APPROVED** [review]
🎊🎊🎊

**Review by brainbicycle — APPROVED** [review]
🎉 thanks!

**Pull request merged**
