### PR TITLE
Auction UI Fixes

### LINKED ISSUE #1340: get rid of rule on auction sale modal
image

### LINKED ISSUE #1341: type formatting on auction sale overview
We're using Garamond Bold when we should be using Garamond Semi-bold

image

image

### PR DESCRIPTION
**Pull request by ashfurrow**
Uses semibold instead of regular bold, and changes colour of serif nav bar shadow.

Fixes #1340.
Fixes #1341.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">2 Warnings</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td>Needs testing on a Phone if change is non-trivial</td>
    </tr>
        <tr>
      <td>:warning:</td>
      <td><h4>Found unstubbbed networking requests</h4>

<ul>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
</ul>
</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
Code gets a 👍🏾 - has a mere conflict though

**Comment by ashfurrow** [comment]
```
 _______  _______  _______  _______  _______  ______  
(       )(  ____ \(  ____ )(  ____ \(  ____ \(  __  \ 
| () () || (    \/| (    )|| (    \/| (    \/| (  \  )
| || || || (__    | (____)|| |      | (__    | |   ) |
| |(_)| ||  __)   |     __)| | ____ |  __)   | |   | |
| |   | || (      | (\ (   | | \_  )| (      | |   ) |
| )   ( || (____/\| ) \ \__| (___) || (____/\| (__/  )
|/     \|(_______/|/   \__/(_______)(_______/(______/ 
                                                      
```

**Comment by ashfurrow** [comment]
This passed, but is red? Weird. 
screen shot 2016-03-22 at 3 53 35 pm

**Comment by ashfurrow** [comment]
This is :green_apple: and I got the :+1: from Orta, so merging.

**Comment by alloy** [comment]
Was just gonna do it :+1:

**Pull request merged**
