### PR TITLE
Erikdstock/replace modal android

### PR DESCRIPTION
**Pull request by erikdstock**
Followup to #4575 which adds android support for replacing a modal with a new modal rather than just pushing onto the stack. Tested on android simulator and it appears to work as expected, though I could not close the webview order flow modal in the style with the `X` button. I know why this would be related, though.

The type of this PR is: **chore**

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

### CODE REVIEW

**Comment by pvinis** [comment]
I'll assign the other two people that worked on modals a lot 👍.

**Review by MounirDhahri — APPROVED** [review]

**Comment by MounirDhahri** [comment]
Nice!

**Comment by erikdstock** [comment]
#squashongreen

**Comment by ds300** [comment]
@erikdstock thanks for taking care of this! 🙏🏼

**Pull request merged**
