### PR TITLE
Migrate to using deploying test flight betas via Fastlane

### PR DESCRIPTION
**Pull request by orta**
Introduces an AppStatus model, that lets you know whether we're in beta or not inside the app. 
Adds a deploy command that just pushes your current branch to the beta. Fixes CI.

### CODE REVIEW

**Comment by alloy** [comment]
How does it let you know, I don’t see anything UI specific?

**Comment by orta** [comment]
Oh its not, I just mean that we can use it to determine that stuff in the app, instead of looking at bundle IDs etc.

**Comment by alloy** [comment]
Aha, gotcha.

**Comment by orta** [comment]
OK this should be good.

**Comment by alloy** [comment]
Awesome :+1:

**Pull request merged**
