### PR TITLE
fix: Android back button behaviour in checkout flow

### PR DESCRIPTION
**Pull request by MrSltun**
This PR resolves [] 

### Description

This PR fixes the back button behavior in Android in the checkout flow

⚠️ PS: I only tested on Android since the back button is Android specific ⚠️

### Videos
| Before | After |
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/7960c32f-d017-41c5-9620-1ef57f28bb05" /> | <video src="https://github.com/artsy/eigen/assets/20655703/8d1a6992-3472-4dab-9e33-e518efabc763" /> |

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [X] I hid my changes behind a **[feature flag]**, or they don't need one.
- [X] I have included **screenshots** or **videos**, or I have not changed the UI.
- [X] I have added **tests**, or my changes don't require any.
- [X] I added an **[app state migration]**, or my changes do not require one.
- [X] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [X] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

- Update back button behavior in checkout flow - mrsltun

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by gkartalis — APPROVED** [review]
Looks good, only one thing that we might need to check, how was the flow before vs now.

Meaning if we are on the **Payment** step, were we able to go back on the shipping before and now its dismissing the modal taking us to the artwork page?

Will QA a bit tomorrow morning 🔥

**Comment by MounirDhahri** [comment]
Do you know why on the first video, on back press we the user lands on my collection instead of the artwork page?

**Comment by gkartalis** [comment]
I think its due to our navigation structure after the rn updates something changed. Until we move to use react-navigation 100% don't know another way on how to avoid that.

A while ago I opened some related prs for some other surfaces that had the same behavior (https://github.com/artsy/eigen/pull/8646)

**Comment by gkartalis** [comment]
@MrSltun just qa'd on the emulator and looks good but not able to QA the gestures (they don't work on my android emulators 😅)

**Comment by MounirDhahri** [comment]
interesting bug - I didn't know about this failure (going to profile tab) - let's move on then

**Pull request merged**
