### PR TITLE
Support auto-playing html5 videos - fixes #980

### LINKED ISSUE #980: Internal Web View Controllers should have movies autoplaying
This can be done by setting `mediaPlaybackRequiresUserAction` to true on the WKWebViewConfig when we know it's internal.

### PR DESCRIPTION
**Pull request by orta**
Adds support for auto-playing the videos we use in the BG for super-posts in martsy/force.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
:white_check_mark: | No errors found
  ------------- | ------------ 



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-11</i>
</p>

**Comment by alloy** [comment]
Can you specify an example for manual testing during Q&A?

**Comment by orta** [comment]
https://www.artsy.net/article/artsy-editorial-2015-the-year-in-art

**Comment by alloy** [comment]
:+1:

**Comment by alloy** [comment]
@orta This doesn’t appear to work atm (on iOS 10), any ideas how/if this could be solved from the HTML side?

**Comment by orta** [comment]
Our investigations say nope:

New API:
https://developer.apple.com/reference/webkit/wkwebviewconfiguration/1851524-mediatypesrequiringuseractionfor?language=objc

Others with same problem
http://stackoverflow.com/questions/39604747/ios10-auto-play-not-working-on-wkwebview-requiresuseractionformediaplayback

**Pull request merged**
