### PR TITLE
chore: increase hitslop of more icon on activity screen

### PR DESCRIPTION
**Pull request by MounirDhahri**
### Description

This PR increases the hitslop of More Icon on the activity screen to offer a better UX

| Before | After |
| --- | --- |
| <Video src="https://github.com/artsy/eigen/assets/11945712/9171db22-025a-49ef-8025-5c11f860fc5f" /> | <Video src="https://github.com/artsy/eigen/assets/11945712/e9f97c88-8c58-4dc5-af07-25797592c79b" /> |

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- increase hitslop of more icon on activity screen - mounir

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (increase hitslop of more icon on activity screen - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bd321433a8900c12f2fe977f14983ffbccafa052
</p>

**Review by gkartalis — COMMENTED** [review]
random but did you know about this dev setting? We can visualize the touchable areas with opening dev menu > Show inspector > touchables 

app will show us an error but if you escape it you can see the surfaces highlighted like this

**Comment by MounirDhahri** [comment]
@gkartalis thanks for the hint. I tried it now but I got an error for some reason

Screenshot 2024-02-27 at 14 00 00

**Comment by gkartalis** [comment]
yep, if you press esc it will work correctly, for some reason it always shows up but it works reliably

**Review by olerichter00 — APPROVED** [review]
Thanks! We might need to do the same change for the header buttons on the Notification page. They are pretty small as well.

**Comment by MounirDhahri** [comment]
it worked now! weird

**Pull request merged**
