### PR TITLE
fix: Update My Collection artwork filter to use category instead

### PR DESCRIPTION
**Pull request by olerichter00**
### Description

Update My Collection artwork filter to use category instead.

#### Acceptance Criteria

-

#### Setup Instructions

-

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by MounirDhahri — DISMISSED** [review]

**Comment by MounirDhahri** [comment]
Thanks for the fix

**Comment by MounirDhahri** [comment]
#squashongreen

**Review by MounirDhahri — CHANGES_REQUESTED** [review]
I think the fix here will be in metaphysics since that's where we do the filtering

**Comment by MounirDhahri** [comment]
The above code is related to the local filters. Which we will also need to update actually!

**Comment by MounirDhahri** [comment]
I made an attempt here https://github.com/artsy/metaphysics/pull/4299

**Comment by olerichter00** [comment]
I merged https://github.com/artsy/metaphysics/pull/4299 and I think we need to merge this PR as well to adjust the filters which are calculated locally.

**Comment by MounirDhahri** [comment]
I agree, let's do it

**Review by MounirDhahri — APPROVED** [review]

**Pull request merged**
