### PR TITLE
[Pods] Point Podfile to updated Interstellar project

### PR DESCRIPTION
**Pull request by mennenia**
To fix my podfile.lock / build issues :D (which ... others are having too...? I would assume?)

( edit: #trivial )

### CODE REVIEW

**Comment by ashfurrow** [comment]
👍 Good to merge on 🍏

**Comment by orta** [comment]
might need a merge from master to get this commit in https://github.com/artsy/eigen/pull/1614/commits/76a16dccf27d896af3b6cbac2f4480b099c2d9ea

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
        
            1 Warning
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
    
    
  </tbody>
</table>
  

  



Time | Class | Function |
| --- | ----- | ----- |254.6ms | [AuctionViewController.swift](/artsy/eigen/tree/mc-fix-podfile/Artsy/View_Controllers/Auction/AuctionViewController.swift#L181) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
214.8ms | [SwiftyJSON.swift](/artsy/eigen/tree/mc-fix-podfile/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
181.8ms | [WebSocket.swift](/artsy/eigen/tree/mc-fix-podfile/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
82.0ms | [Observable.swift](/artsy/eigen/tree/mc-fix-podfile/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
79.6ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/mc-fix-podfile/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, sideMargin: String)
73.0ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/mc-fix-podfile/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
62.9ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/mc-fix-podfile/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView




<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
Ace 👍

**Pull request merged**
