### PR TITLE
fix: Refetch artwork after editing

### PR DESCRIPTION
**Pull request by olerichter00**
This PR resolves [CX-3357] 

### Description

Refetch artwork after editing

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-3357]: https://artsyproduct.atlassian.net/browse/CX-3357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — COMMENTED** [review]
Does returning the artwork as part of the mutation not fix this?

**Comment by olerichter00** [comment]
> Does returning the artwork as part of the mutation not fix this?

We already do it and it doesn't work :/ I've tried to return the required fields directly in the mutation fragment but still the same result.

**Review by lordkiz — APPROVED** [review]
Thank you @olerichter00 . I think this is even a better approach - as long as we do not mind the necessary repeat request. Nice work 🙏

**Comment by olerichter00** [comment]
Figuring out why the mutation doesn't change the values directly in the Relay store (like how it works when you save an artwort, for example) would be a great topic to explore at a Future Friday.

**Comment by MounirDhahri** [comment]
agree - we can look into refactoring those screens and the logic there soon

**Pull request merged**
