### PR TITLE
Removes rotation support for refine view on iPhone.

### LINKED ISSUE #1095: Auction refine view supports interface orientation
It should not.

### PR DESCRIPTION
**Pull request by ashfurrow**
In this PR, I add two accessible variables to `UIViewController` to give trait-specific answers to "do I support rotation?" and "what orientations do I support?" Note these are based on the controller's trait collection and not on the `UIDevice` class. 

(I know we're trying to avoid device idiom-dependent code, but I feel rotation support does actually fall under the category of device-specific functionality. Happy to discuss though!)

Fixes #1095.

### CODE REVIEW

**Comment by alloy** [comment]
I’m in favour of this :+1: 

Can you file a ticket about how we should apply this change across the codebase in the (maintenance) future?

**Comment by alloy** [comment]
(And rebase please.)

**Comment by orta** [comment]
> (I know we're trying to avoid device idiom-dependent code, but I feel rotation support does actually fall under the category of device-specific functionality. Happy to discuss though!)

Agree :+1:

**Comment by ashfurrow** [comment]
Coooooool, good idea. Merged + opened https://github.com/artsy/eigen/issues/1099

**Comment by orta** [comment]
fail was likely caching, triggered rebuild without cache

**Comment by ashfurrow** [comment]
Coooool

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Warning
    ------------- | ------------
        :warning: | Needs testing on a Phone if change is non-trivial
    

  

  


<p align="right" meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/KrauseFx/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
:green_apple:

**Comment by orta** [comment]
:+1:

**Pull request merged**
