### PR TITLE
fix: fix upper limit label of demand rank #trivial

### PR DESCRIPTION
**Pull request by brainbicycle**
The type of this PR is: **Bugfix**

This PR resolves [CX-783]

### Description

Update upper limit label for demand index progress bar.

### Screenshots 

DemandRankUpdatedAgain

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

[CX-783]: https://artsyproduct.atlassian.net/browse/CX-783

### CODE REVIEW

**Comment by admbtlr** [comment]
Just wrote a comment on this ticket: I feel like the labels should actually be `0` and `10` - `0.0` and `10.0` look a bit silly to me 🤔

**Comment by admbtlr** [comment]
I also realise now that (a) it should probably say _Very strong demand (>**9.0**)_, shouldn't it? (b) The text underneath that sentence contains placeholders

**Comment by brainbicycle** [comment]
> I also realise now that (a) it should probably say _Very strong demand (>**9.0**)_, shouldn't it? (b) The text underneath that sentence contains placeholders

Good catch on the 0.9, I think at some point this value changed from a value between 0 and 1 to a value between 1 and 10. I will update. On the text underneath, that is to spec although I agree it looks a bit weird. https://www.figma.com/file/yDSHlbJVzBxvSUROD2bfRI/Sell-tab?node-id=2943%3A19660

**Comment by samchieng** [comment]
@admbtlr good callout on the labels – lets use `0 – 10` and drop the decimal here. For the actual demand index value, I think we should just use 1 decimal place, i.e. `9.7` instead of `9.73`. If anything is above 9.9, I think we should round down to 9.9 though (10/10 feels odd in concept) for this.

**Comment by admbtlr** [comment]
💯

**Pull request merged**
