### PR TITLE
feat(home view): support a singular Card section and deprecate the current Galleries section component

### PR DESCRIPTION
**Pull request by anandaroop**
This PR resolves [ONYX-1350] 

### Description

> [!NOTE]
> Counterpart of https://github.com/artsy/metaphysics/pull/6116

See that^ description for motivation and caveats.

Visually and functionally there is no change here, but under the hood we have retired the misnamed `HomeViewSectionGalleries` in favor of the new `HomeViewSectionCard`:

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Deprecate HomeViewSectionGalleries in favor of the new HomeViewSectionCard — Roop

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-1350]: https://artsyproduct.atlassian.net/browse/ONYX-1350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 615d20e031ed7991b0175537d83eb8a23108171b
</p>

**Review by dblandin — COMMENTED** [review]
LGTM 👍🏼

**Review by MounirDhahri — APPROVED** [review]
👏

**Comment by anandaroop** [comment]
Had to adjust for #10824 but all good now, merging…

**Pull request merged**
