### PR TITLE
[WIP] @ashfurrow =>  [CI] get makefile running

### PR DESCRIPTION
**Pull request by orta**
Start of the work on greening Travis.

selfie-0

### CODE REVIEW

**Comment by orta** [comment]
Looks like the secure env vars aren't being set, hrm.

**Comment by orta** [comment]
don't think that's a public CI limitation, or we'd hit that on eidolon

**Comment by indiche** [comment]
@orta Version `1.0.0` of `Artsy+UILabels` depends on `Artsy+UIFonts` so `pod install` will ask for github login. I believe updating it to v `1.3.1` should fix the problem.

**Comment by orta** [comment]
Thanks @indiche - good call

**Comment by orta** [comment]
deprecated in favour of #20 

we cannot use secure environment variables in fork'd PRs. Makes total sense, someone could go wild with some of that stuff.

**Pull request closed without merging**
