### PR TITLE
Use AspectFill for Show Image Previews

### PR DESCRIPTION
**Pull request by orta**
The tests don't really do justice to the point as most show preview images are landscape, but now they will fill edge to edge

screen shot 2016-04-18 at 18 09 18

/cc @katarinabatina ( pretty sure you mentioned this to me offhand at some point in the past year or two )

### CODE REVIEW

**Comment by alloy** [comment]
Does this not need to fetch higher-res images in cases like the portrait work in the snapshots?

**Comment by alloy** [comment]
Needs a rebase.

**Comment by ashfurrow** [comment]
Merge had no conflicts, running CI now.

**Comment by alloy** [comment]
@orta I would still like an answer to my question, though.

**Comment by orta** [comment]
Hrm, it _probably_ does, especially on iPads where that could be a long one

**Comment by orta** [comment]
I was less worried about it ( it was already an improvement ) given that most shows have install shots, and most install shots are landscape

**Comment by katarinabatina** [comment]
@orta I think this brings us full circle to a problem we had before where install shots that are more vertically oriented get cut off. Is this logic and improvement on what we had before? We specifically moved away from initial implementation when we launched the ipad. Nick had some very specific ideas for what an improvement would look like in this issue https://github.com/artsy/eigen/issues/415

Could you post a few other examples? From both ipad and iphone before we merge?

**Comment by alloy** [comment]
Filed #1460.

**Pull request merged**
