### PR TITLE
Add the developer extra file to git's ignore index  #trivial

### PR DESCRIPTION
**Pull request by orta**
I also added the ability to declare a PR trivial, and worth skipping the CHANGELOG requirement for Danger.

### CODE REVIEW

**Comment by alloy** [comment]
I’m not 100% how that git command works / what it does, but I know you explained it once and it made sense at the time :)

**Comment by orta** [comment]
Any _future_ changes to that file will be ignored locally, so you can build like this:

``` objc
#import "ARTopMenuViewController+DeveloperExtras.h"
#import "ARSerifNavigationViewController.h"
#import "ARGeneViewController.h"
// You can tell git to ignore changes to this file by running
//
//   git update-index --assume-unchanged Artsy/View_Controllers/App_Navigation/ARTopMenuViewController+DeveloperExtras.m


@implementation ARTopMenuViewController (DeveloperExtras)

// Use this function to run code once the app is loaded, useful for pushing a
// specific VC etc.

- (void)runDeveloperExtras
{
    ARGeneViewController *geneVC = [[ARGeneViewController alloc] initWithGeneID:@"flatness"];
    geneVC.title = @"OK then";

    ARSerifNavigationViewController *nav = [[ARSerifNavigationViewController alloc] initWithRootViewController:geneVC];
    [self presentViewController:nav animated:YES completion:^{

    }];
}

@end
```

and not ship that to everyone else

**Comment by alloy** [comment]
Ah, it's a local config thing :+1:

**Comment by orta** [comment]
@mennenia ^ this exists in folio too

**Pull request merged**
