### PR TITLE
refactor(cleanup): remove test experiment

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves []

### Description

Cleanup test experiment with unleash.

### QA Test Case(s)

| Test Case | Feature | Environment | Acceptance Criteria | Setup Instructions/Link |
| --------- | :-----: | ----------: | ------------------: | ----------------------: |
|           |         |             |                     |                         |

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- removed unleash example experiment - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by gkartalis** [comment]
@pvinis do we also need to remove [this](https://github.com/artsy/eigen/blob/e5e271686baa538ea5048dd0004b48a8e83bde15/src/app/utils/experiments.ts#L8-L15)? I guess not since it is a good example on where we can place the fallbacks 🤔

**Comment by pvinis** [comment]
hm ok so we actually don't have any unleash flags? maybe we should keep the smudge code then 🤔 until we do

**Review by dimatretyak — APPROVED** [review]

**Comment by pvinis** [comment]
i feel scared enabling anyone to do anything in unleash, because we don't have the `readyForRelease`. Its something that we really want to have there before we start adding more serious flags.

I have been slow to make a ticket about this. How about this: I will make a ticket for this on the moplat jira, and tomorrow on mobile practice we could add this quickly, (i don't think it needs a lot of time to add), and then we can merge that too and start telling people to use unleash as the go-to?

**Comment by gkartalis** [comment]
closing this as it is stale, will revisit when we have time 😁

**Pull request closed without merging**
