### PR TITLE
@alloy => Convert App back to Frameworks

### PR DESCRIPTION
**Pull request by orta**
Initial work on converting us back to frameworks. Relies on #998 & #99.

### CODE REVIEW

**Comment by orta** [comment]
I've been wondering about whether this will cause too much problems now that we're using testflight for betas and not enterprise hockey builds. Will ship a test flight beta once I've got a working build.

**Comment by orta** [comment]
Currently blocked by https://github.com/CocoaPods/CocoaPods/issues/4723 - will see where this goes

**Comment by orta** [comment]
OK, hrm, looks like some master merging needs doing.

**Comment by orta** [comment]
This is all good.

**Comment by alloy** [comment]
Have you by any chance tested whether removing the various provisioning profiles from your device makes it launch fast, as mentioned in the startup time ticket?

**Comment by orta** [comment]
I'm not seeing slow-down, either in dev or on deploys (in testflight. ) The issue showed up on enterprise builds. Could be cause I have a relatively new phone, so no profiles around.

**Comment by alloy** [comment]
Well that’s good then :+1:

**Pull request merged**
