### PR TITLE
feat(DIA-470): Add news section

### PR DESCRIPTION
**Pull request by araujobarret**
This PR resolves [DIA-470]  and [DIA-469]

### Description

Extracted and adapted from #9741. Now hidden under the feature flag for QA purposes.

iOS

https://github.com/artsy/eigen/assets/15792853/bfa68ef1-5c51-4456-9dd2-7668a7e1026f

Android

https://github.com/artsy/eigen/assets/15792853/8fb89500-2b84-4d18-9a93-beb9be0c8aff

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- feat: enable news section in the home screen(hidden by ff) - araujobarret

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[DIA-470]: https://artsyproduct.atlassian.net/browse/DIA-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIA-469]: https://artsyproduct.atlassian.net/browse/DIA-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (feat: enable news section in the home screen(hidden by ff) - araujobarret)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bda3befaa2ec209c5248a2f0b588bb04552891dd
</p>

**Review by brainbicycle — APPROVED** [review]
Looks great! Thanks for picking this up / making it good haha! Small request could we update the PR title to have some description?

**Comment by MounirDhahri** [comment]
Looks nice! I must admit though I am not a big fan of its position - the curator's picks rail is one of the most converting rails in the app, it's now even one position lower and I am afraid this will make fewer users see the rail.

**Comment by MounirDhahri** [comment]
If I notice a big shift in the [rail views dashboard](https://artsy.looker.com/dashboards/1682?Collector+Marketing+Tier=1%2C2%2C3%2C4) in Looker, I will let you folks now

**Comment by egdbear** [comment]
😍

**Comment by araujobarret** [comment]
@MounirDhahri a big shift up or down? I don't have access to Looker

**Pull request merged**
