### PR TITLE
feat(CX-2325): Make Scrolling from StickyTabPage Header Possible

### PR DESCRIPTION
**Pull request by lordkiz**
This PR resolves [CX-2325] 

### Description

- This PR wraps the Static Fixed Header Content and Sticky Tab Content in StickyTabPage with a gesture handler that allows users the ability to scroll from the header. Previously users will need to locate the Flatlist beneath the StickyTabPage in order to scroll. This can be problematic when we have a large header and so the Flatlist may be hidden away from view.

https://user-images.githubusercontent.com/18648835/202710671-86b15d7d-dbf7-4a6f-8953-87263ea88049.mov

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [x] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [x] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Make Scrolling from StickyTabPage Header Possible - kizito

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-2325]: https://artsyproduct.atlassian.net/browse/CX-2325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]
Niice thanks Kizito

**Comment by MounirDhahri** [comment]
Feel free to merge once you solve the merge conflict

**Comment by lordkiz** [comment]
#squashongreen

**Comment by MounirDhahri** [comment]
would you mind if you rebase to main 👀

**Pull request merged**
