### PR TITLE
feat(onyx-1280): request push notifications permission from new home view screen

### PR DESCRIPTION
**Pull request by nickskalkin**
This PR resolves [ONYX-1280]

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#nochangelog

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-1280]: https://artsyproduct.atlassian.net/browse/ONYX-1280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nickskalkin** [comment]
@dblandin I've created a ticket to extract all this kind of stuff from the home view screen based on your feedback ([jira](https://artsyproduct.atlassian.net/browse/ONYX-1292)).

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ✅ **No changelog changes**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c53f8447e9b0bb5493cdfefe1100766bb6b039b1
</p>

**Review by olerichter00 — APPROVED** [review]
Do you think we could add a test to make sure it's called when the home screen opens?

**Review by MrSltun — DISMISSED** [review]
🌟🌟🌟

**Review by anandaroop — DISMISSED** [review]

**Review by olerichter00 — APPROVED** [review]

**Pull request merged**
