### PR TITLE
[General] Add support for paragraph spacing in blocks of markdown.

### PR DESCRIPTION
**Pull request by orta**
I got fed up of looking at bodies of text with no spacing between paragraphs, so I've fixed it 👍

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
        
            2 Warnings
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
    
    
  </tbody>
</table>
  

  



Time | Class | Function |
| --- | ----- | ----- |248.6ms | [AuctionViewController.swift](/artsy/eigen/tree/orta-textview_paragraphs/Artsy/View_Controllers/Auction/AuctionViewController.swift#L176) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
205.0ms | [SwiftyJSON.swift](/artsy/eigen/tree/orta-textview_paragraphs/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
192.4ms | [WebSocket.swift](/artsy/eigen/tree/orta-textview_paragraphs/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)




<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
Needs a rebase.

**Comment by ashfurrow** [comment]
Looks 💯

**Comment by orta** [comment]
CI is green, not sure what it's waiting on.

**Pull request merged**
