### PR TITLE
refactor: replace deprecated sans and serif with text

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves []

### Description

refactor: replace deprecated sans and serif with text

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### QA Test Case(s)

| Test Case | Feature | Environment | Acceptance Criteria | Setup Instructions/Link |
| --------- | :-----: | ----------: | ------------------: | ----------------------: |
|           |         |             |                     |                         |

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- replaced deprecated Sans/Serif components with the newer Text - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by pvinis** [comment]
just for context, these are based on https://github.com/artsy/eigen/blob/main/src/palette/elements/Text/index.tsx#L22 and https://github.com/artsy/eigen/blob/main/src/palette/elements/Text/index.tsx#L64

**Review by dimatretyak — APPROVED** [review]

**Comment by gkartalis** [comment]
@pvinis do you think that we could merge this? Or do we have to QA first 😅

**Review by MounirDhahri — APPROVED** [review]
bye Sans
download

**Review by pvinis — APPROVED** [review]
I did not check every single change if it is the right one, I will assume you did it right 👍.

Thank you for removing a bunch of these! We are a very big step closer to removing `Sans` and `Serif` from palette and eigen completely 💜.

**Pull request merged**
