### PR TITLE
fix: QA items for full bleed widget GRO-678

### PR DESCRIPTION
**Pull request by jonallured**
This PR applies a black background to the container for artist name/artwork title and then adds back in the artsy logo. Looks like this:

<details>

Simulator Screen Shot - iPhone 12 Pro - 2021-11-30 at 16 07 05
</details>

The other notable thing out of QA is some image quality feedback but I haven't really noticed this and I'm using the largest image size possible so going to punt on that for now.

https://artsyproduct.atlassian.net/browse/GRO-678

/cc @artsy/grow-devs @kathytafel @pvinis

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **It seems like you added some non WebP images to Eigen, please convert them to WebPs using `source images/script.sh` script **
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f2edb0303bb45099489186b926361071cf22e63c
</p>

**Comment by dzucconi** [comment]
Where is the code that generates the image URL?

**Comment by jonallured** [comment]
Note that I chatted with Damon about image quality and will likely address it in a separate PR. More chatter here:

https://artsy.slack.com/archives/C01ADJNCS5D/p1638311139324800?thread_ts=1638310188.321900&cid=C01ADJNCS5D

And separate Jira ticket here:

https://artsyproduct.atlassian.net/browse/GRO-679

**Comment by jonallured** [comment]
Going to merge this so I can move forward and get to the second type of widget - feel free to chime in with any follow ups if needed!!

**Pull request merged**
