### PR TITLE
@ashfurrow => Update fair artist view

### LINKED ISSUE #24: Remove map button from Artists at the Fair View
_From @katarinabatina on January 13, 2015 20:28_

Current build has the map preview and the button, should remove the button 
current
image

change to 
image

_Copied from original issue: artsy/eigen-private#2116_

### PR DESCRIPTION
**Pull request by alloy**
Fixes #24.

Waiting for follow-up on https://github.com/artsy/eigen/issues/24#issuecomment-72455898.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Failure is [valid](https://eigen-ci.s3.amazonaws.com/snapshots/49178523/index.html) – we'll need to update the screenshots in the unit tests sometime.

**Comment by orta** [comment]
Would recommend running Xcode with my Snapshots plugin, makes it a one-click to replace with new.

**Comment by ashfurrow** [comment]
Good idea ([link](https://github.com/orta/Snapshots)).

**Comment by ashfurrow** [comment]
Alcatraz is still [causing the plugin to crash](https://github.com/orta/Snapshots/issues/18), so you'll need to install from source.

**Comment by alloy** [comment]
@ashfurrow Should be done. For a screenshot see https://github.com/artsy/eigen/issues/24#issuecomment-72666698.

**Comment by orta** [comment]
Might be nice to add a or amend one of those snapshots to show what it looks like with a birthday

**Comment by orta** [comment]
and BETA_CHANGELOG entry please ( it's in the xcproject )

**Comment by alloy** [comment]
> Might be nice to add a or amend one of those snapshots to show what it looks like with a birthday

Good call. Do you want me to add a test+snapshot for the variant where either the artist’s nationality or birth year is unknown?

**Comment by alloy** [comment]
Also, looking at the test fixtures atm, the permutation where there is [no map](https://github.com/artsy/eigen/pull/89/files#diff-2) available has a different margin (less) than when there _is_ a map. I assume there not being a map is a real thing to care about and thus the margin needs fixing?

**Comment by ashfurrow** [comment]
Sounds right.

**Comment by orta** [comment]
Yes to all of those things.
(note, needs rebase)

**Comment by alloy** [comment]
Done all the things.

**Pull request merged**
