### PR TITLE
feature: User on gallery detail page on eigen sees marquee

### PR DESCRIPTION
**Pull request by lilyfromseattle**
[GRO-820](https://artsyproduct.atlassian.net/browse/GRO-820)

This implements the scrolling marquee on the eigen partner page. I used `react-native-text-ticker` to accomplish this, after I tried and failed to do it without an external library. Speed/font/spacing can be adjusted if needed.

https://user-images.githubusercontent.com/5643895/155397365-3b035641-c9f8-4cba-aad8-bd82edae4601.mov

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 80c68a268919717215ac0618638ea77f0833a0d1
</p>

**Comment by jonallured** [comment]
I think you can steal the logic that @The-Beez-Kneez implemented here:

https://github.com/artsy/force/blob/f406bb7f3e875bf84f9eb3ec8cb60001d5c4c8a4/src/v2/Components/Cells/PartnerCell.tsx#L44-L46

**Comment by lilyfromseattle** [comment]
> I think you can steal the logic that @The-Beez-Kneez implemented here:
> 
> https://github.com/artsy/force/blob/f406bb7f3e875bf84f9eb3ec8cb60001d5c4c8a4/src/v2/Components/Cells/PartnerCell.tsx#L44-L46



> I think you can steal the logic that @The-Beez-Kneez implemented here:
> 
> https://github.com/artsy/force/blob/f406bb7f3e875bf84f9eb3ec8cb60001d5c4c8a4/src/v2/Components/Cells/PartnerCell.tsx#L44-L46

I have my logic set up to be a boolean, is it better if I pass in a name?

> I think you can steal the logic that @The-Beez-Kneez implemented here:
> 
> https://github.com/artsy/force/blob/f406bb7f3e875bf84f9eb3ec8cb60001d5c4c8a4/src/v2/Components/Cells/PartnerCell.tsx#L44-L46

I didn't mean to leave that `isBlackOwned=true` in there, I replaced the logic with it to take the video and then forgot to revert, my bad!

**Review by jonallured — DISMISSED** [review]
LGTM!! 🎉

**Comment by The-Beez-Kneez** [comment]
@lilyfromseattle lets make this marquee banner static, and then I will merge it in.

If design comes to a new decision on how they want it to look we can address it in a second version.

**Comment by jonallured** [comment]
Closing in favor of this one: https://github.com/artsy/eigen/pull/6561

**Pull request closed without merging**
