### PR TITLE
@alloy => Fixes to the layouts Auction Results cells - fixes #888

### LINKED ISSUE #888: formatting of auction results looks wonky
image

### PR DESCRIPTION
**Pull request by orta**
Problem 1: We were doing layout maths before we knew the real sizes of cells, so in moving from the datasource creation method to the delegate will show method we can rely on the cell having a size. I discovered this in the AppleTV sample code. Good pattern.

Problem 2: We weren't accommodating the size of the nav buttons since consolidating all the warning labels. This fixes that.

### CODE REVIEW

**Comment by orta** [comment]
Added some tests, contrary to the iPad screenshot they actually render like this: 
screen shot 2015-10-27 at 09 53 52

**Comment by alloy** [comment]
Nice! :+1:

Can has changelog?

**Comment by orta** [comment]
pushed

**Comment by alloy** [comment]
Ace

**Pull request merged**
