### PR TITLE
[CI] Use Xcode 7 for Circle CI

### PR DESCRIPTION
**Pull request by orta**

### CODE REVIEW

**Comment by orta** [comment]
Waiting on them shipping 8.4 as an SDK, talked on their intercom thing.

```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:8.4, name:iPhone 6 }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "Artsy" scheme:
		{ platform:iOS Simulator, id:18AEAA3F-D573-4930-899C-2D8F3BAB3D4A, OS:8.1, name:iPad 2 }
		{ platform:iOS Simulator, id:DA23BCB9-9D1F-4A7F-91D5-A4BF2187F70B, OS:8.2, name:iPad 2 }
		{ platform:iOS Simulator, id:2F39BEF2-E92D-498C-B2D9-29366BD8F732, OS:9.0, name:iPad 2 }
		{ platform:iOS Simulator, id:16439C32-C250-43AF-B6B0-BEE0ADCB56E3, OS:8.1, name:iPad Air }
		{ platform:iOS Simulator, id:1204EC88-5E40-4ACD-96B0-1C233430765D, OS:8.2, name:iPad Air }
		{ platform:iOS Simulator, id:42D87249-99F2-4BC1-9180-317D268C46F7, OS:9.0, name:iPad Air }
		{ platform:iOS Simulator, id:6E2B1E19-6466-4328-917C-16019130FDE8, OS:9.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:19F180FC-792A-4CE6-AF04-0AD2574BE981, OS:8.1, name:iPad Retina }
		{ platform:iOS Simulator, id:92095E7F-6861-4337-84DA-9B74BEE506F0, OS:8.2, name:iPad Retina }
		{ platform:iOS Simulator, id:A1EC86BA-49AB-414B-9C27-2D0F26A34A81, OS:9.0, name:iPad Retina }
		{ platform:iOS Simulator, id:3B1D90AB-FF19-484D-B7A5-9E681C967ECD, OS:8.1, name:iPhone 4s }
		{ platform:iOS Simulator, id:A7EFA55A-C22A-4948-8652-CDDD7BB0F92E, OS:8.2, name:iPhone 4s }
		{ platform:iOS Simulator, id:5EF3DECC-3E8F-41A0-B2CF-DC384A66E12E, OS:9.0, name:iPhone 4s }
		{ platform:iOS Simulator, id:4A75E527-F23C-4D5B-B77B-B16BD45D3233, OS:8.1, name:iPhone 5 }
		{ platform:iOS Simulator, id:A3C721C6-296C-42E0-9F3F-27303A07D050, OS:8.2, name:iPhone 5 }
		{ platform:iOS Simulator, id:24F6F5A0-343E-4C64-9F4C-B50D88F5E99E, OS:9.0, name:iPhone 5 }
		{ platform:iOS Simulator, id:A273FCE7-1FD6-428B-8981-B729AD12AE8D, OS:8.1, name:iPhone 5s }
		{ platform:iOS Simulator, id:335B871B-1AF4-4887-9AF9-23102D04A571, OS:8.2, name:iPhone 5s }
		{ platform:iOS Simulator, id:49DAC9E5-C129-497D-853E-D93BC4BB8A10, OS:9.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:D023EBE5-A459-4C63-8F89-3D03788618CC, OS:8.1, name:iPhone 6 }
		{ platform:iOS Simulator, id:926B7850-2A77-4425-A523-CC85F8D89D7B, OS:8.2, name:iPhone 6 }
		{ platform:iOS Simulator, id:53600017-30F1-428A-A16A-25C6CEDBD849, OS:9.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:0A472471-D45B-4CFE-9177-1F178C70207B, OS:8.1, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:8E6177CA-0D9E-4CB1-8AE1-2B840C61C607, OS:8.2, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:321D1CF5-2514-4897-8B09-C133602F6DB5, OS:9.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:763DC427-F2C5-4AA4-989F-2CA944FA8F04, OS:9.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:011805C3-BB7A-4785-A313-D7AD2AF6DE49, OS:9.0, name:iPhone 6s Plus }
```

**Comment by alloy** [comment]
We’re you able to successfully run the tests locally with Xcode 7 and 8.4? It's been crashing for me.

**Comment by orta** [comment]
I didn't try - I think Jory must be or his PR would fail on his tests

**Comment by alloy** [comment]
@orta How so? I think he added those properties just so he could still use iOS 8/Xcode 6?

**Comment by orta** [comment]
Yeah, looks like the fair map VC tests, and then some keychain changes are needed. Getting this one is on you eigen-ers. For energy it just worked on the 6->7 transition.

screen shot 2015-09-15 at 9 31 13 am

**Comment by orta** [comment]
Looks like  our UIApplication swizzling isn't happening

```
- (BOOL)swizzled_application:(id)app willFinishLaunchingWithOptions:(id)opts
{
    ARPerformWorkAsynchronously = NO;
    [ARRouter setup];

    /// Never run in tests
    [[iRate sharedInstance] setRatedThisVersion:YES];
    return YES;
}

```

**Comment by orta** [comment]
screen shot 2015-09-15 at 4 10 58 pm

All green, waiting on Circle now for 8.4-ness.

**Comment by orta** [comment]
Covered by  #789

**Pull request closed without merging**
