### PR TITLE
@alloy => Refactor the Artwork View Controller tests

### PR DESCRIPTION
**Pull request by orta**
A lot of these tests have many `will` statements and `activelyWaitFor(0.5` things to try deal with synchronicity that we don't have anymore since I killed aysnc networking in tests.

I split out the inquire/buy button tests into it's own class too, to try make it feel less intimidating.

### CODE REVIEW

**Comment by orta** [comment]
There's still some space for de-duping the OHHTTP stuff, but I'm not too bothered there.

**Comment by alloy** [comment]
Sweet :+1: 

Why do some tests still use `will`? Because of UIView stuff?

**Comment by orta** [comment]
Oops, switched them to `to` - passing locally.

**Comment by orta** [comment]
Or not, will take a 2nd look :dancers:

**Comment by orta** [comment]
Looks like we had some code that wasn't using `ArtsyAPI` but was doing it's own networking and thus wasn't being ran synchronous! Fixed.

**Comment by orta** [comment]
This baby is GREEEEEN

Giphy

**Comment by orta** [comment]
from 
```
	 Executed 813 tests, with 0 failures (0 unexpected) in 32.071 (33.064) seconds
```
to
```
	 Executed 807 tests, with 0 failures (0 unexpected) in 25.818 (26.503) seconds
```

**Comment by alloy** [comment]
Awesome :clap:

**Pull request merged**
