### PR TITLE
feat: remove design system v2 things

### PR DESCRIPTION
**Pull request by pvinis**
This PR resolves [] 

### Description

Everything is replaced with the actual value that it has had for a while now. We used to replace `0.3` with `5` pixels for a while. Now we removed the actual `0.3` for the correct v3 value which is `0.5`, which also translates to `5` pixels.

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [x] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by olerichter00 — APPROVED** [review]
🧹 🌟

**Review by gkartalis — DISMISSED** [review]
nice cleanup, will this affect the styling of some sections though? 😬

**Comment by pvinis** [comment]
we should definitely check, but there should be no styling change. the reason is that we already have all v2 made into v3 on the fly, so now that is gone and replaced with the actual values of v3. I guess I could have missed one or two, though. if that happened, then yea maybe some spacer will have the wrong size, if I missed a 0.3 to 0.5 conversation 🤔.

the reason I opened this now is that it's after the release, so we will have time. also, if there is something I missed, it will not be anything big like the text size, it will only be a spacing one, which is pretty easy to fix 😬.

how does that sound?

**Comment by pvinis** [comment]
i think ill generate a beta and merge this on Tuesday, when I'm back.

**Review by dariakoko — DISMISSED** [review]
nice cleanup 💪

**Comment by pvinis** [comment]
this is ready. ill make a quick beta to test things out on phone.

**Comment by gkartalis** [comment]
@pvinis Yell if you need an extra pair of 👁️ for an extra check

**Comment by pvinis** [comment]
just tested the beta, seems great.

**Pull request merged**
