### PR TITLE
chore: update alert screen routes

### PR DESCRIPTION
**Pull request by dblandin**
### Description

Match web routes for deep-link support.

```
/my-profile/saved-search-alerts > /settings/alerts
/my-profile/saved-search-alerts/:id > /settings/alerts/:id/edit
```

This PR resolves [ONYX-542](https://artsyproduct.atlassian.net/browse/ONYX-542) 

https://github.com/artsy/eigen/assets/123595/d7fe5473-e150-44f0-b8d5-c16b20d370f0

cc/ @olerichter00 

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [x] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- chore: update alert screen routes — devon

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- 

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-542]: https://artsyproduct.atlassian.net/browse/ONYX-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 33a855b9ccebe013be441b2336aaeba393207709
</p>

**Review by olerichter00 — DISMISSED** [review]
🌟

**Review by MounirDhahri — COMMENTED** [review]
Nice! this should make it work on iOS. We will need to add `/settings` to `AndroidManifest.xml` as well to make sure the deep link works on Android as well

**Review by MounirDhahri — APPROVED** [review]
🚀

**Pull request merged**
