### PR TITLE
[Onboarding] Hide buttons and text when keychain credentials are displayed 

### LINKED ISSUE #1854: [Onboarding] Hide items when showing progress indicator.
When signing in with keychain credentials, a spinner gets shown in the centre of the view. The text needs to be removed in order to accommodate this. Also remove the buttons.

img_8203

### PR DESCRIPTION
**Pull request by mennenia**
Fix #1854

Is this what you had in mind? 

login

I've decided to WIP this as I'm battling the tests atm.

### CODE REVIEW

**Comment by alloy** [comment]
Yes, that looks perfect! 👍 

(What’s with that black bar at the bottom when you rotate?)

**Comment by mennenia** [comment]
That's my xcode 😅 It's just that the gif recording thing keeps the same bounds, so the sides of the ipad are cut off, and it reveals what's behind.

**Comment by mennenia** [comment]
@alloy this is good to go, if you're happy

**Comment by alloy** [comment]
Yup, very happy 👍 Will merge on green.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |253.1ms | [AuctionViewController.swift](/artsy/eigen/tree/mc-fixspinner/Artsy/View_Controllers/Auction/AuctionViewController.swift#L199) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
214.9ms | [SwiftyJSON.swift](/artsy/eigen/tree/mc-fixspinner/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
193.1ms | [WebSocket.swift](/artsy/eigen/tree/mc-fixspinner/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
94.0ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/mc-fixspinner/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L47) | @objc override func viewDidLoad()
82.5ms | [Observable.swift](/artsy/eigen/tree/mc-fixspinner/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
81.4ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/mc-fixspinner/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
73.3ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/mc-fixspinner/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
67.4ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/mc-fixspinner/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
65.2ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/mc-fixspinner/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Pull request merged**
