### PR TITLE
FX-2213, FX-2214, FX-2215: Adds the Artworks and Exhibitors content to fair page

### PR DESCRIPTION
**Pull request by sweir27**
The type of this PR is: **Enhancement**

This PR resolves [FX-2213], [FX-2214], [FX-2215]

### Description

This PR adds the bottom-of-the-page content to the new fair page, which includes the Exhibitors and Artworks shelves/grid.

Some notes:
- To get the sticky header effect, I used the built-in `stickyHeaderIndices` prop on `FlatList`. It seems to work fine, the only weird thing is that when you click into the "Artworks" tab, the screen jumps. I'm pretty sure this is due to how we lazily-load that artworks grid (as the same does not occur when switching to the "Exhibitors" tab).
- The rest is pretty standard and builds off the logic we have on web.
- In order to validate that the basic layout works as-intended, I also included the animated Filter Button in this PR. Will follow up with the actual filtering behavior.

Screen Shot 2020-09-28 at 11 16 20 AM
Screen Shot 2020-09-28 at 11 16 26 AM
fairtabs

### PR Checklist (tick all before merging)

- [X] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [X] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [X] I have documented any follow-up work that this PR will require, or it does not require any.
- [X] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))

[FX-2213]: https://artsyproduct.atlassian.net/browse/FX-2213
[FX-2214]: https://artsyproduct.atlassian.net/browse/FX-2214
[FX-2215]: https://artsyproduct.atlassian.net/browse/FX-2215

### CODE REVIEW

**Comment by pvinis** [comment]
Good job with the sticky tabs, looks sweeeeet.

About the scrollOffset jump on tab switch, yea, probably it's the lazy loading. I wonder if there is a quick easy way to have something like the placeholders we have with the grey animated boxes. We might need to incorporate this in the InfiniteGrid component. If it's out-of-scope for this PR, we can make a ticket for this, and then just having a few boxes should make it not jump.

**Comment by williardx** [comment]
LGTM! Nice job figuring out the sticky header 💪

**Comment by sweir27** [comment]
Going to merge this in so we can keep building on it, but yeah @pvinis we should have a ticket for the skeleton loading `InfiniteGrid`!

**Comment by pvinis** [comment]
Made one here. https://artsyproduct.atlassian.net/browse/MX-556

**Pull request merged**
