### PR TITLE
feat: notify users when they are not connected

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **Feature**

This PR resolves [CX-1945] and [CX-1923]

### Description
- This PR adds is a suggestion for a modal that shows up when the user has no connection. 
**Note:** This PR does not check if the user has internet access or if they can ping our artsy/google servers (it's something we can do easily though)

Screenshot_1631794790

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Show internet status - mounir

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[CX-1945]: https://artsyproduct.atlassian.net/browse/CX-1945
[CX-1923]: https://artsyproduct.atlassian.net/browse/CX-1923

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Show internet status - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6db9f1207f8dfc8b128e0f97af68dd9e4f95d270
</p>

**Review by brainbicycle — APPROVED** [review]
📶 !

**Review by olerichter00 — APPROVED** [review]
📵 🚀

**Comment by MounirDhahri** [comment]
#squashongreen

**Pull request merged**
