### PR TITLE
[DONT MERGE, CLOSE AFTER RELEASE IS DONE] release 8.0.5 (no reanimated, cherry-picked the rest)

### PR DESCRIPTION
**Pull request by pvinis**
* create initial step of merging autocomplete location

* refactor LocationAutocomplete and remove styled

* use LocationAutocomplete in the previous screens

`ShippingModal`, `MyProfileEditForm`, and SWA `ArtworkDetailsForm`

* add UX enhancement in the edit profile screen

* remove unused components

* remove unneeded async

* rename LocationAutocompleteInput to LocationAutocomplete

* remove old tests and add new test

* feat: allow custom input for location field

* fix: update tests

* feat: show error message when there are no results

+ updating tests

* fix: use `showError` in the SWA flow

* fix: update tests

* fix: update show error logic

* fix: update `||` to `??`

Co-authored-by: Pavlos Vinieratos <pvinis@gmail.com>

Co-authored-by: Pavlos Vinieratos <pvinis@gmail.com>
# Conflicts:
#	docs/troubleshooting.md
#	src/app/Components/DetailedLocationAutocomplete.tsx

### Description

This PR resolves []

#### Acceptance Criteria

-

#### Setup Instructions

-

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by pvinis** [comment]
all green. closing 👍.

**Comment by pvinis** [comment]
cc @rajsam003 @MounirDhahri

**Comment by MounirDhahri** [comment]
Why did you closed this @pvinis ? we will need to keep pushing to it as we fix bugs right?

**Comment by pvinis** [comment]
duh 🤦, i forgot sorry haha. i thought its just for ci and we will open if we have bugs. but it makes sense to keep open.

**Comment by MounirDhahri** [comment]
awesome. thanks a lot @pvinis 🙏

**Pull request closed without merging**
