### PR TITLE
@alloy -> remove opaque view from behind search keyboard

### PR DESCRIPTION
**Pull request by 1aurabrown**

### CODE REVIEW

**Comment by 1aurabrown** [comment]
closes https://github.com/artsy/eigen/issues/538

**Comment by orta** [comment]
*note* this has my [second_curtain fix](https://github.com/ashfurrow/second_curtain/pull/30), you can see all the images now :dancers: 

https://eigen-ci.s3.amazonaws.com//304/index.html

**Comment by orta** [comment]
or maybe the same one four times, hard to tell ;)

**Comment by 1aurabrown** [comment]
fixed the images!!!!!!

**Comment by 1aurabrown** [comment]
what does this mean
```
BlueprintIdentifier = "F82A938C8E623C49A74E330A"
-               BuildableName = "Pods.framework"
+               BlueprintIdentifier = "5E858A9E58475A1006BF493A"
+               BuildableName = "libPods.a"
```

**Comment by orta** [comment]
That isn't a change you want, I would specifically remove that change in `Artsy.xcodeproj/xcshareddata/xcschemes/Artsy.xcscheme`, somehow you've got something pre-frameworks influencing this code.

**Comment by 1aurabrown** [comment]
@orta , ok i reverted it to how it is on master.

**Comment by alloy** [comment]
Perfect, thanks :+1: 

I’m ignoring those three test failures (see #571).

I also keep getting that `ilbPods.a` change in the scheme, I’ll see if I can figure out where it’s coming from.

**Comment by alloy** [comment]
@1aurabrown It’s missing a CHANGELOG btw, can you PR one when you get back?

**Comment by 1aurabrown** [comment]
@alloy yes sorry!

**Pull request merged**
