### PR TITLE
feat: Add trending icon to My Collection artwork detail screen

### PR DESCRIPTION
**Pull request by olerichter00**
The type of this PR is: **Feature**

This PR resolves [CX-2359]

### Description

Adds trending icon to My Collection artwork detail screen if the demand index is higher or equal to 9.

simulator_screenshot_3EC69EF2-536F-4256-9AA1-F08E64DDF668

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [x] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Add trending icon to My Collection artwork detail screen - ole

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[CX-2359]: https://artsyproduct.atlassian.net/browse/CX-2359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Add trending icon to My Collection artwork detail screen - ole)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2c3e8093fe171b4c2b429b3cf7b1517a39b3ae30
</p>

**Review by MrSltun — COMMENTED** [review]
Great work Ole 🔥  Thank you!
but I believe that it should be hidden behind `ARShowDemandIndexHints` feature flag according to the ticket

**Comment by olerichter00** [comment]
> Great work Ole 🔥 Thank you! but I believe that it should be hidden behind `ARShowDemandIndexHints` feature flag according to the ticket

Good catch!

**Comment by olerichter00** [comment]
#squashongreen

**Review by MrSltun — APPROVED** [review]

**Pull request merged**
