### PR TITLE
Update emission to v1.4.0 beta.1

### PR DESCRIPTION
**Pull request by alloy**
Messaging!!

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">No CHANGELOG changes made</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Could not find the commit 344a9dec9c21dad964f38d46e21c678762b6812d in <a href="https://github.com/artsy/eigen-artefacts/">artsy/eigen-artefacts</a>.</p>

<p>You need to <code>git push</code> in the Pods dir.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_travis">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
Looking into this:

```sh
$ bundle exec pod install                                                                                                                                                                                                                                    

Analyzing dependencies
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
Downloading dependencies
Using AFNetworkActivityLogger (2.0.4)
Using AFNetworking (2.5.4)
Using AFOAuth1Client (0.4.0)
Using ALPValidator (0.0.3)
Using ARAnalytics (3.9.0)
Using ARCollectionViewMasonryLayout (2.1.2)
Using ARGenericTableViewController (1.0.2)
Using ARTiledImageView (1.2.0)
Using Adjust (4.11.4)
Using Aerodramus (0.3.1)
Using Analytics (3.0.7)
Using AppHub (0.5.1)
Using Artsy+UIColors (3.1.0)
Using Artsy+UIFonts (3.1.1)
Using Artsy+UILabels (2.2.0)
Using Artsy-UIButtons (2.1.0)
Using Bolts (1.7.0)
Using CocoaLumberjack (2.0.1)
Using DHCShakeNotifier (0.2.0)
Using EDColor (1.0.0)
Installing Emission 1.4.0-beta.1 (was 1.3.9)
Using Expecta (1.0.5)
Using Expecta+Snapshots (3.0.0)
Using Extraction (1.2.3)
Using FBSDKCoreKit (4.10.1)
Using FBSDKLoginKit (4.10.1)
Using FBSnapshotTestCase (2.1.4)
Using FLKAutoLayout (1.0.0)
Using FXBlurView (1.6.1)
Using Forgeries (1.0.0)
Using HockeySDK-Source (4.1.5)
Using ISO8601DateFormatter (0.7.1)
Using Interstellar (2.0.0)
Using JLRoutes (2.0.0)
Using JSBadgeView (1.4.1)
Using JSDecoupledAppDelegate (1.2.0)
Using JWTDecode (2.0.0)
Installing KSCrash 1.15.11 (was 1.15.8)
Using KSDeferred (0.2.0)
Using Keys (1.0.0)
Using MARKRangeSlider (1.0.1)
Using MMMarkdown (0.4)
Using Mantle (1.5.6)
Using MultiDelegate (0.0.2)
Using NAMapKit (3.2.0)
Using NPKeyboardLayoutGuide (1.0.0)
Using Nimble (5.1.1)
Using Nimble-Snapshots (4.3.0)
Using OCMock (2.2.4)
Using OHHTTPStubs (3.1.2)
Using ORKeyboardReactingApplication (0.5.3)
Using ORStackView (2.0.3)
Using ObjectiveSugar (1.1.0)
Using Quick (0.10.0)
Using RSSwizzle (0.1.0)
Installing React 0.45.0-rc.2 (was 0.42.0)
Using ReactiveCocoa (2.5)
Using SDWebImage (3.7.3)
Using SSFadingScrollView (1.1.0)
Installing Sentry 3.1.2 (was 2.1.9)
Installing SentryReactNative 0.14.5 (was 0.8.3)
Using Specta (1.0.5)
Using Starscream (2.0.4)
Using SwiftyJSON (3.1.4)
Using Then (2.1.0)
Using UICKeyChainStore (1.0.5)
Using UIView+BooleanAnimations (1.0.2)
Using VCRURLConnection (0.2.0)
Using XCTest+OHHTTPStubSuiteCleanUp (1.0.0)
Installing Yoga 0.45.0-rc.2.React (was 0.42.0.React)

[!] Error installing Yoga
[!] /usr/local/bin/git clone /Users/eloy/Code/React/react-native /var/folders/xk/xbld2_2511b3xc5_8fsfddx40000gn/T/d20170707-51756-rphm74 --template= --single-branch --depth 1 --branch v0.45.0-rc.2

fatal: repository '/Users/eloy/Code/React/react-native' does not exist
```

**Comment by orta** [comment]
I don't see anything implying a local path for Yoga in the Podspec: https://github.com/artsy/Specs/commit/682709e07b8696a482a8c1b41e48e3509eccb4da

**Comment by orta** [comment]
There's nothing about it in the Podfile, or Podfile.lock which could override the Yoga dep

**Comment by orta** [comment]
Gonna try specifying Yoga, maybe this should move into Emission too

**Comment by orta** [comment]
Converting to use release'd Yoga in Podfile:

```ruby
  pod 'Yoga', {    :git => 'https://github.com/facebook/yoga.git',    :tag => '1.5.0',  }
```

Gives: 
```
[!] Unable to satisfy the following requirements:

- `Yoga (from `https://github.com/facebook/yoga.git`, tag `1.5.0`)` required by `Podfile`
- `Yoga (= 0.45.0-rc.2.React)` required by `Emission (1.4.0-beta.1)`

Specs satisfying the `Yoga (from `https://github.com/facebook/yoga.git`, tag `1.5.0`), Yoga (= 0.45.0-rc.2.React)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by orta** [comment]
They recommend explicitly adding Yoga: http://facebook.github.io/react-native/releases/0.46/docs/integration-with-existing-apps.html#3-install-cocoapods

screen shot 2017-07-07 at 10 51 52

**Comment by orta** [comment]
OK, I get it now: https://github.com/artsy/Specs/blob/master/Yoga/0.45.0-rc.2.React/Yoga.podspec.json

We ship our own Yoga, which resolves first. This one is what has the bad URL.

**Comment by orta** [comment]
OK, looks like I can just change that URL to `facebook/react-native` - will do that

**Comment by orta** [comment]
That worked, re-running build.

**Comment by orta** [comment]
Tests are failing because emission has looser requirements on nullability than Eigen:

```sh

❌  /Users/distiller/eigen/derived_data/Build/Products/Debug-iphonesimulator/Emission/Emission.framework/Headers/ARInboxComponentViewController.h:5:4: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]

- (instancetype)initWithInbox;
   ^


❌  /Users/distiller/eigen/derived_data/Build/Products/Debug-iphonesimulator/Emission/Emission.framework/Headers/ARInboxComponentViewController.h:8:44: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]

                      moduleName:(NSString *)moduleName
                                           ^


❌  /Users/distiller/eigen/derived_data/Build/Products/Debug-iphonesimulator/Emission/Emission.framework/Headers/ARInquiryComponentViewController.h:5:50: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]

@property (nonatomic, strong, readonly) NSString *artworkID;
                                                 ^


❌  /Users/distiller/eigen/Artsy/App/ARAppDelegate+Emission.m:24:9: could not build module 'Emission'

#import <Emission/AREmission.h>
```

**Comment by orta** [comment]
Looks like someone missed the `NS_ASSUME_NONNULL_BEGIN` etc on that class, will look to see if I can it turned on in emission, and I'll see if I can temporarily turn it off for this PR on Eigen

**Comment by orta** [comment]
Got a meeting, cause is likely because these VCs are in a pod - those warnings are harder to see. Got an idea.

**Comment by orta** [comment]
Cool, this is now only red on Danger.

**Comment by orta** [comment]
Alright, this is looking 👍

**Pull request merged**
