### PR TITLE
@ashfurrow => [WIP] [Pods] Migrate to CocoaPods frameworks

### PR DESCRIPTION
**Pull request by orta**
This isn't prime-time yet, but I wanted to throw a few hours to get a sense what it's like to migrate. I was pleasantly surprised that I was 90% done within 20 minutes. That was mostly updating CocoaLumberjack and making my own fork of AFNetworking with compiler-time checking for System Configuration removed.

screen shot 2015-05-11 at 10 30 35

WIP because fonts.

### CODE REVIEW

**Comment by alloy** [comment]
Sweet 👌🏿

**Comment by orta** [comment]
OK, this is probably good. I expect it to fail, because the font is a _newer_ font, which has a pretty significant difference on tracking between letters. Ideally we should have a webpage we can see the difference on when it reds.

**Comment by alloy** [comment]
Assigning this to @ashfurrow for during his Q&A time.

**Comment by ashfurrow** [comment]
Is this still a WIP? It needs a merge if we want to continue going with this branch.

**Comment by orta** [comment]
closing in favour of #520

**Pull request closed without merging**
