### PR TITLE
@ashfurrow => [ArtworkView] Fix crash when changing orientation during sign-in.

### LINKED ISSUE #494: Login causes app to crash
Start app, tap you, log in, enter credentials, crash

### PR DESCRIPTION
**Pull request by alloy**
Fixes #494

### CODE REVIEW

**Comment by alloy** [comment]
I _should_ probably create a reduction sample and file a radar, but our release is more important atm.

**Comment by orta** [comment]
cray

**Comment by ashfurrow** [comment]
👏🎉👍💥☕️😻🍰🎀

**Comment by alloy** [comment]
Woohoo, confetti-coffee-cake-cat combo multiplier!

**Pull request merged**
