### PR TITLE
fix(ONYX-182): My collection pills animation transition on android

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR resolves [ONYX-182] 

### Description

https://github.com/artsy/eigen/assets/11945712/25cddd72-41dc-4e1b-8c5a-9abdfa2f0f68

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- fix my collection filtering pills animation transition on android - mounir

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-182]: https://artsyproduct.atlassian.net/browse/ONYX-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (fix my collection filtering pills animation transition on android - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 48279af4647e75ae25948d9bad15d2b56dc6b7e1
</p>

**Review by olerichter00 — APPROVED** [review]
Thanks for the fix 🌟

**Review by dariakoko — APPROVED** [review]
Thank you!
Do you know what exactly in the `Tabs.Scrollview` affected the performance on Android?

**Comment by dariakoko** [comment]
Ah got it now

**Pull request merged**
