### PR TITLE
feat: react 17 FC types

### PR DESCRIPTION
**Pull request by pvinis**
The type of this PR is: **Enhancement**

This PR resolves []

After #6449 and a bunch of comments there and a friend (hey @bitttttten), I realized that `@types/react` [exports](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L66) `React` types as globals, which makes our types simpler. We don't even need to `import { FC } from "react"` to keep our `FC`s! We can just change them to `React.FC` and then magically have the types globally, which is so nice.

In this PR I change all our `FC`s to `React.FC`s, same for `ReactNode`.

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

### CODE REVIEW

**Comment by bitttttten** [comment]
👋

You can reference all types from the namespace React without needing to import them or importing "React". So React.HTMLProps, React.ReactNode, React.ComponentProps, and so on. For everything else, so the things used at runtime like Fragment, useMemo, etc. I would import.

**Review by damassi — DISMISSED** [review]
I actually didn't know this! But i guess it makes sense since i've been adding these types a lot   and we already have React 17 in force, and we never import it. Lol, just never noticed i guess, but that's cool👌

**Comment by damassi** [comment]
> Maybe also React.Component is clearer here? I have no preference here, so maybe we keep it consistent? My only reason for going with just Component was to avoid the React import, and just import what we actually need/use. 

No pref! if `React.Component` works globally without import might be a bit nicer. (Haven't looked at class components in a long while and had to use one the other day and totally forgot how to type props / state, etc)

**Comment by pvinis** [comment]
unfortunately it requires an import 😬. so it's either import React or import just Component 🤷‍♂️

**Comment by pvinis** [comment]
nice. yea I kinda like just Component too.

oh yea, I definitely will make an RFC 😁. I still think FC is a worse option, but no imports at least make it clean haha. It has not changed my mind about anything else, I very much want to trial and evaluate not using FC.

**Pull request merged**
