### PR TITLE
fix: enable scroll only when there is more than one elements in the a…

### PR DESCRIPTION
**Pull request by dariakoko**
This PR resolves [] 

### PR Checklist

Enable scroll on the activity screen only when there is more than one elements in the array

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- enable scroll on the activity screen only when there is more than one elements in the array - daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (enable scroll on the activity screen only when there is more than one elements in the array - daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b484b97b5b2e82cdda1c242b982a70256ac4ebca
</p>

**Review by olerichter00 — COMMENTED** [review]
@MounirDhahri, this bug might be related to the new [Screen.StickySubheader](https://github.com/artsy/eigen/blob/e7dc477974216318f0f9376134e51790cd20954a/src/app/Scenes/Activity/NewActivityScreen.tsx#L54) component. It seems like the sub header is collapsing when scrolling and then abruptly jumping back. I'm fine with addressing this bug as proposed in this PR, but we could see the same issue later with a similar layout: Screen header + FlatlistComponent and content that doesn't fill the entire screen. Do you have any ideas on how we could resolve the root issue instead of just disabling scrolling?

**Comment by MounirDhahri** [comment]
Thanks Daria for the fix but I agree with @olerichter00 I think this should be fixed in `palette`. I will work on it today

**Comment by MounirDhahri** [comment]
I am still trying to come up with a good fix for this but with no success - i will push a temporary fix here since this PR breaks the refresh control

**Pull request merged**
