### PR TITLE
refactor(app): Cleanup and consolidate application folder structure

### PR DESCRIPTION
**Pull request by damassi**
Related: https://github.com/artsy/energy/pull/386

### Description

This PR simplifies Eigen's top-level folder structure by consolidating related things and introducing a `system` "framework" directory, where all framework-level things should live. This mirrors patterns we've setup in our other webapps as well as recently added to energy, which better reflects the actual physical structure of the app.

The idea is: Most of the folders that were in `src/app` remain untouched for 90+% of product dev, and folks don't need to know about them. The things that devs do need to worry about are things they touch on a regular basis.

**Before**

Screenshot 2023-01-19 at 9 57 32 PM

**After**

Screenshot 2023-01-19 at 9 55 00 PM

Now, at a glance, one can hop into Eigen and get an immediate view into the most important / actually-used sections of the codebase without having to wade through less trafficked areas. 

cc @artsy/mobile-platform 

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by pvinis — DISMISSED** [review]
with 800 files, this def needs a message on practice to check if anyone if anyone is in the middle of a big PR. merge when ready

**Review by MounirDhahri — APPROVED** [review]
I love this improvement a lot 👏👏👏

**Review by gkartalis — DISMISSED** [review]
Nice one! There are some test failures but I think that is due to a missing rename of a path 🤔

**Comment by damassi** [comment]
Alright, left a message! 

#squashOnGreen

**Pull request merged**
