### PR TITLE
@1aurabrown => Travis Stability

### PR DESCRIPTION
**Pull request by orta**
Improves the worst offenders for stability, makes a few others pending.

### CODE REVIEW

**Comment by 1aurabrown** [comment]
@orta is the failure expected?

**Comment by 1aurabrown** [comment]
also what happened to second curtain on travis?

**Comment by orta** [comment]
second_curtain should be working fine I think. 
I've updated us to the latest specta/expecta

**Comment by 1aurabrown** [comment]
I saw snapshot failures on travis for this PR but didn't see any link to view the diffs :-/Sent using CloudMagicOn Fri, Feb 13, 2015 at 14:59,  artsy/eigen <reply@reply.github.com> wrote:            second_curtain should be working fine I think. 
I've updated us to the latest specta/expecta

**Comment by orta** [comment]
I've been force pushing amend'd commits, so the ld builds don't reference a commit in history. Thus are deleted.

**Comment by 1aurabrown** [comment]
When i've amended and pushed again, i think second curtain has still sent snapshots to amazon and printed a url to view them, but i'm not positiveSent using CloudMagicOn Fri, Feb 13, 2015 at 15:01,  artsy/eigen <reply@reply.github.com> wrote:            I've been force pushing amend'd commits, so the ld builds don't reference a commit in history. Thus are deleted.

**Comment by orta** [comment]
Yeah the second curtain references should still exist, somewhere

**Comment by 1aurabrown** [comment]
Anyway were the failures expected/should this be merged?Sent using CloudMagicOn Fri, Feb 13, 2015 at 15:05,  artsy/eigen <reply@reply.github.com> wrote:            Yeah the second curtain references should still exist, somewhere

**Pull request closed without merging**
