### PR TITLE
feat: fix swa buttons

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR resolves [APPL-331] & [APPL-332] 

### Description

https://user-images.githubusercontent.com/11945712/223442231-6e64b4f3-2001-4361-9ad8-718e179fbff5.mov

https://user-images.githubusercontent.com/11945712/223442242-33d26814-6e9f-4af4-94c4-927cd86fab48.mov

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

#nochanges 

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[APPL-331]: https://artsyproduct.atlassian.net/browse/APPL-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPL-332]: https://artsyproduct.atlassian.net/browse/APPL-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by gkartalis — COMMENTED** [review]
Thanks for addressing this! I think though that this PR resolves only 321.

The other issue [APPL-321](https://artsyproduct.atlassian.net/browse/APPL-321) is about this cutt off (highlighted with red):
Screenshot 2023-03-07 at 15 43 19

**Comment by MounirDhahri** [comment]
good catch, I missed that

**Comment by MounirDhahri** [comment]
Here it is 

https://user-images.githubusercontent.com/11945712/223460269-cf6f1c9a-3dc9-49a5-be46-441a294ee652.mov

**Review by gkartalis — APPROVED** [review]
noice! Thanks!

**Review by olerichter00 — APPROVED** [review]
Thanks for the fix 🌟

**Pull request merged**
