### PR TITLE
@alloy -> make sure image can zoom in desired frame

### PR DESCRIPTION
**Pull request by 1aurabrown**
fixes https://github.com/artsy/eigen/issues/503

### CODE REVIEW

**Comment by orta** [comment]
smart :+1:

**Comment by alloy** [comment]
Perfetto!

**Comment by alloy** [comment]
@1aurabrown Errr, missed this. Can you CHANGELOG please? :)

**Comment by 1aurabrown** [comment]
Yes sorry 😑

**Pull request merged**
