### PR TITLE
@orta => [Artwork] Enable Markdown support in "More Info: view

### LINKED ISSUE #736: [Artwork] Render Markdown in "More Info" sections
See unrendered Markdown:
Screenshot

### PR DESCRIPTION
**Pull request by jorystiefel**
Fixes #736.

### CODE REVIEW

**Comment by alloy** [comment]
What’s the problem here with the github credentials being required on CircleCI?

**Comment by orta** [comment]
No idea, we've not changed anything to my knowledge ( unless we've somehow revoked the API keys )

**Comment by alloy** [comment]
Oh, I now remember @ashfurrow saying something about revoking keys because CircleCI said we were leaking them, don’t know specifics yet, though.

**Comment by alloy** [comment]
Fixed the CI issues.

@jorystiefel Can you rebase this branch please?

**Comment by orta** [comment]
the build timeout'd so I'm re-running, if not I think this is good to go.

**Comment by orta** [comment]
:+1:

**Pull request merged**
