### PR TITLE
fix: submit artwork from my collection

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR resolves [] 

### Description

This PR comes as a follow-up on https://github.com/artsy/eigen/pull/10466. 
- We need to navigate to complete your submission step on draft submissions instead of the shipping location
- When an artwork is submitted through my collection, we need to create a submission at the title step since it's not going to be there (because we skipped the creation that is supposed to happen at the artist step)

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- fix submit artwork from my collection - mounir

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (fix submit artwork from my collection - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0b4c1b96ebccd3b7654898697e16ad0179d3272e
</p>

**Review by olerichter00 — APPROVED** [review]
The [createConsignmentSubmission](https://github.com/artsy/metaphysics/pull/5803) mutation now supports creating a submission from an artwork by only passing `myCollectionArtworkID`. When the artwork ID is passed all necessary data from the Gravity artwork will be used to create the submission. This might simplify things a lot in Eigen.

**Comment by MounirDhahri** [comment]
oh yeah! I will make that update in this PR <3

**Comment by MounirDhahri** [comment]
I tried to do that in the PR but I think it deserves it own PR because I would need to also update submit from my collection

**Pull request merged**
