### PR TITLE
Update PhotoPlaceholder

### PR DESCRIPTION
**Pull request by patrinoua**
The type of this PR is: **feat**

Improvements to Photo and PhotoPlaceholder

before
Screenshot 2022-03-10 at 17 25 19

after
Screenshot 2022-03-10 at 17 24 28

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

ⓘ 'User-facing' changes will be published as release notes.

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4758016ce3ef4ff271e0ea665520c102374ca380
</p>

**Review by AlicanAkyuz — CHANGES_REQUESTED** [review]
This UI change looks really good to me 🔥  

however, if you remember, we had a chat about aligning the placeholder UI with the uploaded image UI. With these change, there'll be a visible difference between those (like in the photo below). I'd therefore ask either updating the uploaded image UI or making these changes in the placeholder align with the current UI. 

Simulator Screen Shot - iPhone 11 Pro Max - 2022-03-11 at 10 18 44

**Comment by patrinoua** [comment]
@AlicanAkyuz thanks for noticing that, I've updated it and it looks like that now.

I also noticed that when there was an error there was no size to display and "Delete" was appearing somewhat to the left so I added a fixed space to the size place holder which takes care of that.

Screenshot 2022-03-11 at 11 20 36

**Review by kiryl-zubarau — APPROVED** [review]
LGTM!

@patrinoua Could you please add updated screenshot with placeholder and uploaded image?

**Review by AlicanAkyuz — APPROVED** [review]

**Pull request merged**
