### PR TITLE
fix: hot reload when app is run using yarn start

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR fixes hot reloading issues on Eigen

### Description

https://github.com/artsy/eigen/assets/11945712/29e9491f-928b-4fc1-9b1f-9142f8d436f4

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by MounirDhahri** [comment]
signing off, will add more description tomorrow

**Review by damassi — APPROVED** [review]
Thank you!

**Review by gkartalis — APPROVED** [review]
wooohooo

**Comment by damassi** [comment]
cc @pvinis - another one you might be happy to see

**Comment by pvinis** [comment]
fun! thanks for tagging me on these!

the name bit of the concurrently didn't need to leave, I wonder why its gone 🤔. it wasn't causing this right?

**Comment by damassi** [comment]
Nope, it was the 
```
require("../../../../../data/complete.queryMap.json")
``` 
bit!

**Comment by dimatretyak** [comment]
will it work if the `complete.queryMap.json` file will be deleted/will be empty? I get an error

**Pull request merged**
