### PR TITLE
fix: Normalize query in My Collection select artist modal

### PR DESCRIPTION
**Pull request by olerichter00**
### Description

Normalize query in My Collection select artist modal to be able to search without Umlaute.

| Before | After |
| --- | --- |
|Simulator Screen Shot - iPhone 13 Pro - 2022-08-23 at 12 33 23 |Simulator Screen Shot - iPhone 13 Pro - 2022-08-23 at 12 31 33 |

#### Acceptance Criteria

-

#### Setup Instructions

-

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Normalize query in My Collection select artist modal. - ole

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by MrSltun — APPROVED** [review]
🌟

**Comment by MrSltun** [comment]
I just noticed something in the screenshot with the error, the cancel button is in the middle instead of next to the input field

**Comment by olerichter00** [comment]
You're right! I remember adding the bug to the board in the QA session. Have we actually created tickets for these bugs?

**Comment by MrSltun** [comment]
Not sure really, I remember fixing it before on one of the PRs, not sure if it got merged or not 😅

**Pull request merged**
