### PR TITLE
fix(CX-3581): adjust images container naf the text in the footer

### PR DESCRIPTION
**Pull request by dariakoko**
This PR resolves [CX-3581] 

### Description

simulator_screenshot_5DF8EF15-0902-4DF5-8709-08E05BCDB71F

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Small design adjustments on the SWA landing page 

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-3581]: https://artsyproduct.atlassian.net/browse/CX-3581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MrSltun — APPROVED** [review]
Looks great!! 🌟🌟
I just added Mounir as a reviewer since he recently changed the images in #8402

**Review by MounirDhahri — CHANGES_REQUESTED** [review]
I was requested to change the images above by Dasha, did the crop change again? I also find the new images really big and would suggest compressing them first to avoid increasing the bundle size

**Comment by dariakoko** [comment]
@MounirDhahri Yesss, Dasha requested changes, I downloaded the images from [Figma](https://www.figma.com/file/WgcIDeIJkytjcCRkpEcUE9/Sell-with-Artsy---CX?node-id=1594-7263&t=038zCqGvLyJWZlKY-11)

**Review by MounirDhahri — APPROVED** [review]
Thanks Daria - sounds good

**Pull request merged**
