### PR TITLE
chore: Only show published heroes even for admins DIA-75

### PR DESCRIPTION
**Pull request by jonallured**
Quick little PR to reverse the behavior of the app from including unpublished hero units to excluding them even for admins. My thought was that they would want to see them so that they could do QA but web is sufficient for this. More chatter here:

https://artsy.slack.com/archives/C054P6V8HQQ/p1689948709667389

https://artsyproduct.atlassian.net/browse/DIA-75

/cc @artsy/diamond-devs

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against eacded185d9bba54bbd29d8d64c515ee2f1bf77c
</p>

**Review by araujobarret — APPROVED** [review]

**Comment by araujobarret** [comment]
@jonallured please don't remove the PR template, we use some automation to get the changelog for the release, we aim to help release captains with it(#superImportant).

**Comment by jonallured** [comment]
@araujobarret hrm but I have my own PR template... 🤔

**Comment by araujobarret** [comment]
Why don't you use the template of the repo? 😂 
We need to rely on the current template because of the automation and the release process we have, otherwise, we make the release captain tasks harder when comes to collecting changing, ping all teams related, condensing release notes and etc.

**Comment by jonallured** [comment]
I open my PRs from the command line and included in the arguments to that PR is a standard template that I use for all my Artsy PRs. I will try to remember this and open Eigen PRs from the GitHub UI but I wish the automation could be achieved another way...

**Pull request merged**
