### PR TITLE
@alloy -> simplify switch view, clean up constraint problems

### PR DESCRIPTION
**Pull request by 1aurabrown**
fixes most of this: https://github.com/artsy/eigen/issues/383

The snapshot diff isn't addressed, but i fixed places where constraints involving a nil view were causing a crash. also cleaned up the switch view.

### CODE REVIEW

**Comment by alloy** [comment]
Awesome :clap: 

Can you add a beta changelog?

**Comment by 1aurabrown** [comment]
Will do! I don't know why I always forget to do that.

On Wed, Apr 22, 2015 at 06:44, artsy/eigen
<reply@reply.github.com>
wrote:
Awesome:clap: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f44f.png]

Can you add a beta changelog?

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/pull/386#issuecomment-95131181] .[https://github.com/notifications/beacon/ADBlTuMqFmKL_ClVZH-v_Dw_WZAD4hLwks5oB3MTgaJpZM4EFlQg.gif]

**Comment by 1aurabrown** [comment]
@alloy   updated

**Comment by alloy** [comment]
Ah didn’t see that an entry was added!

**Comment by alloy** [comment]
Oh, you did that just now? :D

**Comment by 1aurabrown** [comment]
did travis run on this? i'd like to see if it passed.

**Comment by 1aurabrown** [comment]
lol is travis totally disconnected at this point?

**Comment by orta** [comment]
Yep. It wasn't doing us any good seeing constant reds. #383 should ideally bring it back.

**Pull request merged**
