### PR TITLE
chore: AMBER-671 - add exclusive access to saved artworks items

### PR DESCRIPTION
**Pull request by Mitch-Henson**
This PR resolves [AMBER-671] 

### Description

Adds the text `Exclusive Access` to saved unlisted artworks.

<details><summary>Screenshots</summary>
Screenshot 2024-05-07 at 14 39 03
Screenshot 2024-05-07 at 14 56 33

</details>

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#nochangelog

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[AMBER-671]: https://artsyproduct.atlassian.net/browse/AMBER-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ✅ **No changelog changes**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2eead1a5ac4ef6158f26b542d3f873b0802ae7f8
</p>

**Review by jpotts244 — COMMENTED** [review]
Very nice ✅ 

I would just add note to the changelog section of this PR to denote your user facing changes!

**Comment by Mitch-Henson** [comment]
@jpotts244 I thought about adding it, but wasn't sure because not everyone is going to see this functionality and didn't know the protocol there. It is kind of ... _exclusive_. Happy to add it if you think? Curious what @damassi says too? It will affect my other coming PR as well

**Comment by jpotts244** [comment]
I think it might be helpful for internal tracking, I know we have been adding to the changelog for other PRs
https://github.com/artsy/eigen/pull/10178#issuecomment-2087335917

**Pull request merged**
