### PR TITLE
fix: partner name android not truncated properly

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [ONYX-1374] 

### Description

After an offline discussion with @dariakoko we decided to address that here and open a thread (link pending) and fix the issue on another PR on palette level.

Reasoning:

- our text component has some issues in its implementation and does not respect some prop inheritance
- moving the selectable from the text in palette does fix this issue but creates another issue of people not being able to select and copy text in ios and android apps.

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

- partner name android not truncated properly 

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-1374]: https://artsyproduct.atlassian.net/browse/ONYX-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Android user-facing changes (partner name android not truncated properly - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a73a59642f91fe31573c131f43dadbdac9cff400
</p>

**Review by anandaroop — APPROVED** [review]
To confirm: this is the quick fix but not the ideal fix, which will come in a future release, yes?

**Comment by gkartalis** [comment]
@anandaroop exactly will follow up with a thread

**Comment by dariakoko** [comment]
Thanks George!

**Pull request merged**
