### PR TITLE
@1aurabrown => Add tests for fixed masonry layout

### PR DESCRIPTION
**Pull request by alloy**
These are the tests that shows the behaviour that was fixed in #391.

### CODE REVIEW

**Comment by alloy** [comment]
Specifically this commit https://github.com/artsy/eigen/commit/0a62ee9aa6aff81f42c33d44a8cddd228663e77d

**Comment by orta** [comment]
niiiice

**Comment by 1aurabrown** [comment]
Awesome.

Personally, I think the threshold should be greater that 50%, but that's a design decision, not an implementation issue.

**Comment by alloy** [comment]
@1aurabrown Yarr. Be sure to screenshot cases where you feel it can be improved, this was intentionally naive.

**Pull request merged**
