### PR TITLE
feat(CX-2297): Artwork Detail Page | Status Explanatory Page (what's this)

### PR DESCRIPTION
**Pull request by dariakoko**
The type of this PR is: **Feature**

This PR resolves [CX-2297]

### Description

Added a new scene for Artwork Submission Status Explanatory Page

https://user-images.githubusercontent.com/36167539/154115037-1e6fbd23-1b0b-4d34-b8bb-9ad403cfb4d3.mp4

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- added an Artwork Submission Status Explanatory Page -daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[CX-2297]: https://artsyproduct.atlassian.net/browse/CX-2297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (added an Artwork Submission Status Explanatory Page -daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c0b55a894e0047a5d8581822ff6b21fd36d879f3
</p>

**Comment by dariakoko** [comment]
> Nice work @dariakoko . 👍 However, we'd like to have a reusable tooltip component so that we can replace all the various `What is this?`s with this tooltip component. That way we can have a consistent behaviour wherever tooltips are used. I think an easy solution might be having a screen that receives JSX.Element prop which it subsequently displays.

Hey @lordkiz I'm doing it in a separate branch 👍

**Review by lordkiz — APPROVED** [review]
🎉

**Comment by lordkiz** [comment]
#squashongreen

**Pull request merged**
