### PR TITLE
[Admin] Support running Emission from a local packager

### PR DESCRIPTION
**Pull request by orta**
works with https://github.com/artsy/emission/pull/338

### CODE REVIEW

**Comment by alloy** [comment]
So no other React subspecs were needed after all?

**Comment by orta** [comment]
All subspecs are merged post-resolve, so Emission/AppHub bring their own subspecs along for the ride

**Comment by alloy** [comment]
I see. Ok, I can get with this 👍

**Comment by sarahscott** [comment]
Amazing work @orta !! This is going to make certain things so much easier!

**Pull request merged**
