### PR TITLE
feature(android): adding android app shell!

### PR DESCRIPTION
**Pull request by pvinis**
The type of this PR is: **Feature**

This PR resolves [869]

### Description
Screenshot 2021-01-13 at 13 32 33

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

[CX-434]: https://artsyproduct.atlassian.net/browse/CX-434

### CODE REVIEW

**Review by ds300 — APPROVED** [review]
🤖

**Comment by MounirDhahri** [comment]
Nice! thanks!

**Comment by admbtlr** [comment]
🎉 🎉 🎉 We should probably update the README with Android instructions, right?

**Comment by pvinis** [comment]
yup. after the build setup is done, so we know what is needed exactly 👍.

**Pull request merged**
