### PR TITLE
@jorystiefel => Fix app notification badge not being cleared

### LINKED ISSUE #724: [Notifications] Badge remains when count is 0
Maybe this has to do with reading notifications on the web and then coming back to the app? Not sure yet.

### PR DESCRIPTION
**Pull request by alloy**
Fixes #724.

### CODE REVIEW

**Comment by alloy** [comment]
Wait, forgot to add a test for this.

**Comment by alloy** [comment]
@jorystiefel This is done.

**Comment by orta** [comment]
aww, at this failures :-/

**Comment by alloy** [comment]
Well, I give up on those time-out issues for now. I’ve send CircleCI a tweet http://twitter.com/alloy/status/638713174926196737.

The tests pass locally for me.

**Comment by jorystiefel** [comment]
Notification: this PR is 👍

**Pull request merged**
