### PR TITLE
fix: Allow My Collection artworks without artist

### PR DESCRIPTION
**Pull request by olerichter00**
[Slack Thread](https://artsy.slack.com/archives/C01B2P6LJUU/p1652404071482149)

Description

This change prevents the My Collection queries and screens from failing if artworks don't have artists. Since we do not validate the presence of artists, this case is to be expected.

**Screens showing My Collection artworks without artists:**

| | |
| --- | --- |
| Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-20 at 10 24 28 | Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-20 at 10 14 20 |

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Allow My Collection artworks without artists - ole

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by dariakoko — COMMENTED** [review]
Thank you @olerichter00
What will happen if we edit this artwork? 
1 - edit the name of it, for example
2 - edit the artist name

**Comment by olerichter00** [comment]
> What will happen if we edit this artwork?
1 - edit the name of it, for example
2 - edit the artist name

@dariakoko, good point! I've checked and the artwork form doesn't crash (just doesn't show the artist name). At the moment it's not possible to change the artist of an artwork anyway.

**Review by MounirDhahri — APPROVED** [review]
Thanks for making this fix Ole - maybe we can as well instead of showing no artist title, show `-` instead as an artist name inside my collection list. For the artwork screen, no need to

**Review by MrSltun — DISMISSED** [review]
Thanks for the fix Ole! 🌟 
I like the idea that Mounir suggested 👆 but also feel free to merge :)

**Review by dariakoko — DISMISSED** [review]
🙌 
Agree with Mounir and Sultan

**Comment by olerichter00** [comment]
@MounirDhahri Good idea! I'll do the change.

**Pull request merged**
