### PR TITLE
chore: remove algolia-backed components

### PR DESCRIPTION
**Pull request by dblandin**
This PR resolves [ONYX-18](https://artsyproduct.atlassian.net/browse/ONYX-18)

### Description

Removes Algolia-backed components and any Elastic/Algolia feature flagging in favor of components/queries that are fully backed by Metaphysics.

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Dev changes

- remove Algolia-backed components and any Elastic/Algolia feature flagging in favor of components/queries that are fully backed by Metaphysics.

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-18]: https://artsyproduct.atlassian.net/browse/ONYX-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dblandin** [comment]
fyi — this likely supersedes the work started in [this branch](https://github.com/artsy/eigen/compare/anandaroop-rajsam003/FX-4785-cleanup-algolia?expand=1).

**Review by gkartalis — APPROVED** [review]
Looking great! One thing only: 

- Noticed that the Gemfile.lock still has `algoliasearch` as a dep 🤔 how do we get rid of that? 😅

I guess if we run `bundle update` it will also update a bunch of unrelated things, is there a ruby way of refreshing it to remove only `algoliasearch`?

**Comment by dblandin** [comment]
> >Noticed that the Gemfile.lock still has algoliasearch as a dep 🤔 how do we get rid of that? 😅

Nice catch and I noticed that too but it looks like [it's a dependency of cocoapods-core](https://github.com/artsy/eigen/blob/073882a55b4eb2a0b6de164ac3eb6aa78e5781b5/Gemfile.lock#L62-L65) so might not be able to drop it at this time.

**Review by gkartalis — COMMENTED** [review]
@dblandin actually there is another thing that we need to remove, there is this dep called `search-insights` that we introduced for tracking that we no longer need along with the `useSearchInsights` [hook](https://github.com/artsy/eigen/blob/476c3a280a8126056b1d093b51db3e4eba5dbeb2/src/app/utils/useSearchInsightsConfig.ts)

**Comment by dblandin** [comment]
@gkartalis Good catch! Removed in https://github.com/artsy/eigen/pull/9003/commits/7f2aeeba9af7c459c088bbaa60c85442566bbbca 👍🏼

**Review by anandaroop — APPROVED** [review]
Looks great 🧹 thanks for picking this up!

**Pull request merged**
