### PR TITLE
feature(DX): showing an indicator for webviews

### PR DESCRIPTION
**Pull request by pvinis**
The type of this PR is: **Feature**

This PR resolves []

### Description

Oftentimes I am not sure if a view is a webview or a native one. I thought I'll add a small indicator, so that it's always obvious what it is. It's just a floating red text that says "webview".

Screenshot 2021-11-30 at 13 51 16

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- webview indicator - pavlos

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (webview indicator - pavlos)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 72acbb839fd09bc264e35abbf78f0039b311735c
</p>

**Review by olerichter00 — CHANGES_REQUESTED** [review]
Great idea! 

Can we add a [dev toggle](https://github.com/artsy/eigen/blob/8a34e0e989a8013e34cc774503ec52df0da8f945/src/lib/store/config/features.ts#L228) for this?

**Comment by pvinis** [comment]
done :)

**Review by olerichter00 — APPROVED** [review]
🚀 🚀 🚀

**Review by MounirDhahri — APPROVED** [review]

**Review by brainbicycle — APPROVED** [review]
Nice :)

**Pull request merged**
