### PR TITLE
feat(CX-3273): Remove Phone validation in SWA form

### PR DESCRIPTION
**Pull request by lordkiz**
This PR resolves [CX-3273] 

### Description

- Removes the phone number validation in the SWA form

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [x] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Remove Phone validation in SWA form - kizito

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-3273]: https://artsyproduct.atlassian.net/browse/CX-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pvinis** [comment]
wait, does this screenshot say "kizito"? 😝😝

**Comment by pvinis** [comment]
but on a serious note, so we have a ticket to fix this in the right way? or are we disabling this forever?

**Comment by lordkiz** [comment]
> wait, does this screenshot say "kizito"? 😝😝

😂😂😂😂

**Comment by lordkiz** [comment]
> but on a serious note, so we have a ticket to fix this in the right way? or are we disabling this forever?

@pvinis Yeah, the Consignment team has indicated that it is not useful for them at this time or until the fix is ready.

**Comment by pvinis** [comment]
right. what im asking is if there is a ticket to wait on. good that we disable it, but lets have a ticket to fix this, and it can be prioritized for whenever/never.

**Review by MrSltun — APPROVED** [review]
LGTM! 💫

**Pull request merged**
