### PR TITLE
fix(APPL-565): Fix external url issue in Android webview

### PR DESCRIPTION
**Pull request by MrSltun**
This PR resolves [APPL-565] 

### Description
This PR fixes the issue in Android when tapping an external URL inside the webview
Where the user gets redirected to the browser, but the webview goes to a blank page

### Videos
| Before | After |
|---|---|
| <video src="https://github.com/artsy/eigen/assets/20655703/a9310489-c1ac-4221-b945-c7c17cfd6577" /> | <video src="https://github.com/artsy/eigen/assets/20655703/c6c9f359-db9a-4b8f-a037-91cb68b1345c" /> |

### PR Checklist

- [X] I have tested my changes on **iOS** and **Android**.
- [X] I hid my changes behind a **[feature flag]**, or they don't need one.
- [X] I have included **screenshots** or **videos**, or I have not changed the UI.
- [X] I have added **tests**, or my changes don't require any.
- [X] I added an **[app state migration]**, or my changes do not require one.
- [X] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [X] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

- Fix the issue with the webview having a blank page after tapping an external URL - mrsltun

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[APPL-565]: https://artsyproduct.atlassian.net/browse/APPL-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Android user-facing changes (Fix the issue with the webview having a blank page after tapping an external URL - mrsltun)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against aa8e1c8098bbbde8f7846b8f477643ac0887c670
</p>

**Review by brainbicycle — APPROVED** [review]
nice! this looks good, I wonder if we should also maybe add help.artsy.net to our handled routes so it stays in the webview rather than opening the browser?

**Review by gkartalis — APPROVED** [review]
👏 Thanks for fixing it, also agree with @brainbicycle

**Comment by MrSltun** [comment]
@gkartalis @brainbicycle I like the idea too, but it looks a bit off with the artsy logo at the top
image

I'm not sure if we can remove that like we do in Force

**Review by MounirDhahri — COMMENTED** [review]
Glad to see this working well. I wonder if you tried this solution from the community just for Android - many reported good results about it and I feel like it's worth trying out as well
```typescript
      onContentProcessDidTerminate={() => webViewRef.current.reload()}
```

**Comment by brainbicycle** [comment]
> @gkartalis @brainbicycle I like the idea too, but it looks a bit off with the artsy logo at the top image
> 
> I'm not sure if we can remove that like we do in Force

we can do separately, thanks for looking into!

**Pull request merged**
