### PR TITLE
Revert "fix: hot reload when app is run using yarn start"

### PR DESCRIPTION
**Pull request by MounirDhahri**
Reverts artsy/eigen#8697

### CODE REVIEW

**Comment by MounirDhahri** [comment]
sorry I reverted this before going on holidays quickly. raised an error in the main PR that was happening to all users and wanted to revert it while investigating the issue. Thanks for fixing it

**Comment by MounirDhahri** [comment]
Done - just added some description 🙏

**Comment by MounirDhahri** [comment]
Something seems to be broken when it comes to the query map generation 

https://github.com/artsy/eigen/assets/11945712/c26d08b3-060a-4557-8dc5-e82554d91c8a

**Comment by dimatretyak** [comment]
@MounirDhahri thank you for checking!

**Comment by damassi** [comment]
Once we re-add query files to git + queryMap -- https://github.com/artsy/eigen/blob/28ddd4dbc9e474bc7b59c8529c8fbda4a5e18963/.gitignore#L86 -- this should be fixed.

**Pull request merged**
