### PR TITLE
@alloy => Simplifying the ARShowFeedVC

### PR DESCRIPTION
**Pull request by orta**
This aims to clean-room re-implement the ARShowFeedVC, by switching out a lot of subclassed behavior into simpler more declarative classes via composition. 

It's not finished yet, but is open to PRs :+1:

### CODE REVIEW

**Comment by orta** [comment]
This is now feature complete, I forgot that I still have to unbreak CI :-/

**Comment by orta** [comment]
OK this now greens locally. 

This replaces some of the oldest code in the app, which doesn't have tests at all.

**Comment by alloy** [comment]
Amazecraze. Will review Monday morning!

**Comment by orta** [comment]
I am in no rush :+1:

**Comment by alloy** [comment]
I see from the changed files that it’s missing a changelog btw.

**Comment by orta** [comment]
lets just call this the orta release

**Comment by alloy** [comment]
This patch is really hard to review well, as the largest part of it is due to renaming symbols+files. In the future, renaming should be done in a separate commit.

Can you maybe point out the parts of the patch relevant to fixing the crashes?

**Comment by orta** [comment]
It's not a rename, it's a from scratch re-write with the same features,

**Comment by alloy** [comment]
> there isn't really anything not-relevant to the crashes

lol, ok

**Comment by alloy** [comment]
Rebased, merging.

**Pull request merged**
