### PR TITLE
fix(ONYX-1383): some artwork rail images get mangled after horizontal scrolling

### PR DESCRIPTION
**Pull request by dariakoko**
This PR resolves [ONYX-1383] 

### Description

Use flatList instead of FlashList on artwork rails

Follow-up on https://github.com/artsy/eigen/pull/11142: The max and min width for the artwork rail card were missing. Adding these constraints resolved the issue where the metadata was stretched to its full width. More details: https://artsy.slack.com/archives/C02BAQ5K7/p1732116471982649

Summary after the bug investigation: https://artsy.slack.com/archives/C02BAQ5K7/p1732102644251849

Screenshots confirming that the layout of the artwork rail card is not broken when using FlatList

| Android FF is off | Android FF is on | iOS FF is off | iOS FF is on |
| --- | --- | --- | --- |
| Screenshot_1732712502 | Screenshot_1732712559 | image | image |

https://github.com/user-attachments/assets/f2380738-9121-4ceb-9f6e-481c42a2c033

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- some artwork rail images get mangled after horizontal scrolling (use flatList instead of FlashList on artwork rails)

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-1383]: https://artsyproduct.atlassian.net/browse/ONYX-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — COMMENTED** [review]
Was setting the height and width not enough to fix things inside `PrefetchFlashList`? Can we avoid migrating the `PrefetchFlatList`

**Review by gkartalis — APPROVED** [review]
Nice :)

**Comment by gkartalis** [comment]
@MounirDhahri we had to migrate to `flatlist` instead of `flashlist` due to the bug in android stated [here](https://artsyproduct.atlassian.net/browse/ONYX-1383)

another issue that using flatlist over flashlist is fixed with this PR is that the flatlist draws the elements way faster (in android) vs flashlist for some reason.

**Comment by MounirDhahri** [comment]
thanks for explaing

**Review by MounirDhahri — APPROVED** [review]

**Review by anandaroop — APPROVED** [review]
🙏🏽 🙏🏽

**Comment by MounirDhahri** [comment]
It looks like this fix made the home view pretty slow on iOS. navigating from a screen to a screen started to take 300-500ms instead of 70-100ms. That makes the experience pretty slow. 

Since we know this change fixes issues on Android, I will keep it for Android and use FlashList again on iOS.

Next week I will receive an android testing device and will be able to dive deeper on Android

**Pull request merged**
