### PR TITLE
fix(build): update react native to fix flipper issues

### PR DESCRIPTION
**Pull request by brainbicycle**
This PR resolves [PHIRE-732] 

### Description

Updates react native to patch version that fixes build issues on Xcode 15.3
https://github.com/facebook/react-native/releases/tag/v0.72.12

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- update react native to fix Xcode 15.3 build issues - Brian 

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[PHIRE-732]: https://artsyproduct.atlassian.net/browse/PHIRE-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (update react native to fix Xcode 15.3 build issues - Brian)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6eba09b0d4d5571090bc1f56c4db3eb361a21665
</p>

**Comment by damassi** [comment]
Do we need to follow up on Folio here as well?

**Comment by brainbicycle** [comment]
yes we do :) : https://artsyproduct.atlassian.net/browse/PHIRE-733

**Comment by brainbicycle** [comment]
gonna merge, tested that it is building on iOS and Android and think pretty low risk so would like to keep more devs from running into this but let me know if anything needs updates

**Review by MrSltun — APPROVED** [review]

**Pull request merged**
