### PR TITLE
[Live] Working right jump to current lot

### PR DESCRIPTION
**Pull request by orta**
WIP on Handle transitioning between lots automatically.

I think a good experience is to note that a new lot is open, see if you're the one behind. Wait a full second, then transition. Jumping instantly felt off, you never got to see the results etc. Left as WIP so ideally I can work with @ashfurrow on getting the animations right tomorrow. Keeping the collection view in sync is complex.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Animations are definitely complex. I'm thinking it might make sense to either not do animations or do a window-wide layer-based animation, depending on how much other things we need to do tomorrow.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
        
            1 Error
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">There were <a href="https://eigen-ci.s3.amazonaws.com/2880/index.html">snapshot errors</a></td>
    </tr>
    
    
  </tbody>
</table>
  

  
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
        
            2 Warnings
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">PR is classed as Work in Progress</td>
    </tr>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
    
    
  </tbody>
</table>
  

  



Time | Class | Function |
| --- | ----- | ----- |256.8ms | [AuctionViewController.swift](/artsy/eigen/tree/orta-jump_to_lot/Artsy/View_Controllers/Auction/AuctionViewController.swift#L181) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
188.4ms | [SwiftyJSON.swift](/artsy/eigen/tree/orta-jump_to_lot/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
163.1ms | [WebSocket.swift](/artsy/eigen/tree/orta-jump_to_lot/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
73.4ms | [Observable.swift](/artsy/eigen/tree/orta-jump_to_lot/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
72.4ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/orta-jump_to_lot/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
70.6ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/orta-jump_to_lot/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, sideMargin: String)
65.3ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/orta-jump_to_lot/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L47) | @objc override func viewDidLoad()
64.4ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-jump_to_lot/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
62.5ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-jump_to_lot/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
60.8ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/orta-jump_to_lot/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView




<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
aside note: those snapshots change because it hits index 0, and index 1 is the currently lot, so it migrates over

**Comment by orta** [comment]
It's also worth the discussion about whether we want to start in the current index, think the web does that

**Comment by ashfurrow** [comment]
I think starting at the current index makes a lot of sense.

**Comment by orta** [comment]
Done'd

**Pull request merged**
