### PR TITLE
Registration Status for Bidders

### PR DESCRIPTION
**Pull request by ashfurrow**
This is a WIP because I need to verify it works as expected, and the tests need updating. A surprising amount of work for something so minor. 

I moved away from using the `ArtsyAPISaleRegistrationStatus` enum, and instead rely on logic to determine the `ARAuctionState` option set. Then, our "reducer" `stateToBidButtonState()` maps the lot state and the `ARAuctionState` to an appropriate, exact `enum` case, so we don't have to spread the option set code all over the app.

For #1626.

### CODE REVIEW

**Comment by orta** [comment]
Cool, yeah, this makes sense to me

**Comment by ashfurrow** [comment]
Tests will now compile and complete without crashing, but there are ~50 or so that need to be fixed (changes in how we represent auth status, makes sense many are not right).

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
        
            1 Error
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG changes made</td>
    </tr>
    
    
  </tbody>
</table>
  

  
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
        
            3 Warnings
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">PR is classed as Work in Progress</td>
    </tr>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
    
    
  </tbody>
</table>
  

  



Time | Class | Function |
| --- | ----- | ----- |227.3ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-reg-status/Artsy/View_Controllers/Auction/AuctionViewController.swift#L181) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
177.4ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-reg-status/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
160.1ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-reg-status/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
71.9ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-reg-status/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
68.1ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-reg-status/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, sideMargin: String)
65.9ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-reg-status/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
59.7ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-reg-status/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
57.9ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-reg-status/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
56.0ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/ashfurrow-reg-status/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView




<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
Updated a few snapshots because getting the tests to work with the older data was difficult. I can try again tomorrow if you want to minimize reference image changes.

**Comment by orta** [comment]
Ran locally, merging.

screen shot 2016-06-10 at 9 43 24 am

**Pull request merged**
