### PR TITLE
feat: add auction lots history to Artist Insights Tab

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **Feature**

This PR resolves [CX-737]

### Description
- Add list of auction lots history to artist insights
Screen_Recording_2020-12-08_at_20 44 05

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

[CX-434]: https://artsyproduct.atlassian.net/browse/CX-434
[CX-737]: https://artsyproduct.atlassian.net/browse/CX-737

### CODE REVIEW

**Comment by pvinis** [comment]
Thanks for taking this over @MounirDhahri!
I have added a couple last things, and I think we are all good, if you agree. (both working on this and both kinda reviewing 😛, nice!)

- Removed the `withBlackUnderlayColor`,
  to keep it consistent with elsewhere in the app where we override `underlayColor`. Kinda useful to have a prop for that, but I'd prefer if we add it everywhere else that `black5` is used in a `Touchable`. We could do this as a separate thing if you really want that prop. Also it might be interesting, if we add it, to name it something "dark mode friendly", like `useInverseUnderlayColor` or something 🤔. Anyway, maybe something for a KS or a pairing session.
- Replaced all `•` with `bullet` from `palette`.
  I saw a test was failing and you reverted it. I reverted it back and it seems all good now. I think I missed some spaces around 🙈.
- Completed the logic for the price text,
  and added some tests for it. Based on https://artsyproduct.atlassian.net/browse/CX-737?focusedCommentId=33276.
- Added myself in the changelog 😅

I'm good to merge this on green. If you are too, let me know and we merge!

**Comment by pvinis** [comment]
Solving the conflicts now.

**Comment by MounirDhahri** [comment]
Thanks for the changes 🎉 and sorry for forgetting to include you in the changelog

**Comment by pvinis** [comment]
All done 🤜🤛! #squashongreen

**Pull request merged**
