### PR TITLE
Updates registration button when status changes.

### LINKED ISSUE #1288: registration state does not update after completing registration in martsy
in an ongoing auction when i tap the register button i get sent to martsy, have a successful registration, but when I get kicked back to eigen on the page I don't see the approved to bid, I still see the registration button.

On an auction that hasn't opened yet, when I tap register button (and am already registered) I get to martsy, see a spinner, come back to eigen. I again, have successfully registered however again, I don't get the updated approved to bid.

### PR DESCRIPTION
**Pull request by ashfurrow**
As @alloy suggested, we weren't listening for this NSNotification anywhere. 

I want to confirm my understanding that, in current versions of iOS, we don't need to explicitly unregister ourselves from NSNotificationCenter things, right? Otherwise I'll need to add that to `deinit`.

Fixes #1288.

### CODE REVIEW

**Comment by alloy** [comment]
> I want to confirm my understanding that, in current versions of iOS, we don't need to explicitly unregister ourselves from NSNotificationCenter things, right? Otherwise I'll need to add that to `deinit`.

Still needed for backwards compatibility with iOS 8.

**Comment by alloy** [comment]
I’m not sure I fully understand this, is the issue that @katarinabatina reported with native auction views? If so, why would it have needed fixing asap, as those native auction views are not yet enabled in the app store release?

**Comment by orta** [comment]
I think the idea is to change that flag this week

**Comment by ashfurrow** [comment]
OK, added the unregistration, and a changelog entry, and fixed the tests in the original commit.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">1 Warning</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td><h4>Found unstubbbed networking requests</h4>

<ul>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
</ul>
</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
CI has failed a few times now, but have now succeeded :shrug:

**Comment by alloy** [comment]
I wouldn’t want it any other way! :+1:

**Pull request merged**
