### PR TITLE
fix: attempt at solving undefined lotCount

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR resolves [https://www.notion.so/artsy/Auction-lots-for-you-shows-undefined-price-10ecab0764a080d2a834dfb409fbfb9a?pvs=4] 

### Description
This PR comes as an attempt at solving `undefined` lot count. I don't know yet why this could happen but this seems to solve it for me.

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [X] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- attempt at solving undefined lot count - mounir

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (attempt at solving undefined lot count - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e9e778057235e48b17472b7a8ce7237d972cccb7
</p>

**Comment by MrSltun** [comment]
:ceiling-cat: I think the issue is not related to the lot watcher count, but rather to the auction price, and I know why it's breaking
It's due to some data not being fetched to be used by [`saleMessageOrBidInfo`](https://github.com/artsy/eigen/blob/main/src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx#L86) in `ArtworkRailCardMeta`, I already did the fix locally, can I push the changes on this PR?

**Comment by anandaroop** [comment]
Thanks @MrSltun, I'd say go for it since Mounir is OOO for a week 👍🏽

**Comment by MrSltun** [comment]
### Screenshots for the fix

| | Before | After |
|---|---|---|
| Android | image | image |
| iOS | image | image |

**Review by MrSltun — APPROVED** [review]

**Pull request merged**
