### PR TITLE
Make danger look for un-stubbed network requests in the build log #trivial

### PR DESCRIPTION
**Pull request by orta**
Ideally we should see a warning here soon.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">1 Warning</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td><h4>Found unstubbbed networking requests</h4>

<ul>
<li>ARArtworkViewControllerBuyButtonSpec in test<em>buy</em>button_<em>posts</em>order<em>if</em>artwork<em>has</em>no<em>edition</em>sets</li>
<li>ARCreateAccountViewControllerSpec in test<em>warning</em>view_<em>displays</em>a_message</li>
<li>ARCreateAccountViewControllerSpec in test<em>warning</em>view_<em>displays</em>a_message</li>
<li>AREmbeddedModelPreviewViewControllerSpec in test<em>iPhone</em>peek_<em>shows</em>favorite<em>and</em>follow<em>buttons</em>for<em>logged</em>in_user</li>
<li>AREmbeddedModelPreviewViewControllerSpec in test<em>iPhone</em>peek_<em>shows</em>favorite<em>and</em>follow<em>buttons</em>for<em>logged</em>in_user</li>
<li>AREmbeddedModelPreviewViewControllerSpec in test<em>iPhone</em>peek_<em>passes</em>artwork<em>to</em>share_controller</li>
<li>ARFairViewControllerSpec in test<em>creates</em>an_NSUserActivity</li>
<li>ARGeneViewControllerSpec in test<em>creates</em>an_NSUserActivity</li>
<li>ARGeneViewControllerSpec in test<em>creates</em>an_NSUserActivity</li>
<li>ARTopMenuViewControllerSpec in test<em>navigation</em><em>favorites</em><em>logged</em>in<strong>tab_behavior</strong>already<em>selected</em><em>pops</em>to_root</li>
</ul>
</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/KrauseFx/danger/">danger</a>
</p>

**Comment by alloy** [comment]
Nice :+1:

**Comment by orta** [comment]
OK, cool, this is good. Now everyone gets spammed until someone fixes them ;)

**Comment by esttorhe** [comment]
This is class!!
Kudos guys; I think I'll take the risk and will add `danger` to our own repo

**Comment by orta** [comment]
There's still a bunch of rough edges, but would be interested in seeing how integration with the little docs available works out :+1:

**Comment by ashfurrow** [comment]
:tada:

**Pull request merged**
