### PR TITLE
chore: Use notification headline field as title and better errors

### PR DESCRIPTION
**Pull request by olerichter00**
This PR resolves [ONYX-540] 

### Description

This PR does two things: 

- Updating the Notification screen to use the new `headline` field for the title.
- Updating the error messages.

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Update Notification screen title and error messages (behind ff) - ole

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-540]: https://artsyproduct.atlassian.net/browse/ONYX-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]
LGTM! 
What's the difference between headline and title?

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Update Notification screen title and error messages (behind ff) - ole)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against faba25a7a9d4fe3979ef2ad850356d3243a8b152
</p>

**Comment by olerichter00** [comment]
> What's the difference between headline and title?

`title` is the old title from the current design ([Metaphysics implementation](https://github.com/artsy/metaphysics/blob/afd2ee7fc708abfbc430cbb20c34f4cf5147b08e/src/schema/v2/notifications/index.ts#L45)) and `headline` is the title used in the new design ([Gravity implementation](https://github.com/artsy/gravity/blob/546ed601245bda64535802073c683d44e8202e97/app/models/activity_feed/saved_search_hit_activity.rb#L23)). Unfortunately, we couldn't reuse `title` because it's still in use and needed to add a field for the new title (which is `headline`).

**Comment by MounirDhahri** [comment]
Thanks for explaining. Clear, feel free to merge on 🟢

**Pull request merged**
