### PR TITLE
[My Collection] Update to use new FancyModal and select

### PR DESCRIPTION
**Pull request by damassi**
This swaps out the native modal views with the new FancyModal from https://github.com/artsy/eigen/pull/3484, and also swaps in the new select. Also swapped out the "index" marketing view for the list view. 

Note that there are some issues with modal layering that have been raised in #frontend-ios -- namely, when the modal is open and the user clicks the new select an identical style modal is displayed; but when an item is selected it dismisses both. We need to find a way to layer these things. 

modalflow

#trivial 
#skip_new_tests

### CODE REVIEW

**Comment by damassi** [comment]
@ds300 - thoughts on that warning that appears in the screen cap above?

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Missing Test Files:

- `src/lib/Scenes/Consignments/v2/Components/__tests__/Modal-tests.tsx`
- `src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/__tests__/MyCollectionArtworkListItem-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "#skip_new_tests".</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by ds300** [comment]
@damassi ah sorry about that. I pushed a fixup commit to this branch.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Missing Test Files:

- `src/lib/Scenes/Consignments/v2/Components/__tests__/Modal-tests.tsx`
- `src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/__tests__/MyCollectionArtworkListItem-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "#skip_new_tests".</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
