### PR TITLE
fix: blank screen on career highlights

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR resolves an issue where the career highlights cards are broken on Android

**Before**

https://user-images.githubusercontent.com/11945712/216008943-db717caa-52cd-4383-b6a6-b29edee39b29.mp4

**After**

https://user-images.githubusercontent.com/11945712/216009542-16a39cbe-85b9-454b-a911-06209f39194c.mov

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

- Fix career highlights cards modal - mounir

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by dariakoko — APPROVED** [review]
⭐ ⭐ ⭐  thank you!

**Comment by olerichter00** [comment]
Just out of curiosity, what was the actual issue and how did you solve it?

**Comment by MounirDhahri** [comment]
Sure - we were having `Suspense` inside the component that was calling `useLazyLoadQuery` instead of the component wrapping it. This "worked" for some reason in the previous versions then it suddenly broke. We think it broke because of either a dependabot update or something related to remote android build dependencies.

**Comment by olerichter00** [comment]
Thanks a lot for the explanation 🙏

**Pull request merged**
