### PR TITLE
refactor: hidding bottom tabs approach 2

### PR DESCRIPTION
**Pull request by dimatretyak**
This PR resolves [] 

### Description
Initial PR: artsy/eigen#7760
Improved version: artsy/eigen#7823 (fixed problems that were found in [the QA session](https://www.notion.so/artsy/Navigation-bar-gets-a-bit-glitchy-coming-back-from-Confirm-Bid-modal-ab10d261b58744a5ac1b5b88eb4f9bf2))

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [x] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- hidding bottom tabs (approach 2) - dimatretyak

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by dimatretyak** [comment]
**question**: do you think it's better to use this approach or [the current one](https://github.com/artsy/eigen/pull/7823)?

**Comment by dblandin** [comment]
If we can get rid of the currently implemented access of the navigation stack from the screen's `useEffect` hook — then I think we should go for it. Less risky and more performant 👍🏼

**Comment by dimatretyak** [comment]
you can test these changes:
* iOS - 2022.12.8.20
* Android - **build 686**

**Review by dblandin — APPROVED** [review]
Just tested the beta version and looks good to me 👍🏼

**Review by gkartalis — APPROVED** [review]

**Comment by MounirDhahri** [comment]
Nice!

**Review by MounirDhahri — COMMENTED** [review]
much better UX

**Pull request merged**
