### PR TITLE
fix: increase default storage capacity of async storage on Android

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [PHIRE-106] 

### Description

This PR resolves the following sentry issues:

- [First (after hermes)](https://artsynet.sentry.io/issues/4225202213/?environment=production&project=5867225&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=0) 
- [Second (pre-hermes)](https://artsynet.sentry.io/issues/3570220768/?environment=production&project=5867225&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=8)

Both are basically the same issue: `database or disk is full (code 13 SQLITE_FULL[13])`

The reason for that is that [@react-native-async-storage/async-storage](https://react-native-async-storage.github.io/async-storage/docs/advanced/db_size/#increase-limit) lib has a different implementation between the two platforms.

On iOS devices, the AsyncStorage is not limited programmatically while on Android it is defaulting to 6MB.

Changed that to be 10MB as sugested [here](https://react-native-async-storage.github.io/async-storage/docs/advanced/db_size/#increase-limit) 

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

- increase default storage capacity of async storage on Android - gkartalis

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[PHIRE-106]: https://artsyproduct.atlassian.net/browse/PHIRE-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MrSltun — APPROVED** [review]

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Android user-facing changes (increase default storage capacity of async storage on Android - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e9ce2ef47bfce6d7c5a8097a6157030b65d4d21e
</p>

**Review by MounirDhahri — APPROVED** [review]
Although I think increasing the `AsyncStorage` size will help reduce these bugs, I don't see it fixing the majority of them. 
I did some investigation recently about why are we reaching the limit often here and I believe it's due to us allowing storing local images in `AsyncStorage` and quickly filling it or reaching maximum quickly with big size images. What I believe will get this error to go away would be to not store images in `AsyncStorage` and store them in a different way (a local db for example) as we solved the issue in Force.

This is a link to a risk I outlined in the [RFC](https://www.notion.so/artsy/Handling-long-image-processing-times-inside-Force-Use-local-images-e926e1930958403ba54ced0a36dab62f?pvs=4#eff288987a274e23ad8c49c323adca67) I wrote to handle the same issue on Force.

**Comment by gkartalis** [comment]
Good points @MounirDhahri didn't know about this RFC.

I just added a card to follow up on your point and investigate it further on the practice board [here](https://www.notion.so/artsy/AsyncStorage-Images-in-eigen-investigation-92455fe0353849deab69876b070d89bb?pvs=4)


Feel free to add / edit with more info! 

Will merge this to limit the issue but agree that we should tackle the issue to its root 🪚🌴

**Comment by MounirDhahri** [comment]
Perfect - thanks @gkartalis

**Pull request merged**
