### PR TITLE
@orta -> always use desktop web urls when sharing

### PR DESCRIPTION
**Pull request by 1aurabrown**
fixes https://github.com/artsy/eigen/issues/161

I guess another solution would be to add meta tags on m.artsy.net, but personally I think it's weird and ugly when people tweet/post mobile links. If somebody happens to visit a force link on a phone as a result of a share, they'll just get redirected to mobile anyway.

### CODE REVIEW

**Comment by orta** [comment]
Perfect, thank you @1aurabrown 

can you please add a changelog to the BETA_CHANGELOG

**Comment by orta** [comment]
Tests look much nicer too :dancers:

**Comment by orta** [comment]
( mergable when CHANGELOG'd )

**Comment by 1aurabrown** [comment]
@orta i just added a bunch of things to the changelog and included it in https://github.com/artsy/eigen/pull/228. ok?

**Comment by orta** [comment]
yep. Merging.

**Pull request merged**
