### PR TITLE
@orta => Update test snapshots of related artworks.

### PR DESCRIPTION
**Pull request by alloy**
Adds updated snapshots that I forgot to include in #277.

### CODE REVIEW

**Comment by dblock** [comment]
This GIF!

**Comment by orta** [comment]
:D

**Comment by alloy** [comment]
lol

I’m doing ok now!

**Comment by 1aurabrown** [comment]
Hey, I noticed this failure when running tests locall:
```
/Users/laura/artsy/eigen/Artsy Tests/ARArtworkRelatedArtworksViewTests.m:191: error: -[ARArtworkRelatedArtworksViewSpec test_concerning_an_artwork_at_a_show__adds_a_section_with_other_works_in_the_same_show] : expected: (Burnt umber and ultramarine), got: ()
Test Case '-[ARArtworkRelatedArtworksViewSpec test_concerning_an_artwork_at_a_show__adds_a_section_with_other_works_in_the_same_show]' failed (0.024 seconds).
```

**Comment by alloy** [comment]
@1aurabrown Oh, weird, haven’t seen that. Can you reproduce it?

**Comment by 1aurabrown** [comment]
Yeah happens every time for meSent using CloudMagicOn Mon, Mar 23, 2015 at 13:51,  artsy/eigen <reply@reply.github.com> wrote:             @1aurabrown Oh, weird, haven’t seen that. Can you reproduce it?

**Pull request merged**
