### PR TITLE
@alloy => Ensure that the keychain always works through access groups

### PR DESCRIPTION
**Pull request by orta**
My Watch App introduced some bugs that are only apparent when using the app store build on a device. Sigh. 

So I've gone and re-created our eigen certs, and ensured that we have consistent access groups between all the apps. In started to work on the tests I ended up in the bushes a bit and created https://github.com/artsy/eigen/issues/533 as I realized that this is outside of the current scope. 

fixes https://github.com/artsy/eigen/issues/530

### CODE REVIEW

**Comment by alloy** [comment]
Ace, thanks for the quick fix :+1:

**Comment by alloy** [comment]
The Xcode project should **not** use the ‘iPhone Developer’ code signing identity _anywhere_, or else testing things like push notifications won’t work, so please remove those codesign identity changes and the provisioning profile changes, they should all be properly set at the project level.

**Comment by ashfurrow** [comment]
Doesn't the project need the developer profile for testing on device?

**Comment by alloy** [comment]
@ashfurrow The ‘developer’ profile is a wildcard for a dev to just build any app, but the profile does not have provisions for e.g. Push Notifications, so if you also want to be able to test that you need a special profile. This is what we have the “iOSTeam Provisioning Profile: net.artsy.artsy.dev” profile on the enterprise account for, so as long as you ensure your device is registered on the enterprise account and listed in that profile, it will work.

https://artsy.slack.com/archives/mobile/p1434120731002015

**Comment by ashfurrow** [comment]
Cool, thanks for clarifying. Want to add that to artsy/potential mobile onboarding?

**Pull request merged**
