### PR TITLE
Updates submodule commit

### PR DESCRIPTION
**Pull request by ashfurrow**
I _think_ this will fix CI.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Oh weird, https://circleci.com/gh/artsy/eigen/2843 is working without this. Hmm.

**Comment by orta** [comment]
It'll be build caching

**Comment by ashfurrow** [comment]
Mmmm right.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
        
            1 Warning
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
    
    
  </tbody>
</table>
  

  



Time | Class | Function |
| --- | ----- | ----- |251.0ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-pods-fix/Artsy/View_Controllers/Auction/AuctionViewController.swift#L181) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
193.9ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-pods-fix/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
170.6ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-pods-fix/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
85.8ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-pods-fix/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, sideMargin: String)
77.2ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-pods-fix/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
73.1ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-pods-fix/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
65.9ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-pods-fix/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
63.9ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-pods-fix/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
59.3ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/ashfurrow-pods-fix/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView




<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
🍏

**Pull request merged**
