### PR TITLE
build(deps): bump react-native from 0.69.10 to 0.69.12

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [] 

### Description

Bumps react native 69 to [latest version](https://github.com/facebook/react-native/releases/tag/v0.69.12) because they fixed the Oppo and 1Plus device crashes from `runAnimationStep`.

https://github.com/facebook/react-native/issues/35766

Also makes XCode 15 work with eigen.

⚠️ Had to run `cd ios && bundle exec pod update hermes-engine --no-repo-update` due to this react native issue: https://github.com/facebook/react-native/issues/36945 to make CI pass (TLDR; podfile.lock wasnt updating hermes correctly on podfile.lock) and update `podfile.lock` file (resulted in the last commit diff)

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- bump react-native from 0.69.10 to 0.69.12 - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by MrSltun — APPROVED** [review]
🚀 🚀 🚀

**Comment by gkartalis** [comment]
Will prob merge on the next release to have two weeks time to see if any issues arise out of this

**Comment by MrSltun** [comment]
I just have a thought of adding the command to package.json, and removing it when we upgrade to 72 or above
Just in case we upgrade to a version that's lower than 72 to update hermes on `pod-install` 👀

**Comment by gkartalis** [comment]
> I just have a thought of adding the command to package.json, and removing it when we upgrade to 72 or above
Just in case we upgrade to a version that's lower than 72 to update hermes on pod-install 👀

What do you mean exactly? Doing it on which step?

**Comment by MrSltun** [comment]
> What do you mean exactly? Doing it on which step?

I was thinking either in `yarn pod-install` or inside `post-pod-install.rb` script, but maybe it won't be needed

**Comment by gkartalis** [comment]
@MrSltun Yeah, thought of something like that, but that will add exponentially more time every time that we need to run anything that includes this extra step which will only be needed to run on react-native upgrade prs. I would say lets leave this  out for that reason unless you can think of another workaround on this?

**Comment by MrSltun** [comment]
@gkartalis I'm with leaving it out! It's quite an edge case :)

**Review by brainbicycle — APPROVED** [review]
🙌

**Pull request merged**
