### PR TITLE
chore: upgrade update repo to 0.5.0

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **chore**

This PR is a follow-up from https://github.com/artsy/eigen/pull/5887

### Description
- Upgrade update repo to 0.5.0

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Upgrade update repo to 0.5.0 - mounir

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Upgrade update repo to 0.5.0 - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8f5ada1906b43bc5eb6565d5512d319fc45ecf29
</p>

**Comment by MounirDhahri** [comment]
the build is failing with code 137 (memory) I will try to rerun and hope it gets solved
Screenshot 2021-12-14 at 11 12 23

**Review by olerichter00 — DISMISSED** [review]
Looks good to me! Feel free to merge whenever the Android build is passing 🚀

**Comment by MounirDhahri** [comment]
Finally 😄

**Comment by MounirDhahri** [comment]
After changes

Screenshot 2021-12-14 at 12 31 51

**Pull request merged**
