### PR TITLE
@alloy => Make changelogs use a union merge

### PR DESCRIPTION
**Pull request by orta**
For everyone else: https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/

and https://twitter.com/orta/status/619139230162362368

### CODE REVIEW

**Comment by alloy** [comment]
Can you add the beta changelog too?

**Comment by orta** [comment]
lols, irony, sure

**Comment by alloy** [comment]
lol

**Comment by orta** [comment]
oh wait, I thought you meant add a CHANGELOG note about this, turns out you really meant include the BETA_CHANGELOG.md file :dancers:

**Comment by orta** [comment]
Changed & `make fpush`'d

**Comment by alloy** [comment]
Hahaha, I had want to make that joke, but decided that there was really no point in having it in the changelog itself… :older_man:

**Pull request merged**
