### PR TITLE
fix(ActivityScreen): prompt not closing when submitting

### PR DESCRIPTION
**Pull request by araujobarret**
This PR resolves [APPL-1109] 

### Description

Fixes the wrong state change when dismissing the prompts.

https://github.com/user-attachments/assets/526173ec-2b19-4611-9120-fb0028b56fd1

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- fix: broken visibility state when dismissing prompts in the activity screen - araujobarret

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[APPL-1109]: https://artsyproduct.atlassian.net/browse/APPL-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (fix: broken visibility state when dismissing prompts in the activity screen - araujobarret)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b853a53bfbcfe01bfb815c5ead13ca4829382c45
</p>

**Review by gkartalis — APPROVED** [review]

**Review by MounirDhahri — COMMENTED** [review]
Code looks good to me. Thanks for the fix.

I have a UX questions, shouldn't the message get hidden after you add your profile details?

**Comment by araujobarret** [comment]
@MounirDhahri You'll never see these same items stacked, only in this case bc I triggered manually from Gravity.

Re disappearing, it's was a design choice, right now Force works like this too 😓

**Comment by MounirDhahri** [comment]
> Re disappearing, it's was a design choice, right now Force works like this too 😓

If possible, do you mind if you bring this up again with them because it feels weird to me. User driven experiences should be satisfying and they should be encouraging/rewarding to users. Here, there is none of that. An idea would be a to be show, "thanks for updating your profile! you can update details later in your profile", hide the bottom sheet, and then make the notification disappear. 

I would be really very interested in seeing how this would perform and how many times user will tap it after already filling details. do we have tracking available here?

**Pull request merged**
