### PR TITLE
Removes Hockey feedback mechanisms.

### PR DESCRIPTION
**Pull request by ashfurrow**
This removes the hockey feedback mechanism from the admin menu and the response to taking screenshots. It also removes the ability to record the app, which is now a part of iOS (but we can add that back in if you think, just let me know).

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_travis">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
The pod can be removed too

**Comment by ashfurrow** [comment]
Analytics still relies on Hockey, and the replay stuff was an Apple framework.

**Comment by orta** [comment]
Yep - but we don't do crash reporting with hockey anymore, so we can drop the pod entirely! :D

**Comment by ashfurrow** [comment]
Cool did that. Without the Hocket subspec, CocoaPods installed ReactiveObjC (which is just ReactiveCocoa, just renamed). I don't know why it did that, but it led to duplicate symbol warnings with both installed, so I moved Eigen to ReactiveObjC, too. No API changes required.

**Comment by orta** [comment]
Cool, yep 👍

**Pull request merged**
