### PR TITLE
Fixes mutation reference to include ecommerce prefix

### PR DESCRIPTION
**Pull request by ashfurrow**
Follow-up from #2685. Also adds a changelog entry for that PR.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hmm weird, I wonder why the tests failed _now_ but not on Orta's original PR?

**Comment by ashfurrow** [comment]
Oh I see, hmm. Our testing setup is a little brittle here. The Artwork view is next on the React Native rewrite list, so probably not worth it to invest into fixing it.

**Comment by orta** [comment]
weirrrrdddd

**Comment by orta** [comment]
could there be dummy data that needs the same change?

**Pull request merged**
