### PR TITLE
Add a check for `fit` in swift tests #trivial

### PR DESCRIPTION
**Pull request by orta**
See - https://github.com/artsy/eigen/pull/1370

Danger wasn't looking for a swift syntax WRT `fit` tests

### CODE REVIEW

**Comment by ashfurrow** [comment]
Neat!

**Comment by ashfurrow** [comment]
Rebuilding on CI.

**Comment by ashfurrow** [comment]
Trying again... I've seen the `bundler: command not found: danger` error before, intermittently, and rebuilding usually fixes it.

**Comment by alloy** [comment]
@ashfurrow Indeed, specifically rebuild without cache.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">1 Error</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:no_entry_sign:</td>
      <td>fit left in tests</td>
    </tr>
    
  </tbody>
</table>
  

  
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">2 Warnings</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td>Needs testing on a Phone if change is non-trivial</td>
    </tr>
        <tr>
      <td>:warning:</td>
      <td><h4>Found unstubbbed networking requests</h4>

<ul>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
</ul>
</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
```

~/d/i/a/eigen (mc-onboarding-splashscreen) ⏛  grep -r "fit(" Artsy_Tests/
Binary file Artsy_Tests//ReferenceImages/ARGeneViewControllerSpec/with long desciption as ipad@2x.png matches
```

hah

**Pull request merged**
