### PR TITLE
fix: frozen add artwork modal

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR resolves [CX-2638]

### Description
fix: frozen add artwork modal

https://user-images.githubusercontent.com/11945712/175006004-a7150de3-b239-470a-a335-a3b48d7ba145.mov

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- fix frozen add work modal inside my collection - mounir

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-2638]: https://artsyproduct.atlassian.net/browse/CX-2638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dariakoko** [comment]
Thanks, @MounirDhahri! Do you mind closing this PR? I'm already working on these changes in my branch

**Comment by dariakoko** [comment]
Alright, I'll remove my changes 👌

**Comment by MounirDhahri** [comment]
@dariakoko I need this for the release since it's launch blocking

**Comment by brainbicycle** [comment]
👀 we saw some freezes like this in the bidding modals? I wonder if it is related and could be fixed similarly? https://artsyproduct.atlassian.net/browse/CX-2157

**Comment by MounirDhahri** [comment]
I tried the flow inside CX-2157 again and I couldn't reproduce it, it could be that the race condition only occurs on older phones. Maybe I can update `dismissModal` to run only after the UI thread is done animating.

**Pull request merged**
