### PR TITLE
build: rename opaqueImageView component ff

### PR DESCRIPTION
**Pull request by gkartalis**
### Description

Rename opaqueImageView component feature flag to be released only in latest app version (8.1.0 +)

This PR resolves []

#### Acceptance Criteria

- make sure that the new image component (on staging it has a purple watermark NewImg) renders normally and no weird behavior is encountered. This covers many surfaces so exploratory testing might be suitable for this. Most of the artwork grids use the new image.

#### Setup Instructions

- go to admin menu and enable the feature flag Enable New Image Component.

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [x] I hid my changes behind a [feature flag].
- [x] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- **[NEEDS EXTERNAL QA]** rename opaqueImageView component ff - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by gkartalis** [comment]
will fill out the qa test cases / setup in a bit 🙈 in b2b meetings rn

**Review by MounirDhahri — APPROVED** [review]
Niice thanks

**Comment by gkartalis** [comment]
@MounirDhahri @brainbicycle is the QA ACs and setup instructions that I added enough for applause?

**Comment by MounirDhahri** [comment]
Yes, they're enough imo

**Pull request merged**
