### PR TITLE
Segment cleanup

### PR DESCRIPTION
**Pull request by alloy**
Waiting for this to be merged to perform the last cleanup https://github.com/orta/ARAnalytics/pull/232

### CODE REVIEW

**Comment by ashfurrow** [comment]
screen shot 2015-12-02 at 12 08 58 pm

Objective-C ಠ_ಠ

**Comment by alloy** [comment]
+1 +1 +1 +1

**Comment by alloy** [comment]
This is ready to be merged :+1:

**Comment by orta** [comment]
:+1:

**Pull request merged**
