### PR TITLE
refactor(palette): Migrate more internal palette components to @artsy/palette-mobile

### PR DESCRIPTION
**Pull request by damassi**
⚠️ Branched From:
- https://github.com/artsy/eigen/pull/8455

**Related**: 
- https://github.com/artsy/palette-mobile/pull/78 first

**Addresses**: 
- [MOPLAT-687]
- [MOPLAT-688]
- [MOPLAT-689]
- [MOPLAT-690]
- [MOPLAT-691]
- [MOPLAT-692]
- [MOPLAT-693]
- [MOPLAT-694]
- [MOPLAT-695]
- [MOPLAT-696]
- [MOPLAT-697]
- [MOPLAT-698]
- [MOPLAT-699]

### Description

This migrates a bunch of items out of the palette folder and into palette-mobile. 

cc @artsy/mobile-platform 

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[MOPLAT-687]: https://artsyproduct.atlassian.net/browse/MOPLAT-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-688]: https://artsyproduct.atlassian.net/browse/MOPLAT-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-689]: https://artsyproduct.atlassian.net/browse/MOPLAT-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-690]: https://artsyproduct.atlassian.net/browse/MOPLAT-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-691]: https://artsyproduct.atlassian.net/browse/MOPLAT-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-692]: https://artsyproduct.atlassian.net/browse/MOPLAT-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-693]: https://artsyproduct.atlassian.net/browse/MOPLAT-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-694]: https://artsyproduct.atlassian.net/browse/MOPLAT-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-695]: https://artsyproduct.atlassian.net/browse/MOPLAT-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-696]: https://artsyproduct.atlassian.net/browse/MOPLAT-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-697]: https://artsyproduct.atlassian.net/browse/MOPLAT-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-698]: https://artsyproduct.atlassian.net/browse/MOPLAT-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOPLAT-699]: https://artsyproduct.atlassian.net/browse/MOPLAT-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by gkartalis — APPROVED** [review]
🛳️

**Comment by gkartalis** [comment]
Whats the merging plan for those? 

I also opened https://github.com/artsy/eigen/pull/8472 out of https://github.com/artsy/eigen/pull/8455. 

Do you think merging them all to https://github.com/artsy/eigen/pull/8455 and triggering a beta to QA from there before merging would be a good idea?

Or should we directly merge to main one by one?

**Comment by damassi** [comment]
I like the idea of merging everything into #8455! From there we can have that PR / branch be like a secondary main to give it a quick run. 

I'm not _so_ worried about issues around QA as stuff will come up naturally (always happens with migrations like this), but merging everything into that branch means that if something goes very wrong we can revert that one PR instead of like 10 separate ones.

**Comment by damassi** [comment]
So any PRs I open today will point at that PR as well 👍

**Pull request merged**
