### PR TITLE
[Onboarding] Exclude certain artists and genes from search

### PR DESCRIPTION
**Pull request by mennenia**
...When you've already followed them.

Unfortunately Gravity hasn't added it for genes yet, so I'll see if I can do that later on, but eigen's code is already prepped for it!

### CODE REVIEW

**Comment by alloy** [comment]
> Unfortunately Gravity hasn't added it for genes yet, so I'll see if I can do that later on, but eigen's code is already prepped for it!

Oh really? Can you link the open ticket for that?

**Comment by alloy** [comment]
Boomdiggidy 💥

**Comment by mennenia** [comment]
@alloy:

I haven't made a specific ticket. I did originally request it in [this ticket](https://github.com/artsy/gravity/issues/10383), but it didn't seem to have been added in [the PR](https://github.com/artsy/gravity/pull/10396).

I was thinking, for it to be done for genes, do we just need to create [this](https://github.com/artsy/gravity/pull/10396/files#diff-8137369ed744eb751663983245254198) for the `genes_filtered_query.rb`?

**Comment by mennenia** [comment]
Sorry. I did make a local note of it here: #1838

**Comment by alloy** [comment]
> I did originally request it in [this ticket](https://github.com/artsy/gravity/issues/10383), but it didn't seem to have been added in [the PR](https://github.com/artsy/gravity/pull/10396).

Oh yeah, I only now notice it being in the title of that ticket.

> I was thinking, for it to be done for genes, do we just need to create [this](https://github.com/artsy/gravity/pull/10396/files#diff-8137369ed744eb751663983245254198) for the `genes_filtered_query.rb`?

Yeah probably, assuming that the code otherwise is similar.

**Pull request merged**
