### PR TITLE
feat: Add no results for filter message to My Collection

### PR DESCRIPTION
**Pull request by olerichter00**
The type of this PR is: **Feature**

This PR resolves [CX-2332]

### Description

Add no results for filter message to My Collection.

Simulator Screen Shot - iPhone 12 mini - 2022-02-07 at 17 15 46

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [x] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-Add "no results for filter" message to My Collection - ole

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[CX-2332]: https://artsyproduct.atlassian.net/browse/CX-2332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Add "no results for filter" message to My Collection - ole)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5fa13cdf034aa608a90c4df79326c6271c135ecf
</p>

**Review by nickskalkin — CHANGES_REQUESTED** [review]
lgtm 👍 One moment though: I would extract some tests from MyCollection.tests.tsx. There are tests checking what component to render (zerostate, scroll). I think this tests now belong to MyCollectionArtworks.tests.tsx

I click "Request changes" so you don't overlook my comment, but if you don't want to follow my suggestion, let me know and I will Approve

**Comment by olerichter00** [comment]
> lgtm 👍 One moment though: I would extract some tests from MyCollection.tests.tsx. There are tests checking what component to render (zerostate, scroll). I think this tests now belong to MyCollectionArtworks.tests.tsx

Good catch! I checked and I've decided to leave them in `MyCollection.tests.ts` to have them as an integration test for the whole screen.

**Comment by olerichter00** [comment]
#squashongreen

**Pull request merged**
