### PR TITLE
@1aurabrown => Get test suite to run on CircleCI

### PR DESCRIPTION
**Pull request by alloy**
Runs on iOS 8.3 https://circleci.com/gh/artsy/eigen/40

### CODE REVIEW

**Comment by alloy** [comment]
Oh wait, I need to first fix SecondCurtain.

**Comment by orta** [comment]
The README will want a circle badge instead.

**Comment by 1aurabrown** [comment]
OK. lmk when mergeable

**Comment by orta** [comment]
I changed the access for the S3 account again, they should be really locked down, please give a snapshots fail again

**Comment by marcomorain** [comment]
Awesome!

**Comment by marcomorain** [comment]
Can I make a suggestion for the `circle.yml`? If you follow the `xcodebuild` command from here you will get a better integration with our tools: https://circleci.com/docs/ios#build-commands

- Sending the output through `tee $CIRCLE_ARTIFACTS/xcode_raw.log` will save the raw xcode output to a file which is stored in the build artifacts with each build – this can really help with debugging build errors that `xcpretty` can mask, and it helps if the build output gets too long and Circle truncates it.
- If you add `--report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml` to the `xcpretty` invocation it will allow us to collect test result data and show a list of failing test. This will turn output like this:

screen shot 2015-05-12 at 19 14 20

Into something more like this (this second screen-shot is from a different project but the formatting will be the same):

screen shot 2015-05-12 at 19 15 35

- If you add `set -o pipefail &&` to the begining of your build command before `xcodebuild` it will stop errors in xcodebuild being swallowed by `xcpretty`: http://bclary.com/blog/2006/07/20/pipefail-testing-pipeline-exit-codes/

Let me know if you have any other questions, or email sayhi@circleci.com :sparkles:

**Comment by alloy** [comment]
@marcomorain Thanks for all those tips! I’ll be giving them a try :+1:

**Comment by alloy** [comment]
@orta Yup, still works :+1:

**Comment by alloy** [comment]
@marcomorain I think I got it all right, thanks again :+1:

**Comment by alloy** [comment]
@1aurabrown This should be mergable on green 🐎

**Comment by marcomorain** [comment]
- Raw log: https://circle-artifacts.com/gh/artsy/eigen/51/artifacts/0/tmp/circle-artifacts.M8yeJeK/xcode_raw.log :heavy_check_mark: 
- Test results: `Your build ran 737 tests in xcode with 0 failures.` :heavy_check_mark: 

:+1:

**Comment by 1aurabrown** [comment]
:tada:

**Pull request merged**
