### PR TITLE
[WIP] @ashfurrow => Update ARAnalytics and fix deprecation warnings.

### PR DESCRIPTION
**Pull request by alloy**
This pulls in the dev branch where I added support for screen views with properties: https://github.com/orta/ARAnalytics/tree/add-screen-properties

It should now be a matter of implementing the screens+events that are listed in the provided sheet https://github.com/artsy/eigen/issues/422#issuecomment-103416783

### CODE REVIEW

**Comment by alloy** [comment]
Once my dev branch is deemed ok, can you get that merged too?

**Comment by ashfurrow** [comment]
Yeah, you want to open a PR on ARAnalytics?

**Comment by alloy** [comment]
Will do :+1:

**Comment by alloy** [comment]
Done https://github.com/orta/ARAnalytics/pull/158

**Comment by ashfurrow** [comment]
Gonna merge this into `segment`, then work on it from there.

**Pull request merged**
