### PR TITLE
Remove unneeded decimals from prices

### PR DESCRIPTION
**Pull request by alloy**
This fixes the decimal part of https://github.com/artsy/collector-experience/issues/786. It’s a crude fix, but figuring out this iOS bug is proving more than 5 minutes work.

### CODE REVIEW

**Comment by alloy** [comment]
There’s more places where we don’t display `LOT N`, so I left that out for now as well.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_travis">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
OK, got it green, waiting on my build to compile so I can verify if my per-currency formatter fixes #2514

**Comment by orta** [comment]
Ah damn, this needs merged.

**Pull request merged**
