### PR TITLE
chore: define separate feature flag for controlling saved search on A…

### PR DESCRIPTION
**Pull request by dblandin**
The type of this PR is: **Bugfix**

Define separate feature flag for controlling saved search on Android.

Choose the appropriate feature flag key depending on the active react-native platform.

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

#### Dev changes

- Define separate feature flag for controlling saved search on Android

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Define separate feature flag for controlling saved search on Android)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7bd3f1ee98be09b37a6e4f86020e16bf2bd8e2ee
</p>

**Review by anandaroop — APPROVED** [review]
LGTM, thanks for the quick fix!

**Comment by dimatretyak** [comment]
Should [the tests](https://github.com/artsy/eigen/blob/master/src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx#L63) be updated under the new flags, or will only iOS check by default?

**Comment by anandaroop** [comment]
CI fail seems to indicate that Echo needs the corresponding update first. I can add that right after this line, yes? https://github.com/artsy/echo/blob/0084783fe1d5db6de7704e5f5c8e79cc2c94da0c/Echo.json5#L35

**Comment by anandaroop** [comment]
We just merged the required Echo PR (https://github.com/artsy/echo/pull/108) so I'll rebuild on this one shortly…

**Review by brainbicycle — APPROVED** [review]

**Pull request merged**
