### PR TITLE
fix(my collection): set correct keyboard types #trivial

### PR DESCRIPTION
**Pull request by admbtlr**
The type of this PR is: Bugfix

This PR resolves [CX-786]

### Description

This specifies keyboard types for the Add Artwork form:

- Dimensions (height/width/depth): numeric with decimal
- Edition (number/size): numeric
- Price paid: numeric with decimal
- Date: numeric with punctuation

The Date field is not ideal - I wonder whether we should change the label to "Year" and then have a straight numeric keyboard @joanna20 ? Or just leave it as "Date" but use a numeric keyboard?

image
image

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

[CX-786]: https://artsyproduct.atlassian.net/browse/CX-786

### CODE REVIEW

**Review by brainbicycle — APPROVED** [review]
Looks good! +1 on question about date input, if we are just looking for year would be better to label as year and use numeric

**Comment by joanna20** [comment]
Yes "date" should be "year" and +1 to numeric keyboard. thank you!

**Review by ds300 — APPROVED** [review]
:+1:

**Comment by admbtlr** [comment]
I just changed the label and placeholder to `Year`, but left everything everything else as `Date` (field, test-id, etc.) since the `Artwork` model is complicated. Does that seem like a bad thing to do?

**Comment by admbtlr** [comment]
@ds300 ^

**Comment by ds300** [comment]
> Does that seem like a bad thing to do?

Well I think `year` would be a better name but I'm happy for you to merge this as-is if you think it would be difficult to update the name right now.

**Pull request merged**
