### PR TITLE
add packager debug support to VS Code

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **Enhancement**

### Description

Add `Debug React-Native Packager` to VS Code. 

Related VS Code extension 
https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native

**Other features we can include later to improve our debugging**
- Typescript source maps support
- Native Android/iOS

### Screenshots
Screenshot 2020-07-27 at 13 22 36 (2)

#trivial
#skip_new_tests

### CODE REVIEW

**Comment by ds300** [comment]
Yes this is a great idea!  How do you feel about adding a doc describing how to get up and running?

**Comment by MounirDhahri** [comment]
Yes of course, that's a great idea!

**Comment by pvinis** [comment]
Seems cool, I'd love to try this out and compare with react-native-debugger!

**Comment by MounirDhahri** [comment]
cool, oki

**Pull request merged**
