### PR TITLE
feat: add recently-viewed menu item to settings [JFDI]

### PR DESCRIPTION
**Pull request by MounirDhahri**
### Description
**JFDI:** This adds a recently viewed menu item to the settings tab. It also adds tracking to make sure we can tell how it's performing and if users are clicking on it.

Group 6 (1)

https://github.com/artsy/eigen/assets/11945712/35d9df17-1318-4559-8af8-2c0a76a232aa

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Add recently-viewed menu item to setting screen - mounir

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Add recently-viewed menu item to setting screen - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 018a891c7d442b65bba24719974916f09a0ee07f
</p>

**Review by gkartalis — APPROVED** [review]
awesome! I was about to suggest adding also a test in [here](https://github.com/artsy/eigen/blob/f72cadc52dbffba17e4e8d52e62eab1c8c8d97c4/src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx) but then I realized that they are not that helpful so feel free to 🚢

**Review by olerichter00 — APPROVED** [review]
Great idea 🌟

**Comment by MounirDhahri** [comment]
🚢 🚢 🚢 🚢

**Pull request merged**
