### PR TITLE
fix(ONYX-758): fix spinner on the activity screen

### PR DESCRIPTION
**Pull request by dariakoko**
This PR resolves [ONYX-758] 

### Description

| before | after |
| --- | --- |
| https://github.com/artsy/eigen/assets/36167539/659a1a9d-62de-42cd-8ee2-48ba53dee91f | https://github.com/artsy/eigen/assets/36167539/3a7e7d46-1a9d-45c2-b23f-119ee7cf4622 |

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- fix spinner on the activity screen - daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-758]: https://artsyproduct.atlassian.net/browse/ONYX-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (fix spinner on the activity screen - daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 97f4e777a9bbdacce00181da07552005b24f6ce1
</p>

**Review by olerichter00 — DISMISSED** [review]
Thanks for the fix 🙏 

`notificationConnection's` `totalCount` seems to not be working correctly. In Force, I've added [this workaround](https://github.com/artsy/force/blob/82647bb4b64d968e83eca2a6042f8718ea54ecc2/src/Components/Notifications/NotificationsList.tsx#L119) to avoid the spinner from showing up, even if there are no more notifications after the initial load. I will take a look to see if we can fix the root cause of it. Until then, we could also add the workaround to this PR.

**Review by MounirDhahri — DISMISSED** [review]
LGTM! it seems like the loading logic is broken though because of we have no next items, we should not show the spinner

**Comment by MounirDhahri** [comment]
@olerichter00 sorry answered before reading your comment - I remembered your PR as well and the fix

**Comment by dariakoko** [comment]
Added the workaround 🙏

**Review by olerichter00 — APPROVED** [review]

**Pull request merged**
