### PR TITLE
Supports negative lots away distances

### PR DESCRIPTION
**Pull request by ashfurrow**
Handles the case when the distance is negative but taking the absolute value. In order to test this, I corrected the existing `LiveAuctionLotViewControllerTests` that @orta and I had problems with earlier by opening up the salesperson's lot view model for DI. The new snapshots more holistically reflect the state of the auction, because the subjects only have one auction view model now.

For #1547.

### CODE REVIEW

**Comment by orta** [comment]
IMO, we're probably better off not showing anything when its a negative number, here's an example:

```
current lot: 2
[ 1, 2, 3, 4, 5, ... ]
[ x, 0, 1, 2, 3, ... ]
```

Switch current lot 4, without closing 2:
```
current lot: 4
[ 1, 2, 3, 4, 5, ... ]
[ x, -2, -1, 0, 1, ... ]
```

At this time, you would show that both 1 & 4 are 1 lot away. Which is true and is not true, only one thing can be one lot away. I talked to liz who implied that this is normally something to skip an auction, so it would _probably_ be:

```
current lot: 4
[ 1, 2, 3, 4, 5, ... ]
[ x, ?, ?, 0, 1, ... ]
```

Wherein you might come back to them at the end of the auction

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
        
            1 Error
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">There were <a href="https://eigen-ci.s3.amazonaws.com/2843/index.html">snapshot errors</a></td>
    </tr>
    
    
  </tbody>
</table>
  

  
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
        
            1 Warning
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
    
    
  </tbody>
</table>
  

  



Time | Class | Function |
| --- | ----- | ----- |263.9ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-negative-lots-away/Artsy/View_Controllers/Auction/AuctionViewController.swift#L181) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
205.0ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-negative-lots-away/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
180.7ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-negative-lots-away/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
83.5ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-negative-lots-away/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
73.4ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-negative-lots-away/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, sideMargin: String)
71.5ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-negative-lots-away/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
65.3ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-negative-lots-away/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
63.4ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-negative-lots-away/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)




<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
Good point Orta, I think just using "Upcoming" makes sense if they're negative?

**Comment by orta** [comment]
👍

**Comment by ashfurrow** [comment]
I've made some changes to make the image caching suite-wide, so we don't have to repeat it all the time, and I believe they were causing some intermittent failures.

**Comment by orta** [comment]
Alright, I'll let you off with the lack of CHANGELOG

**Pull request merged**
