### PR TITLE
fix home button content size by using insets instead of constraints

### PR DESCRIPTION
**Pull request by 1aurabrown**
fixes https://github.com/artsy/eigen/issues/636

I think that the reason this was happening was that the button's content size is the size of it's image, which is constrained to 20x20. Instead of doing this, I set the contentInset, so that the margins around the image are calculated into the content size.

### CODE REVIEW

**Comment by 1aurabrown** [comment]
screen shot 2015-07-14 at 11 44 34 am

**Comment by alloy** [comment]
These test failures seem unrelated, I’ve restarted the build.

**Comment by 1aurabrown** [comment]
Oh, maybe theres a pixel or two difference. I can fix.

On Tue, Jul 14, 2015 at 12:49, Eloy Durán <notifications@github.com> wrote:
These test failures seem unrelated, I’ve restarted the build.

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/pull/652#issuecomment-121305715] .[https://github.com/notifications/beacon/ADBlTpg_KVOqMnh4UsQpvJTRihTN4jtyks5odTUNgaJpZM4FYV9N.gif]

**Comment by alloy** [comment]
The current test failures make sense, the previous ones were completely different ones _or_ I was just tripping.

**Comment by alloy** [comment]
Perfetto, grazie!

**Pull request merged**
