### PR TITLE
@ashfurrow => added a whitespace gobbler to the show

### PR DESCRIPTION
**Pull request by orta**
Should fix 'dem Reds.

Got a new t-shirt, on the subject of that colour. 

photo on 1-28-15 at 1 46 pm

### CODE REVIEW

**Comment by ashfurrow** [comment]
:greeeeeeeeeen:

**Comment by orta** [comment]
with envy at my t-shirt?

**Comment by ashfurrow** [comment]
Match! But when I get home from the bar, I'll post a selfie of my @Quick tshirt.

**Comment by ashfurrow** [comment]
Oh wait, I'll do it now. 
![image](https://cloud.githubusercontent.com/assets/498212/5947534/25333ede-a73e-11e4-8b4c-6cdc0f619d5d.jpg
/cc @modocache

**Pull request merged**
