### PR TITLE
chore(AMBER-769): Remove "Bidding closed" logic from the artwork grid

### PR DESCRIPTION
**Pull request by lidimayra**
https://github.com/artsy/gravity/pull/17866

This PR resolves [AMBER-769] 

### Description

It now comes straight from Gravity, we don't need it set on the clients anymore

Screenshot 2024-07-02 at 10 32 57

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Remove "Bidding closed" logic from the Artwork Grid implementation and fetch it from Gravity instead

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

cc @artsy/amber-devs 

[AMBER-769]: https://artsyproduct.atlassian.net/browse/AMBER-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Remove "Bidding closed" logic from the Artwork Grid implementation and fetch it from Gravity instead)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9cc573c94085bd0fc56fff2ac00537e273177a3f
</p>

**Review by Mitch-Henson — DISMISSED** [review]

**Comment by Mitch-Henson** [comment]
I approved too quickly because the code changes look great. Looks like you might have to update a few tests like you did in Force. Happy for you to do this and just merge but can also take another look if you want once you are done!

**Comment by lidimayra** [comment]
Thank you, @Mitch-Henson !! I pushed the updated test in [ce05e1d](https://github.com/artsy/eigen/pull/10444/commits/ce05e1dc39b9334cca4538db6923bc176254cc4e)

**Review by jpotts244 — APPROVED** [review]
Awesome!

**Pull request merged**
