### PR TITLE
@alloy => 64 bit support

### PR DESCRIPTION
**Pull request by orta**
screen shot 2015-02-16 at 10 40 40 am

Was seeing this trying to run on device. 

selfie-1

### CODE REVIEW

**Comment by orta** [comment]
closed by #170

**Comment by alloy** [comment]
Mine was missing the indentation fix, though :/

**Comment by orta** [comment]
minimal loss, next time someone is in those tests they can do it :+1:

**Comment by alloy** [comment]
Aye aye :+1:

**Pull request closed without merging**
