### PR TITLE
Changes metaphysics call to use POST instead of GET

### PR DESCRIPTION
**Pull request by ashfurrow**
I've tested it on staging and production and it appears to work. Would like input from @alloy and @orta, if there's no rush.

Fixes https://github.com/artsy/eigen/issues/2213

### CODE REVIEW

**Comment by ashfurrow** [comment]
Test fail is legit, waiting to here back about my approach here before fixing.

**Comment by alloy** [comment]
👍

**Comment by ashfurrow** [comment]
Okay, updated unit test. Will merge on 🍏

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Pull request merged**
