### PR TITLE
fix: hard-coded collection title

### PR DESCRIPTION
**Pull request by anandaroop**
This PR resolves [this bug report](https://artsy.slack.com/archives/C03N12SR0RK/p1719942428131239)

### Description

Replaces the hard-coded title in the sticky header with the collection's actual `title` attribute.

https://github.com/artsy/eigen/assets/140521/8be664df-32d1-41b6-90c3-f5e9280da77d

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Fix incorrect title on collection screen - roop

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Fix incorrect title on collection screen - roop)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 773a9636208aba07cf9ca6a0edeec5a9c10cda27
</p>

**Comment by joeyAghion** [comment]
Good catch!

**Review by MounirDhahri — APPROVED** [review]
OMG ! thanks

**Comment by MounirDhahri** [comment]
Hey @gkartalis @brainbicycle  - I would like to release this fix to the existing release. Any issues?

**Comment by gkartalis** [comment]
@MounirDhahri no that sounds reasonable - lets do it

**Comment by MounirDhahri** [comment]
Great, creating a branch with the hotfix now.

**Comment by MounirDhahri** [comment]
Done - should be fixed by all users next time they open the app

https://github.com/artsy/eigen/assets/11945712/ad949be5-1c63-46f9-a125-8f5983a8bb14

**Comment by anandaroop** [comment]
Thank you for following up!

Confirmed that this works on my device (after switching to App Store version and force-restarting)

**Pull request merged**
