### PR TITLE
Merged 3.2.5 and 3.2.6 patches into master

### PR DESCRIPTION
**Pull request by ashfurrow**
This PR merges the patches 3.2.5 and 3.2.6 into master. This includes improved GraphQL response serialization, improved logging of GraphQL response errors, custom sale-on-hold banners, sending client metadata to Causality, a fix for bid labels not updating, and a fix for Eigen deploys. Here are the relevant PRs:

- https://github.com/artsy/eigen/pull/2436
- https://github.com/artsy/eigen/pull/2432
- https://github.com/artsy/eigen/pull/2435
- https://github.com/artsy/eigen/pull/2430
- https://github.com/artsy/eigen/pull/2429
- https://github.com/artsy/eigen/pull/2423

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_travis">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ashfurrow** [comment]
I'll take a look at the failing tests.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><h4 id="found-unstubbed-networking-requests">Found unstubbed networking requests</h4>

<ul>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__fails_on_an_empty_response</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__it_works_in_the_success_case</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__doesnt_crash_with_null_JSON_in_the_data_field</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__doesnt_crash_with_null_JSON_in_the_me_field</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__doesnt_crash_with_null_JSON_in_the_savedartworks_field</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__doesnt_crash_with_null_JSON_in_the_artworksconnection_field</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__doesnt_crash_with_null_JSON_in_the_pageInfo_field</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__doesnt_crash_with_null_JSON_in_the_edges_field</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__doesnt_crash_with_null_edges</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPIArtworks+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPIArtworksSpec</a> in <code>test_favourites__doesnt_crash_with_null_cursor_info</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPISales+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPISalesSpec</a> in <code>test_it_works_in_the_success_case</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPISales+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPISalesSpec</a> in <code>test_fails_on_an_empty_response</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPISales+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPISalesSpec</a> in <code>test_doesnt_crash_with_null_JSON_in_the_data_field</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPISales+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPISalesSpec</a> in <code>test_doesnt_crash_with_null_JSON_in_the_sale_field</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPISales+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPISalesSpec</a> in <code>test_doesnt_crash_with_null_JSON_in_the_saleartworks_field</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPISales+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPISalesSpec</a> in <code>test_returns_an_empty_array_for_an_NSNull_saleartworks</code></li>
  <li><a href="https://github.com/search?q=ArtsyAPISales+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=✓">ArtsyAPISalesSpec</a> in <code>test_returns_an_empty_array_for_saleartworks_with_NSNull_artworks</code></li>
</ul>
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_circle">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ashfurrow** [comment]
@alloy this is ready for review

**Comment by alloy** [comment]
Great effort 💪

Outside of tests, are there any changes to the code that wasn’t in any of the already reviewed PRs?

**Comment by ashfurrow** [comment]
Nope, it's all existing stuff 👍

**Comment by alloy** [comment]
Alrighty, then I’m going to be ok with me just skimming 👍

**Pull request merged**
