### PR TITLE
[MX-286] Remove UIWebView usage in tests

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **Enhancement**

This PR resolves [MX-286]

### Description

Migrate to `WKWebView ` because Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

there were only 2 references for UIWebView in the project

This PR is a follow-up from [this PR](https://github.com/artsy/eigen/pull/606)

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))

#trivial

[MX-286]: https://artsyproduct.atlassian.net/browse/MX-286

### CODE REVIEW

**Comment by MounirDhahri** [comment]
I just realized some of the pods are still using the UIWebview, I will adjust them now

**Comment by ashfurrow** [comment]
Yeah, was just about to point that out 👍 Thanks Mounir! And good catch – I'm glad that #606 already took care of the lion's share of the work here 🎉

**Comment by ashfurrow** [comment]
Looks like we might need to update to a newer version of the Facebook SDK – might be tricky. @brainbicycle has most recently worked with the login code (which is the only place we use Facebook's SDK) so reach out if you need a hand 👍

**Comment by MounirDhahri** [comment]
Cool, I will reach out to @brainbicycle if I had any issues

**Pull request closed without merging**
