### PR TITLE
feat(DIA-307): use inEditorialFeed false when querying articles

### PR DESCRIPTION
**Pull request by araujobarret**
This PR resolves [DIA-307] 

### Description

Related to https://github.com/artsy/metaphysics/pull/5388 remove the `inEditorialFeed` to show articles with `NEWS` layout in the whole app.

In the video below, if we don't show `NEWS` then we won't show the Article in the About tab

https://github.com/artsy/eigen/assets/15792853/ef550b2f-b5a7-4735-b046-5541746b32a2

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- shows Articles with layout NEWS in all Articles - araujobarret

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[DIA-307]: https://artsyproduct.atlassian.net/browse/DIA-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (shows Articles with layout NEWS in all Articles - araujobarret)
- undefined (changes)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0f0af147b069a6272285cfc3f3e482745c4ecba8
</p>

**Review by jonallured — APPROVED** [review]
LGTM!! 🎉

**Review by gkartalis — APPROVED** [review]
👏

**Comment by MounirDhahri** [comment]
Do we no longer have the concept of unpublished articles? we are using this flag intentionally to make sure we don't accidentally show articles that are not supposed to be seen. 
https://github.com/artsy/eigen/pull/4675

**Comment by jonallured** [comment]
> Do we no longer have the concept of unpublished articles?

This is a good question. From the sound of this flag it seems to suppress unpublished articles but I don't see it actually doing that! From what I was able to trace through MP and into Positron this flag is actually about the `layout` of the item NOT whether it's published or not!

https://github.com/artsy/positron/blob/a3965b72b7c312320f9d4414e433cdc4ab14eaf4/src/api/apps/articles/model/retrieve.js#L140-L143

**Pull request merged**
