### PR TITLE
tooling(storage): trying to remove some extra stuff from redux to zustand

### PR DESCRIPTION
**Pull request by pvinis**
The type of this PR is: **Enhancement**

This PR resolves []

### Description

After seeing the problems redux has caused us, with the require cycles, I am trying out this new way, of having separate, smaller stores, with zustand. We recently added the toasts in the GlobalStore, and it's only temporary storage, so it's the perfect candidate to move out of redux.

I would like to try to connect this with some actions/thunks if they are needed, to see how that would look like, but definitely, that state feels best staying separate from the rest.

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Move toast state to zustand - pavlos

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Move toast state to zustand - pavlos)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4a15563b6da5328874cd7b8a08bbb0067b88d63f
</p>

**Review by MounirDhahri — APPROVED** [review]
This looks good to me.

I have one question though, I don't understand why you needed to use `zustand` to manage the toast store state. Wouldn't using `createContextStore` from easy-peasy give us the same result and make additions easier since most of the team now is familiar with easy-peasy stores?

**Review by olerichter00 — APPROVED** [review]
Looks good to me!

**Comment by admbtlr** [comment]
> I have one question though, I don't understand why you needed to use `zustand` to manage the toast store state. Wouldn't using `createContextStore` from easy-peasy give us the same result and make additions easier since most of the team now is familiar with easy-peasy stores?

I'm also interested in this. I don't like the idea of using both `zustand` and `easy-peasy` unless there's a really compelling reason.

Also, can you change the PR title to `chore(storage):...` please! 😝

**Comment by MounirDhahri** [comment]
Closing PR for inactivity - please feel free to reopen it if needed 👌

**Pull request closed without merging**
