### PR TITLE
fix: NSInternalInconsistencyException sentry crash iOS 17

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [PHIRE-1389] 

### Description

Fixes this [iOS sentry crash](https://artsynet.sentry.io/issues/4479226101/events/d98fd95bd4c74271a184596c901fac26/).

By looking for this issue found connections with two of our deps:

1. react-native-linear-gradient 
1. react-native-fast-image

The `react-native-linear-gradient` has already fixed the issue and released a version so bumping in order to fix the issue from there.

For `react-native-fast-image` we need to [patch it](https://github.com/muntius/react-native-fast-image/commit/fc2b8acd97f07989e312f5cbd61d2e541fda3611#diff-24ce0837ec34bb03c94a76bc62258a10d1c729e2e6b2f3ac706eab55f76dc0ecR87) temporarily until they release this with a new version.

Related issues:
https://github.com/react-native-linear-gradient/react-native-linear-gradient/issues/618
https://github.com/DylanVann/react-native-fast-image/issues/1002

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

- fixes iOS 17 image crash 

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[PHIRE-1389]: https://artsyproduct.atlassian.net/browse/PHIRE-1389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MrSltun — APPROVED** [review]

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- iOS user-facing changes (fixes iOS 17 image crash - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ffd024265e9a8bcf560bd4d5d7ac59df9f71bab0
</p>

**Review by MounirDhahri — APPROVED** [review]
nice catch! how did you notice it?

**Comment by gkartalis** [comment]
@MounirDhahri As I was monitoring the releases from the [latest ios sentry release](https://artsynet.sentry.io/releases/ios-8.58.0-2024.12.02.16/?project=5867225) and filtering unhandled crashes

**Comment by MounirDhahri** [comment]
thanks - glad someone is doing that

**Comment by dariakoko** [comment]
Good catch, thanks!

**Pull request merged**
