### PR TITLE
feat: enable Inquiry Checkout (PURCHASE-2684)

### PR DESCRIPTION
**Pull request by starsirius**
The type of this PR is: **Feature**

This enables Inquiry Checkout. The corresponding Echo PR is [here](https://github.com/artsy/echo/pull/85).

https://artsyproduct.atlassian.net/browse/PURCHASE-2684

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

### CODE REVIEW

**Comment by starsirius** [comment]
CI failed because Echo hasn't had [the new feature key](https://github.com/artsy/echo/pull/85). This makes me wonder if we should

1. Set the new feature to `false` in [the Echo PR](https://github.com/artsy/echo/pull/85), merge and deploy that.
2. Rebuild this PR, merge and submit for approval
3. When we are ready to release Inquiry Checkout, update the Echo flag to `true`.

Would love to pair on this and learn more about the sequencing!

Screen Shot 2021-05-16 at 10 46 28 PM

**Comment by pvinis** [comment]
But in general, I think merging the echo PR should make this PR here pass, and it will be good to go.

**Comment by ds300** [comment]
yeah this test is to make sure that the echo flag exists before deploying.

@starsirius the steps you outlined are exactly how we suggest to do things for _timed releases_. If you don't care about whether the feature becomes available on a particular day, you can also set the echo flag to `true` and then the feature will be switched on as soon as people update their apps to the version that this PR gets deployed in.

**Comment by starsirius** [comment]
Thanks @pvinis and @ds300! I submitted another [Echo PR](https://github.com/artsy/echo/pull/91) to disable the feature for now. Will rebuild this PR again once it's deployed! 🙏

**Comment by pvinis** [comment]
Could you make this PR into a draft, instead of using the [don't merge] title? It makes it clearer for us 🙏.

**Pull request merged**
