### PR TITLE
[CX-1564] Adding inEditorialFeed: true to articlesConnection for all Fair and Other Queries

### PR DESCRIPTION
**Pull request by chr-tatu**
The type of this PR is: Enhancement

This PR resolves [[CX-1564](https://artsyproduct.atlassian.net/browse/CX-1564)]

### Description

Adding inEditorialFeed: true to articlesConnection for all Fair and Other Queries. Please only merge this PR after the one from  [metaphysics#3291](https://github.com/artsy/metaphysics/pull/3291).   

( cc @pvinis )

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

#### Dev changes
- Adding inEditorialFeed: true to articlesConnection for all Fair and Other Queries. - christian

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Adding inEditorialFeed: true to articlesConnection for all Fair and Other Queries.)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ee86dd0b03438d9d2ef4f9fedfe70644f262fa26
</p>

**Comment by olerichter00** [comment]
#squashongreen

**Comment by olerichter00** [comment]
Looks good! 
I added your name to the Changelog entry, rebased the branch, and updated the generated Relay queries. The tests should pass now :)

**Comment by chr-tatu** [comment]
@olerichter00: Thanks for adding the generated files. Are those added via the commit hook?

**Comment by olerichter00** [comment]
After rebasing, I just ran `yarn start` (`yarn relay` would do the job as well) to change the generated Relay queries.

**Pull request merged**
