### PR TITLE
fix: Order History: "Unable to load" page is opened (exception occurs) when artwork is deleted/unpublished from order (PX-4253)

### PR DESCRIPTION
**Pull request by Serge0n**
The type of this PR is: **Bugfix**

This PR resolves [PX-4253]

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

image
[PX-4253]: https://artsyproduct.atlassian.net/browse/PX-4253

### CODE REVIEW

**Comment by sweir27** [comment]
@Serge0n Can you screenshot what the "Order Details" page looks like in the case where the artwork is deleted? I'm wondering if we need to gracefully degrade that view as well.

**Review by brainbicycle — APPROVED** [review]
Nice!

**Comment by Serge0n** [comment]
> @Serge0n Can you screenshot what the "Order Details" page looks like in the case where the artwork is deleted? I'm wondering if we need to gracefully degrade that view as well.

Yes, there is the same bug in OrderDetails. I'll fix it too

**Comment by MounirDhahri** [comment]
This is great work but I think this won't be fixing the issue as adding the @principalField directive only suppresses the warning on dev but the issue remains there for production builds. I guess we have 2 ways to fix this for now: First way, would be probably from metaphysics level, I think that's the impact over perfection approach. The second way, would be probably adjust the way we create orders and instead of referring to the original artwork, we will need to be referring to a snapshot of the artwork that was ordered. 
I will be pairing with @Serge0n on the metaphysics approach, but I strongly suggest that we consider the second approach for a more robust solution. Please correct me if I am wrong.

**Pull request merged**
