### PR TITLE
[MSG] Remove back button from inbox VC

### PR DESCRIPTION
**Pull request by mennenia**
Fix [Emission#666](https://github.com/artsy/emission/issues/666)

I only managed to get it out of the main inbox view, the button still hangs around on a conversation view, issue futher explained in #2389

screen shot 2017-07-12 at 12 04 51

### CODE REVIEW

**Comment by alloy** [comment]
I don’t think the button should be completely removed, or at least not special-cased. For instance, currently we show the inbox in a nav controller from the admin menu, how would you navigate back?

Additionally, I don’t think we need to subclass to implement the menu aware protocol, iirc we do it through a class category for other component VCs.

In retrospect, maybe we should’ve waited to fix this until we got to reworking the locations of where these VCs will live so that we know for sure what is and is not needed. Sorry 😑

**Comment by mennenia** [comment]
@alloy ahh so my understand was that this was supposed to be a quick fix (seeing as it's for the upcoming beta), because this implementation is definitely temporary (and hence I've created #2389). It needs a more thorough solution.

I couldn't quite get the category in `ARAppDelegate+Emission` to work myself, and because I assumed we'd delete this later, I opted for the subclass.

As for losing the behaviour of the back button, that would've been a given, considering you can only launch it from the admin list at the moment. I figured one would kill the app, shake again, or just use the other tab buttons to navigate around.

Feel free to just close this PR though if you don't think it's helpful for this beta.

**Comment by alloy** [comment]
Yeah alas I think we should punt on it for now. Let’s keep the branch around for now, though.

**Comment by alloy** [comment]
Aaargh, damn Safari extension beat me to it. Can you re-push your branch?

**Comment by mennenia** [comment]
Branch has been restored 👍

**Comment by alloy** [comment]
Aaaaaarggggggggghhhh… Can you do it one more time? It happened again, I’m not gonna click the notification for this PR again, I promise.

**Comment by orta** [comment]
Lol, I just deleted it

**Comment by orta** [comment]
Want to push it with a different name?

**Pull request closed without merging**
