### PR TITLE
build(deps): remove unused deps 

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [PHIRE-591] 

### Description

Removes:
- [x] `@omakase/cli`
- [x]  `auto` 

since they are obsolete and outdated and we don't use them in eigen (there were also some security dependency issues around those)

> [!CAUTION]
> Let me know if we use those somewhere that I am not aware of

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- remove unused dev deps - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[PHIRE-591]: https://artsyproduct.atlassian.net/browse/PHIRE-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gkartalis** [comment]
still WIP as I am reviewing the rest of the dependabot sec alerts

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (remove unused dev deps - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 55bbd74cf273f41bb499f2bf36c24905d2908b48
</p>

**Review by MrSltun — APPROVED** [review]
🧹🧹🧹

**Review by MounirDhahri — APPROVED** [review]
Byeee

**Pull request merged**
