### PR TITLE
chore: remove useless flatlist #doNotMerge

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [] 

### Description

As I was working on improving performance of artwork grids noticed that we had a list inside a list on the searchartworksgrid so I removed it. 

The feature doesn't change at all functionality wise.

|Before|After|
|---|---|
|simulator_screenshot_36B1CD57-61AD-4590-AF8B-39759E85FEED|simulator_screenshot_F489DBF0-945F-4253-B9F3-8E1FADCF1CDE
|

### PR Checklist
- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- removed extra useless flatlist from searchArtworkGrid - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by pvinis — APPROVED** [review]
💜 simplify 💜

**Comment by gkartalis** [comment]
There is only one problem that I need to fix 😬

https://user-images.githubusercontent.com/21178754/202679944-47653c2a-fe7c-455f-90e3-e5c6fcbf3137.mp4

the is loading when fetching more seems a bit broken 👀 looking into it now

**Comment by pvinis** [comment]
ah nice. thanks for looking into it.

**Comment by gkartalis** [comment]
closing this since we progressed the artwork grids pr and there is no time in diving deeper into [the issue](https://github.com/artsy/eigen/pull/7684#issuecomment-1319809421) above

**Pull request closed without merging**
