### PR TITLE
Updates to CocoaPods master branch #trivial

### PR DESCRIPTION
**Pull request by ashfurrow**
Should fix [CI build failures](https://circleci.com/gh/artsy/eigen/2222).

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hmm, getting the same error on `pod install` locally: 

```
bundle exec pod install
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/cocoapods-a33c0d282344/lib/cocoapods/config.rb:135:in `initialize': wrong number of arguments (1 for 0) (ArgumentError)
	from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/cocoapods-a33c0d282344/lib/cocoapods/config.rb:135:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/cocoapods-a33c0d282344/lib/cocoapods/config.rb:135:in `sources_manager'
	from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/cocoapods-a33c0d282344/lib/cocoapods/user_interface/error_report.rb:163:in `repo_information'
	from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/cocoapods-a33c0d282344/lib/cocoapods/user_interface/error_report.rb:76:in `stack'
	from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/cocoapods-a33c0d282344/lib/cocoapods/user_interface/error_report.rb:23:in `report'
	from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/cocoapods-a33c0d282344/lib/cocoapods/command.rb:64:in `report_error'
	from /usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:396:in `handle_exception'
	from /usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:337:in `rescue in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:325:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/cocoapods-a33c0d282344/lib/cocoapods/command.rb:50:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/bundler/gems/cocoapods-a33c0d282344/bin/pod:44:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/bin/pod:23:in `load'
	from /usr/local/lib/ruby/gems/2.2.0/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
might need a custom cocoapods-core or claide - try that on master too

**Comment by ashfurrow** [comment]
Ah right right, been a while :sweat_smile:

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">1 Warning</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td><h4>Found unstubbbed networking requests</h4>

<ul>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
</ul>
</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
Yep

**Pull request merged**
