### PR TITLE
Added initial fastlane integration

### PR DESCRIPTION
**Pull request by KrauseFx**
### This commits adds a very basic [fastlane](http://fastlane.tools) integration:

- Added [snapshot](https://github.com/KrauseFx/snapshot) integration to create 4 screenshots on different devices (see screenshot on bottom)
- Added [fastlane](https://github.com/KrauseFx/fastlane) dependency to `Gemfile`
- Added [fastlane](https://github.com/KrauseFx/fastlane) screenshots folder to `.gitignore`

### There are 2 lanes available:

- `test`: Only run unit tests and integration tests (which will also generate new screenshots)
- `beta`: Run tests, create new screenshots and build&upload beta app to Hockey

There is also one empty lane `deploy`, which can later be used for App Store distribution.

### How can I use it?

Just run

```
fastlane test
```

or

```
fastlane beta
```

to trigger the `beta` lane. Add this as a build step to Travis.

You can also run each tool individually, for example, to generate new screenshots, just run `snapshot` in the project directory and `snapshot` will generate new screenshots for you.

### Next things to do:

- If you decide to also use [deliver](https://github.com/KrauseFx/deliver) or [sigh](https://github.com/KrauseFx/sigh), update the `fastlane/Appfile` and set your `apple_id`. This is a ruby file, so you can easily change it to `apple_id ENV['APPLE_ID']`
- To enable Slack notifications, make sure to have a POST url stored in the environment variable `SLACK_URL`. Once this is done, enable the `slack` integration in the `fastlane/Fastfile`
- If you want to hide the `fastlane` folder, you can prepend a `.` => `.fastlane`
- Implement a better `UI Automation` script for `snapshot`, to support different languages and show more interesting screens. This might require some work on the `accessibilityIdentifier`. More information on the [snapshot project page](https://github.com/KrauseFx/snapshot)
- Set up [deliver](https://github.com/KrauseFx/deliver) to upload screenshots, app metadata and app updates to iTunes Connect
- You can define as many lanes as you want, for all kinds of actions
- Once you have a Jenkins computer set up, please follow the [Jenkins fastlane Guide](https://github.com/krausefx/fastlane#jenkins-integration) to make use of the nice integration, which shows lane results and the generated screenshots right in Jenkins.

##### Let me know if there is anything I can help you with :+1: 

Generated screenshots summary
screenshot 2015-02-17 22 39 48

### CODE REVIEW

**Comment by orta** [comment]
THIS ISSSSS AMAAZINGGGG

Russian Armed Forces

**Comment by segiddins** [comment]
Those files should probably have trailing newlines

**Comment by orta** [comment]
I think the failing GIF is the worst part of this PR, though, it seems it does need a rebase. Sorry!

**Comment by KrauseFx** [comment]
There was a merge conflict after the merge of https://github.com/artsy/eigen/pull/193

I fixed the merge conflict and added trailing newlines to the newly added files :+1:

**Comment by KrauseFx** [comment]
The failing build was not caused by this pull request

**Comment by alloy** [comment]
This looks amazing, great work @KrauseFx! :heart:

**Comment by orta** [comment]
OK! Done a review, looks good to me! Thanks a bunch, will make an issue around expanding on this for the Clean Slate Milestone.

**Comment by KrauseFx** [comment]
@alloy :smiley: 

Thanks for merging @orta :+1: 

Let me know if everything works for you!

**Pull request merged**
