### PR TITLE
fix: my account edit ui block

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **Bugfix**

This PR resolves [MX-557]

### Description
- The UI Blocks after failed mutation on MyProfile Edit Phone - Edit Email 
- Edit Password returns the wrong message when the user changes his current password with an invalid password

Screen_Recording_2020-09-30_at_15 29 23

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

[MX-557]: https://artsyproduct.atlassian.net/browse/MX-557

### CODE REVIEW

**Comment by pvinis** [comment]
Let's wait for today's KS to check on #3954 and see how we move to fix both 😬.

**Comment by pvinis** [comment]
from KS, let's try https://reactnative.dev/docs/modal#ondismiss instead of a setTimeout for popping back to account. 🤞

**Comment by MounirDhahri** [comment]
Thanks for the adjustments @pvinis please feel free to merge

**Comment by pvinis** [comment]
I tried it again and I can't make it work on my sim 🤦. I don't know if I'm doing something wrong or what's up.

**Comment by MounirDhahri** [comment]
just say your comment, I will check it out

**Comment by pvinis** [comment]
We worked on this with mounir, I asked for extra reviews just to get some eyes on this, but we will #squashonmerge to release a beta and run through the QA script.

**Comment by pvinis** [comment]
Extra changes on this:
- removed the deferred alerts, and made this part of the `onDismiss` of the Alert
- moved most of the error alerts and made them part of the Input, like in the spec https://www.figma.com/file/OSXdLHRQMbe6k6a58uW5Xp/Profile-Tab?node-id=150%3A2890

**Pull request merged**
