### PR TITLE
fix(CX-1722): [unknown] sentry errors

### PR DESCRIPTION
**Pull request by rajsam003**
The type of this PR is: Bugfix

This PR resolves [CX-1722]

### Description

This PR is a fix for Sentry errors where it shows the error title as **[unknowns]**. Now with this fix, we can see the error message as the title. 

For eg, for [this](https://sentry.io/organizations/artsynet/issues/2339408559/?query=is%3Aunresolved) sentry issue. We will get **ESOCKETTIMEDOUT** as the title instead of **[unknown]**

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Showing the error message as the title instead of [unknown].

</details>

[CX-1722]: https://artsyproduct.atlassian.net/browse/CX-1722

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Show error name on Sentry)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5d98824b38e298c3c397aad5a410bb84ddc1f33d
</p>

**Comment by olerichter00** [comment]
Let's fix these tests and work through the **PR Checklist** (in the PR description).

**Comment by olerichter00** [comment]
@brainbicycle @pvinis what do you think?

**Comment by pvinis** [comment]
Sorry for the delay.

I think `req.operation.name` would still be useful, I wonder if we could append it or if it's always undefined.

Also, it would be cool to trigger one on sentry and see that it works, with a link or screenshot.

Otherwise, I think that change makes sense. 👍

**Comment by brainbicycle** [comment]
This seems reasonable to me, agree would be nice to see a working example but also okay with just merging and trying it out.

**Review by brainbicycle — APPROVED** [review]

**Pull request merged**
