### PR TITLE
refactor(Input): Unify and fix Input multiline

### PR DESCRIPTION
**Pull request by pvinis**
The type of this PR is: **Enhancement**

This PR resolves []

### Description

A bunch of components are using `Input` from palette, some use `TextInput` from RN, and some use `TextArea` from `lib/Components`.

We are trying to unify here. Now we will only use `Input multiline` for "text area" inputs in eigen.

In this PR we fix a padding issue on `Input multiline`, we remove the `TextArea` component and its 2 uses, and we will make a ticket to replace all `TextInput` from RN with `Input multiline` from palette.

Also removed two tests, one skipped one not. They were using `checkbox-shipping_quote` as a test id, and this string appears nowhere in the repo, so..

before (notice the wrong border color and font size)

Screenshot 2021-11-09 at 10 35 52

after
Screenshot 2021-11-09 at 11 07 09

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- unifying the Input multiline - pavlos, sam

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (unifying the Input multiline - pavlos, sam)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4ccb4983837856a9ad08b1c5843498e633e2aeda
</p>

**Review by dimatretyak — APPROVED** [review]
Looks good to me. But I noticed a small problem: when the keyboard is open, it does not scroll to `Input` with `multiline` on iOS (PROVENANCE input)

https://user-images.githubusercontent.com/3513494/140916544-6f2e72e5-5965-4cc2-8d85-79572fa4c32b.mp4


https://user-images.githubusercontent.com/3513494/140916515-22464dde-27c7-4f8e-9cb6-119056eff684.mp4

**Comment by dimatretyak** [comment]
Everything is fine on Android

https://user-images.githubusercontent.com/3513494/140917251-8a125db9-ffd9-4d11-9e33-eea6e9a8123d.mp4

**Comment by pvinis** [comment]
interesting. good catch. ill take a look.

**Comment by pvinis** [comment]
fixed, maybe you could take another look @dimatretyak?

**Review by MounirDhahri — APPROVED** [review]

**Comment by dimatretyak** [comment]
@pvinis everything looks great. Thanks for the fix

#### iOS
https://user-images.githubusercontent.com/3513494/141287243-1a86d5e4-3904-4650-9ddc-b0a6995f296d.mp4

#### Android

**Comment by pvinis** [comment]
thanks for checking again!

**Pull request merged**
