### PR TITLE
Remove X-Callback support from our app - introduced in #354

### PR DESCRIPTION
**Pull request by orta**
Now that Eigen controls the artsy.net domain system wide, there's no need to faff with x-callback stuff. Everyone will just treat URLs as something they can route rather than making special cases.

### CODE REVIEW

**Comment by orta** [comment]
Hm, the fail here is Danger. Tests are :+1: 
Gonna jump into Danger now.

**Comment by orta** [comment]
I've fixed Danger - https://github.com/KrauseFx/danger/pull/35

**Comment by ashfurrow** [comment]
Looks good, will merge on :green_apple:

**Comment by orta** [comment]
ok

**Pull request merged**
