### PR TITLE
@orta => Move search to nav bar

### LINKED ISSUE #482: Adjust search UI

### PR DESCRIPTION
**Pull request by alloy**
Closes #482.

nav-bar-search

* This is not using any custom transition for the view controller yet. Is it really needed and, if so, what kind of transition?
* This still needs a properly sized search icon, which @katarinabatina should be getting me later today.

### CODE REVIEW

**Comment by alloy** [comment]
@katarinabatina After using it, I’m still not really sold on it. _But_ I’m really unsure if that’s because it needs to grow on me or if I really do prefer it having its own tab.

**Comment by orta** [comment]
well... in the time you've done this PR. I have:

Read 3 chapters of https://parahumans.wordpress.com/about/
Made a hot chocolate.
Made 2 crumpets. 



Good to see one of us is doing something useful.

**Comment by orta** [comment]
In an ideal world, I'd like to see a return to the darkened blurred background of the screen you were seeing before hitting the button. Though feel free to do whatever Katarina says :dancers:

**Comment by orta** [comment]
does the search disappear with the back button? ( it should )

**Comment by alloy** [comment]
> Good to see one of us is doing something useful.

:disappointed: I’ll see how to make crumpets and learn to read.

> I'd like to see a return to the darkened blurred background of the screen you were seeing before hitting the button.

I’m not sure what “darkened blurred background” you are referring to.

> does the search disappear with the back button? ( it should )

Aye, it does. I should have included that in the GIF.

**Comment by orta** [comment]
How I'd see it:

Take a snapshot, then progressively darken + blur it:
screen shot 2015-07-10 at 18 25 03

Then bring in the white bits + keyboard

**Comment by katarinabatina** [comment]
@alloy I agree with @orta completely the push is not desirable. I would hope that we blur the current screen as @orta has outlined

**Comment by orta** [comment]
@alloy - https://github.com/artsy/eigen-private/blob/1.3.0/Artsy/Classes/Utils/Navigation%20Animations/ARAppMenuTransition.m this is the old transition for the menu, which I think should cover most of what you're doing

**Comment by alloy** [comment]
search-transition

**Comment by alloy** [comment]
Sooo merging this.

**Pull request merged**
