### PR TITLE
chore(TX-1114): update wire transfer details

### PR DESCRIPTION
**Pull request by rquartararo**
This PR resolves [TX-1114] 

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Update wire transfer bank details 

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[TX-1114]: https://artsyproduct.atlassian.net/browse/TX-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — COMMENTED** [review]
I know [WirePaymentSection.tsx](https://github.com/artsy/eigen/blob/d74c75545e1950154f060fc0a80322f917dbcf24/src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx#L110) was there ahead of this PR but nevertheless, I would strongly suggest to pull Artsy bank details values from metaphysics instead or a remote JSON file instead of hard coding them in the app. This will help us in the future avoid receiving transfers on the wrong account or asking users which account they wired money to

**Comment by rquartararo** [comment]
> I know [WirePaymentSection.tsx](https://github.com/artsy/eigen/blob/d74c75545e1950154f060fc0a80322f917dbcf24/src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx#L110) was there ahead of this PR but nevertheless, I would strongly suggest to pull Artsy bank details values from metaphysics instead or a remote JSON file instead of hard coding them in the app. This will help us in the future avoid receiving transfers on the wrong account or asking users which account they wired money to

@MounirDhahri I definitely agree. I think this was talked about at some point but a ticket was never created (that I know of) so I've created one [here.](https://artsyproduct.atlassian.net/browse/TX-1118) This will also help with not having to create 4 different PR's to update this info 😅

**Review by starsirius — APPROVED** [review]
Thank you for creating the followup ticket and moved bank information to an API.

**Comment by starsirius** [comment]
@rquartararo Similar to https://github.com/artsy/force/pull/12221, can you also help fix the typo in Eigen? Should've called out that in the ticket. My bad. 🙏

**Pull request merged**
