### PR TITLE
fix: broken photo picker padding, remove excluded_arch flags

### PR DESCRIPTION
**Pull request by brainbicycle**
This PR resolves [PHIRE-1407] 

### Description

This little rabbit hole solved some mysteries! 

The breakage in photo picker in iOS 18 sims is due to arm64 being in excluded archs list, adding this flag is consequential, it means that builds default to a simulator running in Rosetta rather than on the m1 arch, that probably has consequences for performance but also more importantly stability:
https://forums.developer.apple.com/forums/thread/765079

I think we added this to workaround some build issues on m1, my machine which is m1 builds fine but if anyone could pull down and try to run it would be appreciated 🙏 

I am hoping this will solve some of our running on sim issues, but let's see, for me:
- Constant PIF transfer errors needing an Xcode restart
- Not being able to delete the app from the sim and needing to restart the sim 

And a bonus, this I think is why we need rosetta in ci, so we should be able to get rid of that!

photo-picker

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- remove excluded archs flags, bye rosetta - brian 

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[PHIRE-1407]: https://artsyproduct.atlassian.net/browse/PHIRE-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (remove excluded archs flags, bye rosetta - brian - brainbicycle)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cb12b22b62235e8556999c1b9cc490bcf92db5d7
</p>

**Comment by brainbicycle** [comment]
oof running into an old friend: https://github.com/CocoaPods/CocoaPods/issues/11839 
The test failures are I think just snapshot failures due to non-rosetta sim differences but I can't run the tests locally due to the above, will timebox a fix tomorrow

**Review by MounirDhahri — APPROVED** [review]
Amazing! thank you sooo much!

**Review by gkartalis — DISMISSED** [review]

**Review by dariakoko — APPROVED** [review]
Tested on my M3, it works
Thanks Brian!

**Review by MrSltun — DISMISSED** [review]
Thank you! 🌟

**Pull request merged**
