### PR TITLE
fix: correct mismatch of time until live auction

### PR DESCRIPTION
**Pull request by mc-jones**
The type of this PR is: BugFix 

This PR resolves [PURCHASE-2621]

### Description

This PR addresses a bug that resulted in the start time of a live auction being display in two different ways in the Auctions view and the Individual Auctions view. 
e1b3a8cf-428f-400f-8cbc-1fc99e6a5d10 e1781532-7569-4dca-9291-8d4b6339cc97

Both views now show the time until auction in hours, when less than 24, and the individual auction page also includes the minutes until auction to be more precise. 

Phone 8
Screen Shot 2021-05-25 at 4 18 29 PM119561344-0bb17500-bd73-11eb-8339-61d7a7a88c8a

Pixel 2 
pixel 4  

In addition to providing more information to the user, this addresses an issue cause by how we handle time calculation on the client vs the server. More detail in this [slack thread](https://artsy.slack.com/archives/C9YNS4X32/p1621871560189300). 

### For future consideration 
We should consider unifying how we handle time calculations between the client and server, as it is likely we will continue to run into bugs following the current approach. 

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

[CX-434]: https://artsyproduct.atlassian.net/browse/CX-434

[PURCHASE-2621]: https://artsyproduct.atlassian.net/browse/PURCHASE-2621

### CODE REVIEW

**Comment by erikdstock** [comment]
Looks good here but I'd like to confirm with design (cc @ArvindLall ) that we are okay with showing this more fine-grained timing, as adding minutes might cause confusion when the screen doesn't update automatically.

**Review by erikdstock — COMMENTED** [review]
Looks good assuming we are okay from a UX perspective on the time specificity in minutes. Thank you!

**Comment by mc-jones** [comment]
Thanks @erikdstock! Ran it by him in the Jira ticket and he was on board. But @ArvindLall of course feel free to let me know if any additional thoughts have come up.

**Review by brainbicycle — APPROVED** [review]
Looks good to me! ⏳ merge when ready

**Pull request merged**
