### PR TITLE
fix: main patch issues

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [] 

### Description

Attempt to fix main patch issues due to https://github.com/artsy/eigen/pull/8847. 

More context: merging the PR above #8847 caused some issues with ci as you can see on the checks but only when merged to main.

Then I opened https://github.com/artsy/eigen/pull/8848 for refreshing the cache hoping to fix the issue but the issue remained on main only 🤔.

### Other fixes @brainbicycle
This ended up requiring a few fixes:
- updated our android images to non-deprecated version
- added ruby orb to ensure we have correct ruby installed on machines, was causing a bundle install failure (aside, it seems we run ruby and gem installation too often worth looking into)
- removed `set -u` from our scripts around android, this causes hard fails for unbounded vars and apparently there is one in rvm in the ruby orb

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.
#nochangelog

### CODE REVIEW

**Review by dimatretyak — DISMISSED** [review]

**Comment by dimatretyak** [comment]
oops, can't apply patch locally

image

**Comment by gkartalis** [comment]
because theoretically you don't need to apply the package locally 🤔 running `yarn install:all` should automatically apply it for you

**Comment by dimatretyak** [comment]
> @dimatretyak what if you do `rm -rf node_modules` first and then just run `yarn install:all`

this time I didn't face this problem when applying the patch after I initially made `rm -rf node_modules`

**Comment by gkartalis** [comment]
amazing! Thanks for the confirmation! Will ping people at #practice-mobile to run `rm -rf node_modules` first

**Pull request merged**
