### PR TITLE
Added dude in vertical view, closes #1294.

### LINKED ISSUE #1294: Add dude view to portrait
@orta says that the reason why we don't have the dude in the vertical view is because it didn't fit on an iPhone 4. Times have changed. What about showing the dude in the view on portrait too?

screen shot 2016-03-17 at 4 32 21 pm

I am happy to PR this. What do you think @katarinabatina?

### PR DESCRIPTION
**Pull request by dblock**
This is someone's favorite feature.

dude

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">1 Warning</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td>Needs testing on a Phone if change is non-trivial</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
Fixed alignment too:

screen shot 2016-03-17 at 19 00 06

**Comment by orta** [comment]
Tested this on my iPhone 6 :+1:

**Comment by orta** [comment]
OK, I used this to fix an annoyance - @ericallam I'm finally living up to your [2014 talk at UIKonf](https://youtu.be/44-2vmqQBl0)

**Comment by ashfurrow** [comment]
:tada:

**Comment by orta** [comment]
double checked it, it's cool:

**Pull request merged**
