### PR TITLE
@1aurabrown => Update collection view to ensure artworks don’t stick out at wrong end.

### LINKED ISSUE #301: other works in show, etc. not formatting correctly on ipad
second row should start on the left,

image

### PR DESCRIPTION
**Pull request by alloy**
Updated to ARCollectionViewMasonryLayout 2.1.x.

Fixes #301.

Here’s an example of a case where previously the trailing artwork would have been added to the right-most column:

ios simulator screen shot 23 apr 2015 17 56 37

### CODE REVIEW

**Comment by alloy** [comment]
Seeing as you’re all gone for lunch and @orta wanted me to do a beta release, I’ll be merging this myself.

**Comment by alloy** [comment]
You know what, I forgot to CHANGELOG that :sob:

**Comment by orta** [comment]
haha

**Comment by 1aurabrown** [comment]
@alloy sorry, this slipped under my radar. is it possible to add tests with different image sizes so that snapshots can show what's really going on?

**Comment by alloy** [comment]
@1aurabrown Good point, I’ll do that :+1:

**Pull request merged**
