### PR TITLE
Refine settings reflects current number of lots

### PR DESCRIPTION
**Pull request by ashfurrow**

### CODE REVIEW

**Comment by alloy** [comment]
LGTM :+1: 

Will merge on :green_heart:

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">1 Error</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:no_entry_sign:</td>
      <td>There were <a href="https://eigen-ci.s3.amazonaws.com/1947/index.html">snapshot errors</a></td>
    </tr>
    
  </tbody>
</table>
  

  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by alloy** [comment]
The branch build passed, what gives? :/ https://circleci.com/gh/artsy/eigen/1946

**Comment by orta** [comment]
Weird, I mean it obv uploaded something, maybe there's some `will` tests?

**Comment by ashfurrow** [comment]
Could be related to how I pushed (did an amended commit with a changelog entry, and force-pushed. Maybe have confused Circle).

**Comment by ashfurrow** [comment]
Looks like the generated snapshots might actually be wrong (did it on my MacBook, not my usual dev machine ¯\\_(ツ)_/¯).

**Comment by ashfurrow** [comment]
:green_apple:

**Pull request merged**
