### PR TITLE
chore: remove unmock relay followup

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [] 

### Description

removes all `jest.unmock\("react-relay"\)` references from eigen.
Used Find and Replace regex `jest.unmock\("react-relay"\)(\r?\n|\n)` in vscode on find and empty replace string 

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#nochangelog

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by pvinis — APPROVED** [review]
nice

**Comment by pvinis** [comment]
feel free to merge on green

**Comment by gkartalis** [comment]
@pvinis there were some errors on the recommit hook though coming from eslint?? Did we add eslint there? had to push with `--no-verify`

**Comment by pvinis** [comment]
what kind of errors? cc @damassi

**Comment by gkartalis** [comment]
`  13:20  error  React Hook "useTracking" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks`

something like this coming from some tests, it wasn't complaining before

**Comment by gkartalis** [comment]
also detect-secrets failing 🤔

**Comment by pvinis** [comment]
I had that yesterday. I think there's a new version. I can take a look in a few min 👍

**Comment by gkartalis** [comment]
You can repro like this:
`➜ yarn lint eigen/src/app/Components/Artist/ArtistInsights/ArtistInsights.tests.tsx`
from what I understand we added `yarn lint` with eslint on the pre-commit hook for the staged files and this causes this. also when I open the file in VScode I see 🔴 underlining the line.

No stress just reporting :)

**Comment by gkartalis** [comment]
tests are passing 💚

**Comment by pvinis** [comment]
can you rebase on top of https://github.com/artsy/eigen/pull/8049 (or main once this is merged) to see the versions of detect-secrets?

**Comment by pvinis** [comment]
also, i pushed a pr for the eslint thing. correct report.

**Review by pvinis — APPROVED** [review]

**Comment by gkartalis** [comment]
@pvinis thanks! Although the linting issue is that this check didn't happen before and now it breaks so many files (the one that I sent was one of many examples) 

Whenever a dev touches something they will have to run `--no-verify` due to the `yarn lint` eslint change 🤔 do you think we can avoid that?

**Comment by pvinis** [comment]
going to slack

**Pull request merged**
