### PR TITLE
feat[swa-271] make SubmitArtworkOverview the standard flow

### PR DESCRIPTION
**Pull request by patrinoua**
The type of this PR is: **feat**

[SWA-271] 
Make SubmitArtworkOverview the standard flow

Echo PR https://github.com/artsy/echo/pull/210
docs https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md

For follow up things to do, please check [SWA-270] 

This PR resolves []

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

ⓘ 'User-facing' changes will be published as release notes.

#### Cross-platform user-facing changes

- Rename modal title - patrinoua

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[SWA-270]: https://artsyproduct.atlassian.net/browse/SWA-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SWA-271]: https://artsyproduct.atlassian.net/browse/SWA-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Rename modal title - patrinoua)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7e28ce74405b525510cabb0c7e666c4079aea4be
</p>

**Review by AlicanAkyuz — CHANGES_REQUESTED** [review]
I think we should work with the feature flag instead of modifying the component in order to release the feature. his will help us revert it, if something goes wrong in production. 

You can follow _Releasing a feature_ section here in this doc: https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md  

Basically, we want to change the flag to true in `features.ts`:
```
AREnableAccordionNavigationOnSubmitArtwork: {
    readyForRelease: true,
    description: "Enable New Artwork Submission Flow with Accordion",
    showInAdminMenu: true,
},
```

and in Echo, make a change like this: https://github.com/artsy/echo/pull/70/files by adding `{ name: 'AREnableAccordionNavigationOnSubmitArtwork', value: true },`

**Comment by patrinoua** [comment]
Thank you @AlicanAkyuz 🙏 I've updated the PR can you maybe have another look?

**Review by AlicanAkyuz — APPROVED** [review]
looks good, thanks for making the changes 🙏  

the error on the CI is because we haven't merged the PR in Echo yet. it should be fine once we do that. 

let's wait to merge this and Echo PR, until after the current release launches and we QA everything in the test app 🤞

**Comment by pvinis** [comment]
all good with the release. it was cut from main a few commits back, so no worries. we can merge when we want.

in general, main should be pretty much unblocked from releases. we can merge stuff to main whenever we want. what we are trying now is to cut a release from main (which means making a new branch from main), and only adding hotfixes etc on there, so we should be very much unblocked from main and releases 👍

**Comment by AlicanAkyuz** [comment]
@pvinis we are still unsure if we want to release this in the next release as we are still working on some bugs/improvements. does it still make sense to merge now?

**Comment by pvinis** [comment]
ah gotcha, you mean next release. I would suggest (if possible) to put things behind a flag. that way we can merge and not have it released/visible to users. if a flag wouldn't work, then holding the PR is ok, but it's the harder option I feel like.

**Comment by AlicanAkyuz** [comment]
understood, thank you. since this is removing a flag already, it looks like keeping it on hold is the only option.

**Comment by pvinis** [comment]
oh, and I just checked the changes, and it's actually the flag! 😅

if we are not sure we will be releasing this, we have some options:
- close the PR and open it when we are sure
- keep the PR until we are sure
- connect that flag to echo, turn the flag in echo to false, them merge this PR here. this way we control the release from echo.

up to you and your team :)

**Comment by AlicanAkyuz** [comment]
I'd say let's keep it on hold as-is if there aren't other opinions. in the next couple of days it'll be clearer if we want to release this in the next release.

**Comment by patrinoua** [comment]
Replaced by https://github.com/artsy/eigen/pull/6399

**Comment by patrinoua** [comment]
Replaced by https://github.com/artsy/eigen/pull/6399

**Pull request closed without merging**
