### PR TITLE
refactor(perf): boost performance by wrapping renderitem usecallback

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [] 

### Description

Moved all the renderItem from `Tabs.Masonry` to a `useCallback` in order to take advantage of slightly improved performance.

Read more [here](https://www.mukesh-jangid.com/post/optimize-flatlist-with-the-power-of-usememo-and-usecallback)

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- boost tabs.masonry performance by wrapping renderitem in usecallback - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by MrSltun — APPROVED** [review]
Great work! 🌟🌟🌟

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (boost tabs.masonry performance by wrapping renderitem in usecallback - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0024f72f670c1edee34ecba06f046bfcf9722b17
</p>

**Review by brainbicycle — APPROVED** [review]
nice ⚡

**Review by MounirDhahri — DISMISSED** [review]
LGTM - Do you mind if you export `renderItem` to a standalone function? it looks like it's the same function everywhere so it might be worth it to move it somewhere shared

**Comment by gkartalis** [comment]
> LGTM - Do you mind if you export renderItem to a standalone function? it looks like it's the same function everywhere so it might be worth it to move it somewhere shared

Good point, will have a look if it is possible (there are some differences here and there)

**Review by araujobarret — DISMISSED** [review]
I have a fear of exporting this function because it relies on an `item` which is a generic type that can cause more headaches than helping out If an item in the future uses a different shape.
I'm in favor of keeping the duplication 👍

**Pull request merged**
