### PR TITLE
Use newer API routes for genes

### PR DESCRIPTION
**Pull request by orta**
Updates signing profiles: When I added myself as an individual developer it required updating the certs

Still hooked up good.
screen shot 2016-01-15 at 13 30 56

I verified that the Gene artworks is the same as the app store build.

### CODE REVIEW

**Comment by alloy** [comment]
There shouldn’t be a need for any of those code-signing changes nor for a specific development provisioning profile. Can you revert those and see if it doesn’t just work and otherwise what it’s complaining about?

**Comment by alloy** [comment]
Is this route deprecated in the sense that it will still work for older app versions?

**Comment by orta** [comment]
Nah, it's deprecated in the sense platform want to get rid of it, and while we are not the only consumer of the API, we will be the longest lasting one. Given that it would break all gene pages for all past clients, it's not something that can just happen easily.

**Comment by alloy** [comment]
:+1:

**Comment by orta** [comment]
OK, this is now a focus'd PR :+1:

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Error
    ------------- | ------------
        :no_entry_sign: | No CHANGELOG changes made
    

  

  
    &nbsp; | 1 Warning
    ------------- | ------------
        :warning: | Needs testing on a Phone if change is non-trivial
    

  

  


<p align="right" meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/KrauseFx/danger/">danger</a>
</p>

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Warning
    ------------- | ------------
        :warning: | Needs testing on a Phone if change is non-trivial
    

  

  


<p align="right" meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/KrauseFx/danger/">danger</a>
</p>

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Warning
    ------------- | ------------
        :warning: | Needs testing on a Phone if change is non-trivial
    

  

  


<p align="right" meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/KrauseFx/danger/">danger</a>
</p>

**Comment by orta** [comment]
Not sure if  `5 additions and 6 deletions.` counts as non-trivial. FWIW Danger

**Pull request merged**
