### PR TITLE
@alloy => update provisioning

### PR DESCRIPTION
**Pull request by jorystiefel**
Switches to correct iOS Artsy dev profile which includes my devices. See screenshot, still using `net.artsy.artsy.dev`

screenshot 2015-08-25 11 31 43

### CODE REVIEW

**Comment by orta** [comment]
we should still be using the custom one, @alloy we should really move to a _custom named_ profile, as this shares a name with one auto generated by Xcode

**Comment by alloy** [comment]
Good point.

@jorystiefel Did you edit the one from the provisioning profile or did Xcode create this?

**Comment by jorystiefel** [comment]
@alloy I just refreshed my account in Xcode and then selected net.artsy.artsy.dev

**Comment by alloy** [comment]
@jorystiefel I renamed the manually maintained profile to ‘Eigen Development Profile’ and selected that to be used in https://github.com/artsy/eigen/commit/f8bf9c5a92550ede1024d408a27aa141c7e6478c

**Pull request closed without merging**
