### PR TITLE
[Gene] Handle creating Gene Refinement setting objects to and from JSON

### PR DESCRIPTION
**Pull request by orta**
This should handle the communication between the refine VC in Swift, and our JS - allowing us to send data from our refine allocations in graphQL to the RefineGeneSettings in Eigen and back.

side note: in retrospect, I should have outright re-created this view controller in JS. This JSON comms method alone is more complex and harder to maintain over the long run than a separate implementation of the view controller. Too late now, but I'll probably be doing less of this sort of thing in the future.

### CODE REVIEW

**Comment by orta** [comment]
Maxim's already got one PR assigned

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG changes made</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |285.8ms | [AuctionViewController.swift](/artsy/eigen/tree/orta-gene_refine/Artsy/View_Controllers/Auction/AuctionViewController.swift#L199) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
251.9ms | [SwiftyJSON.swift](/artsy/eigen/tree/orta-gene_refine/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
176.6ms | [WebSocket.swift](/artsy/eigen/tree/orta-gene_refine/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
98.6ms | [Observable.swift](/artsy/eigen/tree/orta-gene_refine/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
94.0ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/orta-gene_refine/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
93.1ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/orta-gene_refine/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L47) | @objc override func viewDidLoad()
74.2ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/orta-gene_refine/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
68.6ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-gene_refine/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
66.5ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-gene_refine/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by alloy** [comment]
Looks good to me. I’m holding off from merging until the beta is out, as this doesn’t need to be in anyways.

**Comment by alloy** [comment]
Merging ✨

**Pull request merged**
