### PR TITLE
feat: add lottie

### PR DESCRIPTION
**Pull request by MounirDhahri**
### Description

This PR adds Lottie to the app

| Animation | Video |
| --- | --- |
| Watch lot  | https://user-images.githubusercontent.com/11945712/173563064-c017c34d-ccea-478e-ad0f-303dbb76070a.mov |

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [x] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by admbtlr** [comment]
Shouldn't we have an RFC before adding something like Lottie?

**Comment by MounirDhahri** [comment]
Hey @admbtlr yes for sure. I created this PR a while ago after the conversation [here](https://artsy.slack.com/archives/C02BAQ5K7/p1652099026950109) and wanted to try out if Lottie would work by default in Eigen and evaluate how much effort it would take to add some animations.

**Comment by MounirDhahri** [comment]
This PR will probably remain as a draft for while and hopefully at the next hackathon/refinathon I can get back to it and share the results with the rest of the team

**Comment by MounirDhahri** [comment]
Closing this PR for inactivity, please feel free to reopen it if it's still a work in progress.

**Pull request closed without merging**
