### PR TITLE
fix: SWA top navigation bar height jumps

### PR DESCRIPTION
**Pull request by olerichter00**
### Description

This fixes the SWA top navigation bar height jumps by fixing the height of the text above the progress bar.

## Jumping top navigation 🔴 

https://github.com/artsy/eigen/assets/4691889/1a09691e-34fa-4f12-adfb-7f3668ae5c3f

## Top navigation with fixed height 🟢 

Simulator Screenshot - iPhone 15 Pro - 2024-06-05 at 12 01 46

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Fix SWA top navigation bar height jumps (behind ff) - ole

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f432ae62f9a6cd9850ccf832feae353005477e9f
</p>

**Comment by MounirDhahri** [comment]
You can check my changes here https://github.com/artsy/eigen/pull/10336/commits/fc4399000a67e762253a9ea825bfb7c9cdea8d23 - I figured out it's time to have everything defined all together instead of the old way which made `LayoutAnimation` confused

**Comment by olerichter00** [comment]
> You can check my changes here https://github.com/artsy/eigen/commit/fc4399000a67e762253a9ea825bfb7c9cdea8d23 - I figured out it's time to have everything defined all together instead of the old way which made LayoutAnimation confused

Will this fix the jumping progress bar? Could you create a PR? Then we can close this one and merge your fixes.

**Comment by MounirDhahri** [comment]
Yes, this should fix it. The commit is part of this PR https://github.com/artsy/eigen/pull/10336

**Pull request closed without merging**
