### PR TITLE
@orta => [Fair Map] Allow for more textual content on callout.

### LINKED ISSUE #127: [Fair map] Some annotations get a small chevron in callout
fair artist - callout small chevron

### PR DESCRIPTION
**Pull request by alloy**
For examples see https://github.com/artsy/eigen/issues/127#issuecomment-73930642

* Decrease font sizes to 14 and 11 points.
* Decrease horizontal margins around views on right side.
* Always show arrow chevron at native size.

Fixes #127.

### CODE REVIEW

**Comment by orta** [comment]
Code looks :+1: 
Good for merge

**Comment by alloy** [comment]
This is green locally.

**Comment by orta** [comment]
:+1: Looks great

**Comment by orta** [comment]
but needs a rebase

**Comment by alloy** [comment]
@orta did done it!

**Comment by orta** [comment]
Awesome.

**Pull request merged**
