### PR TITLE
Fixes crashes in live interface #trivial

### LINKED ISSUE #1969: Fix crash in Artsy.LiveAuctionToolbarView.(setupUsingState (Artsy.LotState) -> ()).(closure #1).(closure #1), line 73
### Stacktrace ###

<pre>-;Artsy.LiveAuctionToolbarView.(setupUsingState (Artsy.LotState) -> ()).(closure #1).(closure #1);LiveAuctionToolbarView.swift;73
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Artsy.LiveAuctionLotViewModel.addEvents ([__ObjC.LiveEvent]) -> ();LiveAuctionLotViewModel.swift;330
-;Artsy.LiveAuctionLotViewModel.addEvents ([__ObjC.LiveEvent]) -> ();LiveAuctionLotViewModel.swift;313
-;function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed, Arg[2] = Dead and Owned To Guaranteed> of Artsy.LiveAuctionStateReconciler.(updateLotWithEvents in _825FD3FE24083D900CBB43391B945B5D) (Artsy.LiveAuctionLotViewModel, lotEvents : [[Swift.String : Swift.AnyObject]], fullEventOrder : [Swift.String]?) -> ();LiveActionStateReconciler.swift;158
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Artsy.LiveAuctionStateReconciler.updateState (Swift.AnyObject) -> ();LiveActionStateReconciler.swift;69
-;@objc Artsy.LiveAuctionStateReconciler.updateState (Swift.AnyObject) -> ();LiveActionStateReconciler.swift;0
-;protocol witness for Artsy.LiveAuctionStateReconcilerType.updateState (Swift.AnyObject) -> () in conformance Artsy.LiveAuctionStateReconciler : Artsy.LiveAuctionStateReconcilerType in Artsy;LiveActionStateReconciler.swift;56
-;Artsy.LiveAuctionStateManager.(init (host : Swift.String, sale : __ObjC.LiveSale, saleArtworks : [Artsy.LiveAuctionLotViewModel], jwt : Artsy.JWT, bidderCredentials : Artsy.BiddingCredentials, socketCommunicatorCreator : (host : Swift.String, causalitySaleID : Swift.String, jwt : Artsy.JWT) -> Artsy.LiveAuctionSocketCommunicatorType, stateReconcilerCreator : (saleArtworks : [Artsy.LiveAuctionLotViewModel]) -> Artsy.LiveAuctionStateReconcilerType) -> Artsy.LiveAuctionStateManager).(closure #1);LiveAuctionStateManager.swift;52
-;partial apply forwarder for Artsy.LiveAuctionSocketCommunicator.(receivedText in _2FBDEE69475B63219A7CE1A35D4FCE4A) (Swift.String) -> ();LiveAuctionSocketCommunicator.swift;131
-;partial apply forwarder for Artsy.(applyUnowned <A, B, C where A: Swift.AnyObject> (A, (A) -> (B) -> C) -> (B) -> C).(closure #1);SwiftExtensions.swift;13</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/142084155](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/142084155)

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes #1969.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |276.3ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-crash-fixes/Artsy/View_Controllers/Auction/AuctionViewController.swift#L199) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
243.4ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-crash-fixes/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
207.0ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-crash-fixes/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
100.8ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-crash-fixes/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
93.0ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/ashfurrow-crash-fixes/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L47) | @objc override func viewDidLoad()
83.9ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-crash-fixes/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
82.6ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-crash-fixes/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
71.5ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-crash-fixes/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
69.4ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-crash-fixes/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)


### Tests: 

Classname | Name|
--- | ---|
ARSwitchBoardSpec | test_ARSwitchboard__routeInternalURL__routes_genes|
ARTopMenuViewControllerSpec | test_navigation__feed__tab_behavior__when_presenting_a_root_view_controller__when_already_on_the_selected_tab__animates_popping|
ARTopMenuViewControllerSpec | test_navigation__feed__tab_behavior__when_presenting_a_root_view_controller__when_already_on_the_selected_tab__does_not_change_tab|
ARTopMenuViewControllerSpec | test_navigation__browse__tab_behavior__when_presenting_a_root_view_controller__when_already_on_the_selected_tab__animates_popping|
ARTopMenuViewControllerSpec | test_navigation__browse__tab_behavior__when_presenting_a_root_view_controller__when_already_on_the_selected_tab__does_not_change_tab|
ARTopMenuViewControllerSpec | test_navigation__browse__tab_behavior__when_presenting_a_root_view_controller__when_not_on_the_selected_tab__changes_tabs_in_an_animated_fashion|
ARTopMenuViewControllerSpec | test_navigation__favorites__logged_in__tab_behavior__when_presenting_a_root_view_controller__when_already_on_the_selected_tab__animates_popping|
ARTopMenuViewControllerSpec | test_navigation__favorites__logged_in__tab_behavior__when_presenting_a_root_view_controller__when_already_on_the_selected_tab__does_not_change_tab|
ARTopMenuViewControllerSpec | test_navigation__favorites__logged_in__tab_behavior__when_presenting_a_root_view_controller__when_not_on_the_selected_tab__changes_tabs_in_an_animated_fashion|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by orta** [comment]
FWIW, I'd argue that a crash fix _is_ worth a changelog entry

**Comment by ashfurrow** [comment]
Yeah, makes sense 👍 I'll wait for #1975 to get merged in and then update this PR.

**Comment by orta** [comment]
awesomebeans

**Comment by orta** [comment]
Rock

**Pull request merged**
