### PR TITLE
@alloy => Fixes white screen presented after cancelled twitter login 🚫📱

### LINKED ISSUE #143: Aborting Twitter/Facebook login leaves me on white screen with spinner.
1. Login
2. Select Twitter/Facebook
3. Get thrown out to web browser
4. Think "ah, can't be bothered" and go back to app

image

### PR DESCRIPTION
**Pull request by ashfurrow**
See discussion on the issue for more details. 

Fixes #143.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Note: a more robust version would maintain state for both twitter/facebook and show the error when it became active. However, I don't really like showing errors for things users cancelled, so.

**Comment by alloy** [comment]
@ashfurrow I would argue that it’s not even an error. It’s a totally expectable cancellation action.

**Comment by ashfurrow** [comment]
Totally, though I should note that Facebook does currently treat cancels as errors.

**Comment by alloy** [comment]
Then that’s a UX bug imo.

**Comment by alloy** [comment]
Ouch, this change misses a CHANGELOG. Can you write one up and post it here? I’ll add it.

**Comment by ashfurrow** [comment]
I can open an issue if you like.

**Comment by ashfurrow** [comment]
Oops, yes it does sorry.

**Comment by alloy** [comment]
> I can open an issue if you like.

:+1:

**Pull request merged**
