### PR TITLE
chore(FX-3706): mark AREnableImprovedAlertsFlow to readyForRelease

### PR DESCRIPTION
**Pull request by gkartalis**
The type of this PR is: **Feature**

This PR resolves [FX-3706]

### Description

Marks AREnableImprovedAlertsFlow ready for release

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- mark AREnableImprovedAlertsFlow readyForRelease - gkartalis

</details>

[FX-3706]: https://artsyproduct.atlassian.net/browse/FX-3706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dimatretyak — APPROVED** [review]
LGTM 👍

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (mark AREnableImprovedAlertsFlow readyForRelease - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b16afe41390ea52d66cf3c2b10a2d0be08b90d68
</p>

**Comment by gkartalis** [comment]
Tests were failing because of [this unused variable](https://github.com/artsy/eigen/pull/6111/files#diff-711500e0a24b1933f2661d17ecef6a7f95dc64efda954f07f2917d9116211ce0R27). Removed it and re-running the checks

**Comment by gkartalis** [comment]
#squashOnGreen

**Pull request merged**
