### PR TITLE
build(deps): remove @react-native-camera-roll/camera-roll

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [] 

### Description

- Removes `@react-native-camera-roll/camera-roll` unused dependency.
- Also adds a comment on a react-native-dev-menu-android that is used but looks like it is not.

Used https://github.com/depcheck/depcheck to find unused packages by running `yarn global add depcheck && npx depcheck`and the output was something like this:

```sh
* @react-native-community/cameraroll
* @sentry/cli
* deprecated-react-native-prop-types
* events
* grapheme-splitter
* jsc-android
* react-native-dev-menu-android
* tsutils
* url
```

Didn't proceed with the rest because some of them are used for other purposes like:

- `@sentry/cli` - used in fastlane setup
- `deprecated-react-native-prop-types` - used for some patches for react native and deprecated deps
- `events` - used from navigation (maybe we could remove it and use the react native events?)
- `jsc-android` - used for android specific stuff (might be possible to remove it now that we use Hermes?)
- `react-native-dev-menu-android` - added a comment on the why on `dependency comments` section of package json
- `url` - used for parse url function (seems to be deprecated maybe we need to remove it and replace it with another up to date?)
- `grapheme-splitter` - not quite sure why we have it  

⚠️ Tested out the camera functionality in the android / iOS platforms to make sure I didn't break anything, let me know if I am missing something! 

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- remove @react-native-camera-roll/camera-roll and tsutils - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (remove @react-native-camera-roll/camera-roll and tsutils - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2401c008533824e2acb275da079cdfc3e2ddfbee
</p>

**Review by araujobarret — APPROVED** [review]
LGTM 👍 

About `@sentry/cli` being used in Fastlane, can't we use `npx` and avoid the necessity of having it here?

**Comment by araujobarret** [comment]
Let's not forget to include a test scenario for the QA next week 🎗️

**Comment by gkartalis** [comment]
> About @sentry/cli being used in Fastlane, can't we use npx and avoid the necessity of having it here?
good point will make a ticket for this

**Pull request merged**
