### PR TITLE
fix(APPLAUSE-6697021): auth2 back button double tap crash

### PR DESCRIPTION
**Pull request by iskounen**
This PR fixes a bug where double-tapping the back button on the password step of the auth flow crashes the app.

This happens because tapping back "pops" the last screen from a list of previous screens and sets it as the current screen, but we do not guard that operation against an empty list of previous screens. This PR solves that by not allowing the user to double-tap past the first screen in the auth flow.

| BEFORE | AFTER |
|----------|-------|
| https://github.com/user-attachments/assets/8c08b24b-3d74-4767-92ca-43ac2f9f9d87 | https://github.com/user-attachments/assets/93f22d74-58d0-40ec-aa0d-85c5a5674550 |

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Fixed a bug that could cause the authentication flow to crash

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Fixed a bug that could cause the authentication flow to crash - iskounen)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 318da2a2744e0d4ef1ebeb0aa5ac0ba173647bd0
</p>

**Review by MounirDhahri — DISMISSED** [review]
Thanks for this addition. Another approach would have been to `debounce` the back button

**Review by MrSltun — DISMISSED** [review]
Niiice!!

**Comment by MounirDhahri** [comment]
Cool - sure @araujobarret. It's not a blocker for sure. It's something we already in `navigate` and it's only perceived if you tap multiple times in a row.

**Comment by iskounen** [comment]
> I can perceive 100ms honestly 😂

thesixmilliondollarman

**Pull request merged**
