### PR TITLE
fix: dont require React import

### PR DESCRIPTION
**Pull request by pvinis**
This PR resolves []

### Description

Hitting cmd-. on VSCode will not offer importing react anymore. it will instead import the right thing.

- removed unused react imports
- removed tests that weren't running inside palette (Box, Join, Collapse)
- removed unused mock

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by gkartalis — DISMISSED** [review]
👏 Woohooooooo 🤘

**Review by brainbicycle — APPROVED** [review]
nice!

**Comment by pvinis** [comment]
huh, weird.. this makes the regular import react a type error. i can try and make tslint ignore that, or i can remove it from all our files 😬. Ill go for the first.

**Comment by brainbicycle** [comment]
> unfortunately the only way for this is to disable `noUnusedLocals` in `tsconfig`. I would rather not, I would prefer to just remove all imports. Do people mind if I do that in this PR as well?



> unfortunately the only way for this is to disable `noUnusedLocals` in `tsconfig`. I would rather not, I would prefer to just remove all imports. Do people mind if I do that in this PR as well?

that is just removing existing React imports? think it is ok to include in this PR

**Comment by brainbicycle** [comment]
> unfortunately the only way for this is to disable `noUnusedLocals` in `tsconfig`. I would rather not, I would prefer to just remove all imports. Do people mind if I do that in this PR as well?



> unfortunately the only way for this is to disable `noUnusedLocals` in `tsconfig`. I would rather not, I would prefer to just remove all imports. Do people mind if I do that in this PR as well?

that is just removing existing React imports? think it is ok to include in this PR

**Comment by pvinis** [comment]
exactly. it's a bit annoying because the PR will have 300 files changed, but yea, just removing react imports. I can do that next week.

**Comment by patrinoua** [comment]
This could also be a refinathon thing 🙌🏻

**Comment by pvinis** [comment]
911 files. cool :D

**Review by gkartalis — APPROVED** [review]

**Pull request merged**
