### PR TITLE
New loading indicator & Bid Button Styles

### PR DESCRIPTION
**Pull request by ashfurrow**
New loading indicator for the live auction which waits until the initial causality sale state has been received before showing the user a complete interface. 

Here's the loading view on iPhone:

screen shot 2016-06-16 at 3 21 50 pm

And on iPad in both orientations:

screen shot 2016-06-16 at 3 23 12 pm
screen shot 2016-06-16 at 3 23 07 pm

Re: #1633. /cc @katarinabatina

### CODE REVIEW

**Comment by katarinabatina** [comment]
realizing it might make more sense to say "entering the auction room" but if making the copy change is a pain this looks good 👍

**Comment by ashfurrow** [comment]
No problem at all, I'll make the change and update this PR.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |238.5ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Artsy/View_Controllers/Auction/AuctionViewController.swift#L183) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
199.1ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
172.3ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
77.0ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
70.3ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
70.2ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
63.3ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
62.0ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L49) | @objc override func viewDidLoad()
61.3ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
58.4ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/ashfurrow-loading-indicator/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
🍏

**Comment by ashfurrow** [comment]
🍏

**Comment by acjay** [comment]
Looks great to me!

**Pull request merged**
