### PR TITLE
Update Danger, make the Dangerfile use the new scoped syntax #trivial

### PR DESCRIPTION
**Pull request by orta**
This is one of the front-page Dangerfiles on danger.systems - so I've made sure it makes more sense.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG changes made</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |250.4ms | [AuctionViewController.swift](/artsy/eigen/tree/orta-dm_update/Artsy/View_Controllers/Auction/AuctionViewController.swift#L183) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
219.9ms | [SwiftyJSON.swift](/artsy/eigen/tree/orta-dm_update/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
172.1ms | [WebSocket.swift](/artsy/eigen/tree/orta-dm_update/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
81.2ms | [Observable.swift](/artsy/eigen/tree/orta-dm_update/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
73.4ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/orta-dm_update/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
72.8ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/orta-dm_update/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
65.8ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/orta-dm_update/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L49) | @objc override func viewDidLoad()
64.4ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-dm_update/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
62.3ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-dm_update/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
60.1ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/orta-dm_update/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView






<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by orta** [comment]
screen shot 2016-07-18 at 10 57 51 am


screen shot 2016-07-18 at 10 58 13 am

Merging for now.

**Comment by alloy** [comment]
https://github.com/dependencyci/dotyaml/issues/2

**Comment by orta** [comment]
Thanks

**Comment by andrew** [comment]
@orta @alloy should be fixed now, docs on how to use `dependencyci.yml` here: https://dependencyci.com/docs#dependencyciyml

**Pull request merged**
