### PR TITLE
Adds admin ability to view echo configuration.

### PR DESCRIPTION
**Pull request by ashfurrow**
Looks like this:

simulator screen shot dec 6 2016 1 56 36 pm
simulator screen shot dec 6 2016 1 54 54 pm

Related to https://github.com/artsy/auctions/issues/262.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Added a last-updated label too:

screen shot 2016-12-06 at 2 26 57 pm

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by alloy** [comment]
Nice stuff 👌 Is there a specific use case this was created for?

**Comment by ashfurrow** [comment]
Aye, I'm investigating in https://github.com/artsy/auctions/issues/262 why a change in echo config isn't being reflect in App Store builds when relaunched. Any suggestions would be welcome!

**Comment by orta** [comment]
tsk tsk - doesn't even use my fancy admin Garamond styling

**Comment by orta** [comment]
👍

**Pull request merged**
