### PR TITLE
[blocked] Update Gene to use the new ARGeneComponentVC

### PR DESCRIPTION
**Pull request by orta**
This switches the default to on, and uses echo to support turning it off.

### CODE REVIEW

**Comment by orta** [comment]
Relies on a n Emission deploy and https://github.com/artsy/emission/pull/362

**Comment by alloy** [comment]
Tapping the REFINE button [won’t do anything yet](https://github.com/artsy/eigen/blob/3703dee2ccf15548f0010e2c53a9e95e8660daaf/Artsy/App/ARAppDelegate+Emission.m#L147-L150), though, and I’m not entirely sure right now how it needs to be hooked-up.

**Comment by alloy** [comment]
Oh, judging by the current state of Emission, it seems like the REFINE button is just not available at all? i.e. you decided to not make that work for now?

**Comment by orta** [comment]
There's no refine button in the UI for this run

**Pull request merged**
