### PR TITLE
feat: Add isEdition boolean to MyCollection artwork checkbox

### PR DESCRIPTION
**Pull request by annacarey**
The type of this PR is: **Bugfix**

This PR resolves [CX-915]

### Description

This PR allows users to check the checkbox in the artwork from in MyCollection to indicate if the work is an edition without filling in additional information. (Previously you needed to mark editionNumber for the checkbox to be checked.) Now we are using an isEdition field from Metaphysics. The Metaphysics ticket adding the field is [here](https://github.com/artsy/metaphysics/pull/2915/commits/dc5f20e20c0b7c6e839b42caae88c9630fa6b158). 

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

[CX-434]: https://artsyproduct.atlassian.net/browse/CX-434
[CX-915]: https://artsyproduct.atlassian.net/browse/CX-915

### CODE REVIEW

**Review by brainbicycle — APPROVED** [review]
🙌

**Review by MounirDhahri — APPROVED** [review]

**Comment by MounirDhahri** [comment]
Thanks Anna 🙌, Thanks Brian for the review 🙏.

**Comment by MounirDhahri** [comment]
#squashongreen

**Comment by annacarey** [comment]
@MounirDhahri thanks for closing this out! i feel like #mergeongreen hasn't been working on my PRs maybe?

**Comment by MounirDhahri** [comment]
hmmm it could be that the bot only added the label after it was already green. I will merge the PR manually then 😀

**Pull request merged**
