### PR TITLE
feat(CX-3516): SWA Lp updates part 2

### PR DESCRIPTION
**Pull request by lordkiz**
This PR resolves [CX-3516] 

### Description
- Updates copy and addresses the QA issues

[swa-lp-2a.webm](https://user-images.githubusercontent.com/18648835/224954972-d09c4857-50bc-47cc-9e49-e00a1676e847.webm)

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- SWA Lp updates part 2 - kizito

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-3516]: https://artsyproduct.atlassian.net/browse/CX-3516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dariakoko** [comment]
This image looks cropped. Is it?
image

**Review by dariakoko — DISMISSED** [review]
Looks good to me.
I only left a couple of comments

**Comment by lordkiz** [comment]
> This image looks cropped. Is it? image

@dariakoko it uses resizeMode: `cover`. It is not possible to `contain` these images without having extra spaces around them.

**Comment by dariakoko** [comment]
@lordkiz but if you crop the image it doesn't align with the design. Would you like to jump on a call and adjust it together?

**Comment by lordkiz** [comment]
> @lordkiz but if you crop the image it doesn't align with the design. Would you like to jump on a call and adjust it together?

Sure

**Comment by lordkiz** [comment]
Merging this so it can be QA'd early

**Pull request merged**
