### PR TITLE
chore(ONYX-570): remove alert name from alert flow

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR resolves [ONYX-570] 

This PR removes the alert name from the alert flow (both edit and create)

### Description
Group 2

### Placeholder on Edit Screen

https://github.com/artsy/eigen/assets/11945712/51a10cb4-222d-471b-989b-182961466abe

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Remove alert name from Create Alert and Edit Alert flows - mounir

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-570]: https://artsyproduct.atlassian.net/browse/ONYX-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Remove alert name from Create Alert and Edit Alert flows - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9f2cb9ba6b17b46d7561a98b79ce8c25b3d834d4
</p>

**Review by olerichter00 — DISMISSED** [review]
🌟

**Comment by MounirDhahri** [comment]
Oh nooooo merge conflict in the massive test 😭

**Comment by MounirDhahri** [comment]
🚀 🚀 🚀

**Pull request merged**
