### PR TITLE
fix: Update webview progress bar

### PR DESCRIPTION
**Pull request by MrSltun**
This PR related to [EMI-1396] 

### Description

This PR removes the custom progress bar we have since it doesn't work properly on Android, and the new version of `react-native-webview` package includes a progress bar that works on both platforms

>[!NOTE]
> The progress bar doesn't show up on the first load, which doesn't appear when we go to webview version of articles (check the videos)

### Videos
| Screen (Platform) | Before | After |
|---|---|---|
| Checkout flow (Android) | <video src="https://github.com/artsy/eigen/assets/20655703/fa7f2fe3-bb21-4800-87f9-43ff84ee2748" /> | <video src="https://github.com/artsy/eigen/assets/20655703/6d9941e8-b81c-496c-8605-f9099592c78f" /> |
| Chekout flow (iOS) | <video src="https://github.com/artsy/eigen/assets/20655703/215463d9-c48b-4ecb-ab4d-cd1f31500b2a" /> | <video src="https://github.com/artsy/eigen/assets/20655703/b917d032-c6f5-4143-900c-107f28005015" /> |	
| Articles (Android) | <video src="https://github.com/artsy/eigen/assets/20655703/e35cc9d9-4c0d-4dac-9db0-7ac0eb427edd" /> | <video src="https://github.com/artsy/eigen/assets/20655703/f44ddfc7-79ac-4933-bac2-f264be5d55cf" /> |
| Articles (iOS) | <video src="https://github.com/artsy/eigen/assets/20655703/2847c33e-48ed-4475-9b68-bca7c9e9a50f" /> | <video src="https://github.com/artsy/eigen/assets/20655703/6d13ed80-3a79-41be-b90f-cb901d600e17" /> |	

### PR Checklist

- [X] I have tested my changes on **iOS** and **Android**.
- [X] I hid my changes behind a **[feature flag]**, or they don't need one.
- [X] I have included **screenshots** or **videos**, or I have not changed the UI.
- [X] I have added **tests**, or my changes don't require any.
- [X] I added an **[app state migration]**, or my changes do not require one.
- [X] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [X] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [X] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Remove webview custom progress bar from ArtsyWebView - mrsltun

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[EMI-1396]: https://artsyproduct.atlassian.net/browse/EMI-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Remove webview custom progress bar from ArtsyWebView - mrsltun)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 988ad607da5d641dbef6cbde36a1392c409522a6
</p>

**Review by MounirDhahri — APPROVED** [review]
Nice! thanks for the thorough description

**Review by brainbicycle — APPROVED** [review]
Nice 👍

**Review by gkartalis — COMMENTED** [review]
Let's ship it 🤑

**Pull request merged**
