### PR TITLE
@alloy => synxify

### PR DESCRIPTION
**Pull request by orta**
Runs @venmo's synx across Eigen using my custom spaces to underscore branch. @marklarr - I owe you a beer sometime. 

screen shot 2015-07-03 at 11 25 47

### CODE REVIEW

**Comment by alloy** [comment]
Epic! As a vim user, you don’t know half how happy I am with sane FS representation and, in our case, no spaces.

Thanks @orta and @marklarr! :heart:

**Comment by orta** [comment]
FWIW, TextMate now supports opening xcodeproj files and setting the tree view based on it, could be worth making one for vim

before opening xcproj
screen shot 2015-07-03 at 11 39 19

after
screen shot 2015-07-03 at 11 39 27

**Comment by alloy** [comment]
@orta The thing is that so many of the extra vim tools purely work based on FS, so this wouldn’t really help there.

**Comment by orta** [comment]
Thanks CircleCI

MRW not having a clue who Victoria is

**Comment by alloy** [comment]
lol, awww, dat gif.

**Comment by alloy** [comment]
MERGING!

**Pull request merged**
