### PR TITLE
Galleries viewing rooms shell

### PR DESCRIPTION
**Pull request by ashfurrow**
This is just an empty shell behind a lab option (so users don't see it until we're ready). #skip_new_tests

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>TypeScript hasn't passed, see below for full logs</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Missing Test Files:

- `src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx`
- `src/lib/Scenes/ViewingRoom/__tests__/index-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "#skip_new_tests".</td>
    </tr>
  </tbody>
</table>


### TypeScript Fails

```src/lib/Components/__tests__/FilterModal-tests.tsx(313,27): error TS2322: Type '{ type: string; filter: string; }' is not assignable to type 'FilterData'.
  Object literal may only specify known properties, and 'type' does not exist in type 'FilterData'.
src/lib/Components/__tests__/FilterModal-tests.tsx(314,26): error TS2322: Type '{ type: string; filter: string; }' is not assignable to type 'FilterData'.
  Object literal may only specify known properties, and 'type' does not exist in type 'FilterData'.
```
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by ashfurrow** [comment]
@ds300 Hmm, seems like this isn't re-running `pod install` and so isn't picking up on the new files. I looked at the Circle CI config and it is including `^emission/` in the `native_code` manifest. Any ideas?

**Comment by ds300** [comment]
ah yes, to fix this we can just make it run `pod install` regardless of whether the cache got reinstated. It should still do the minimal amount of work because we're caching the Podfile.lock changes too.

So just remove the `ls Pod ||` bit from the pod install step.

Apologies for the oversight.

**Comment by ashfurrow** [comment]
No worries, that makes sense. Thanks David! 🙌

**Comment by ansor4** [comment]
thanks you two! i'm gonna go ahead and merge this!

**Pull request merged**
