### PR TITLE
@alloy => webkit polish

### PR DESCRIPTION
**Pull request by orta**
* makes topVC background black
* doesn't have an extra top margin
* Improves logging around allowing/cancelling requests

Ran out of time.
Includes #819 - cause 'ya know.

### CODE REVIEW

**Comment by alloy** [comment]
Before injecting those scripts, I’d like to be clear; it’s a conscious choice to allow the user to zoom these pages in Mobile Safari, yeah?

**Comment by orta** [comment]
Yeah, it is

**Comment by orta** [comment]
those pages aren't meant to _feel_ like a part of the app

**Comment by alloy** [comment]
Wouldn’t it still make more sense for them to add these restrictions when the client is Eigen? They already do certain things different for Eigen, so maybe it makes more sense to keep that all in one place

If that’s not necessarily the case for them, then I’m fine with merging this :+1:

**Comment by orta** [comment]
Yes, it would

**Comment by orta** [comment]
made an issue @anipetrov can you keep an aye on the issue directly above this comment, we need it in production before the next release ships.

**Comment by orta** [comment]
OK, presuming this is green, then it's good for review, I'm un WIPing

**Comment by alloy** [comment]
Btw, what about the `NSLog` calls, don’t want to turn those into log level specific ones?

And, just out of curiosity, which change makes it so that the background is black?

**Comment by orta** [comment]
>    [super webView:webView didFinishNavigation:navigation];

It's superclass uses this method to set it

**Comment by orta** [comment]
Fixed, ARActionLog wasn't autocompleting, figured it got `rm`'d

**Comment by alloy** [comment]
Thanks! 👌

**Comment by alloy** [comment]
There was a build that did succeed https://circleci.com/gh/artsy/eigen/815, so not sure what’s going on with CI, but gonna merge this.

**Pull request merged**
