### PR TITLE
fix: fix hidden login errors #trivial

### PR DESCRIPTION
**Pull request by brainbicycle**
The type of this PR is: **fix**

### Description

We are revalidating the form after setting the login error, since this isn't a form error it clears out the error. Remove the revalidation.

https://user-images.githubusercontent.com/49686530/149790955-4b084c2c-cc13-4478-9c0d-073056befac2.mp4

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Fix hidden login errors - brian 

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

### CODE REVIEW

**Comment by brainbicycle** [comment]
(also changed password for this account after the gif 😓 )

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Fix hidden login errors - brian)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3d76c528ba0ea46f350c61ca1a219c46f0f71314
</p>

**Comment by admbtlr** [comment]
Either the UX here is a bit odd, or we're giving away too much information: we use a generic error message, but only the password textbox is highlighted in red. We should either highlight both of them or neither of them.

**Comment by brainbicycle** [comment]
agreed but I didn't change any UX for this PR so I would say we shouldn't make a blocker to fix the major issue that we are not showing errors at all.

**Review by admbtlr — APPROVED** [review]

**Pull request merged**
