### PR TITLE
feat(CX-2362): Visual Update of Demand Index section

### PR DESCRIPTION
**Pull request by dariakoko**
The type of this PR is: **Feature**

This PR resolves [CX-2362]

### Description

Visual Update of Demand Index section

How it looks with and without feature flags "ARShowDemandIndexHints" and "ARShowRequestPriceEstimateBanner":

https://user-images.githubusercontent.com/36167539/158222782-55cf78be-1043-476d-bab8-ffae8f838711.mp4

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- visual Update of Demand Index section -daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[CX-2362]: https://artsyproduct.atlassian.net/browse/CX-2362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (visual Update of Demand Index section -daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 03ad9e04258fc4d46c1d3fcfccedd1eb912d9d2d
</p>

**Review by lordkiz — DISMISSED** [review]
Looks good to me. 👍 . You just need to fix that pesky `getByText(...)` test. Let me know when you do.

**Review by olerichter00 — APPROVED** [review]
Looks great 🌟

**Comment by dariakoko** [comment]
> Looks good to me. 👍 . You just need to fix that pesky `getByText(...)` test. Let me know when you do.

pesky indeed. :) I just removed it, we don't need that text any longer. 
I'll assign myself and merge when green, thanks! 👍

**Pull request merged**
