### PR TITLE
fix(stickers): fixing ios imessage stickers

### PR DESCRIPTION
**Pull request by pvinis**
The type of this PR is: **Bugfix**

This PR is part of FF.

### Description

I saw there was an email from apple that our sticker extension was 32-bit.

I removed and added a fresh extension, with the same stickers. (They look nice, I'll try to see what we could do to add them for messenger and whatsapp, I wanna use them 😄)

Here they are on an iPad.
IMG_DA69489D8BF4-1

- I moved the license file one dir up, so it's not inside apple's "xcassets" or whatever the name is, not to mess with anything in there.
- Removed the readme and the sketch file. They were not serving any purpose. The sketch file just had the artsy logo, not the stickers etc.
- I moved the min target from `12.0` to `12.1`. That's the minimum iOS 12 suggested by xcode so I thought I'll use that. Our app was `12.0` and the new extension came with `14.4`, so I put both to `12.1`.

#known

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

[CX-434]: https://artsyproduct.atlassian.net/browse/CX-434

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Developer Specific file shouldn't be changed, you can skip by adding #known to the PR body and re-running CI</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by pvinis** [comment]
lol at the visible messages there :p

**Review by ds300 — APPROVED** [review]
I can't read xcode metadata files 🙈 but the way you did this sounds 👍🏼 and I don't see anything odd.

**Comment by pvinis** [comment]
I took good care of the xcode files. I tried to make it simpler by moving things around but xcode really wanted them flipped. I can show the diffs if you want, but it's good. Now we also have a scheme that you can run and it opens imessage with the stickers nicely.

**Review by brainbicycle — APPROVED** [review]
🎉 Nice one!

**Pull request merged**
