### PR TITLE
feat(EMI-1815): allow countering a partner offer

### PR DESCRIPTION
**Pull request by leamotta**
This PR resolves [EMI-1815] 

### Description

Similar to https://github.com/artsy/force/pull/13811 but with less changes, as the checkout is only on web

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Send partner offer id when making an offer on a partner offered listing - leamotta

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[EMI-1815]: https://artsyproduct.atlassian.net/browse/EMI-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 56ed6bdc471e4460b717009ec70fc7c0392366a6
</p>

**Review by narikazu — APPROVED** [review]
LGTM

**Review by MrSltun — APPROVED** [review]
Looks good! 🌟 
But do we need to hide this change behind a feature flag? or just release it in the next release?

**Comment by leamotta** [comment]
> Looks good! 🌟 But do we need to hide this change behind a feature flag? or just release it in the next release?

Thought about it and think we can just release it in the next one!

**Pull request merged**
