### PR TITLE
@orta -> fix snapshots with 1px diff due to last PR

### PR DESCRIPTION
**Pull request by 1aurabrown**
I didn't realize my change to the chevron broke tests due to a 1px difference.

### CODE REVIEW

**Comment by orta** [comment]
Hrm, they all fail, are you not using the 8.3 sim?

**Comment by 1aurabrown** [comment]
Tests won't run without the 8.3 sim. I'll check it out.

**Comment by alloy** [comment]
Is this something that still needs to be done? Tests pass locally for me, so…

**Comment by orta** [comment]
Nah, let's close it.

**Pull request closed without merging**
