### PR TITLE
refactor(dev menu): android 14 Dev menu issues

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [PHIRE-359] 

### Description

@dblandin reported a weird behavior in the dev menu that happens only on android 14.

This PR fixes that by removing `CollapseMenu` component that we were using only on DevMenu with the Expandable component that lives in eigen. 

Will move it to palette-mobile in another PR.

> [!NOTE]
> **Bonus:**  Also converts the modal devMenu on the onboarding stack to a screen to match the rest of the app

|Before|After|
|---|---|
|<video src="https://github.com/artsy/eigen/assets/21178754/3f4ceffd-b06c-4a9b-baeb-ec084fec771c" width="200" />|<video src="https://github.com/artsy/eigen/assets/21178754/66990b87-65d5-4b90-b470-75d41bf5c271" width="200" />|

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- android dev menu improvements - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[PHIRE-359]: https://artsyproduct.atlassian.net/browse/PHIRE-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gkartalis** [comment]
I've also run ` yarn codepush:deploy 'Canary' 'Dev Menu'` to trigger a codepush canary build to test it out before merging.

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (android dev menu improvements - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 089019b64288e24e1cb455d4f4e6b082c351fb78
</p>

**Review by dblandin — APPROVED** [review]
Amazing! Just downloaded the latest beta and then fetched the latest canary JS bundle. The updated menus in the dev menu seem fixed to me!

Thanks so much 💯

**Comment by brainbicycle** [comment]
nice one, got rid of a custom component and fixed a bug 🤩

**Pull request merged**
