### PR TITLE
Update License section

### PR DESCRIPTION
**Pull request by jonallured**
I noticed that our copyright line was inconsistent across projects and
often still listed 2016. So, I worked with Yayoi to figure out what the
right language was and am now copy/pasting to achieve consistency.

### CODE REVIEW

**Comment by alloy** [comment]
🕺 

What about the copyright line in the LICENSE file?

**Comment by orta** [comment]
Could also make a danger rule?

**Comment by jonallured** [comment]
Haha, what have I gotten myself into. Ok, I just talked it over with Yayoi:

* Ensure LICENSE file exists in Artsy open source projects (raise issue if not)
* Compare LICENSE copy to default copy (https://github.com/jonallured/omg/blob/master/LICENSE)
* Move copyright line to the LICENSE file from README
* Link to LICENSE file from README (single source of truth)
* Ensure copyright line is up to date (2017)
* Ensure copyright line includes year of first commit
* Ensure correct company name (Art.sy Inc.)

I think that's enough for this afternoon. Future Jon can create a Danger rule and get that in a separate PR.

**Comment by orta** [comment]
If you can write the danger rule in JS - I can get it applied across the entire org [using Peril](https://github.com/danger/peril)

**Comment by jonallured** [comment]
Ok, last note on license/copyright stuff today, promise! Turns out the copyright line belongs in the LICENSE file and that should be the single source of truth for this info. While I was at it, I updated the copy slightly to match the default copy from the GitHub template.

**Comment by orta** [comment]
looks legit to me

**Comment by alloy** [comment]
Yup, LGTM. Groovy, thanks @jonallured!

**Comment by jonallured** [comment]
and thanks for catching that our copyright was duplicated @alloy <3

**Pull request merged**
