### PR TITLE
Updates pods for colours, buttons, labels

### LINKED ISSUE #1263: Misplaced Info Button
On Auctions native views. Reported at https://rink.hockeyapp.net/manage/apps/37020/feedback/454937

Example:

image_0-4

### PR DESCRIPTION
**Pull request by ashfurrow**
(But not fonts!)

298 snapshot tests have had their reference PNG changed, so let's be extra careful :grimacing: 

I tried to base new colour uses off of https://github.com/artsy/Artsy-UIColors/commit/f49a3bc1a1e24def2f2b805a47bf3d17d7b4c700 and https://github.com/artsy/Artsy-UIColors/commit/25e953a3fa61ec347315c17277426cea463b2861 but I may be wrong, and I just had to pick one for `artsyAttention` I used `artsyAttentionYellow` since the old one was yellowish. 

The snapshots should give us a good look at the differences. @katarinabatina could you give them a once-over and see if there are any colours we need to change?

Fixes #1263.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">2 Warnings</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td>Needs testing on a Phone if change is non-trivial</td>
    </tr>
        <tr>
      <td>:warning:</td>
      <td><h4>Found unstubbbed networking requests</h4>

<ul>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
</ul>
</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
It may be easier to view the snapshots in: https://github.com/artsy/eigen/pull/1299/commits/da1acf16f29b89b7eda2bc2d14f6dd48a80c9f5d

**Comment by katarinabatina** [comment]
@ashfurrow @orta pretty brutal to go through as the diffs stopped rendering halfway through the page. The fact that I can't comment on a per diff basis is MINDBLOWING. Any suggestions for how I should QA this? (Top of my list of things to tackle in the morning)

**Comment by orta** [comment]
can sit with me, and we can try go over on my computer

**Comment by alloy** [comment]
That 'search zero state' label looks less intelligible to me.

I'll delegate further reviewing+merging to @orta + @katarinabatina.

**Comment by ashfurrow** [comment]
Agreed, I'll be in the office after lunch and can help review.

**Comment by ashfurrow** [comment]
OK, resolved some design issues with @katarinabatina. This should be good to review. 

I took a look for places we were using `colorWithHex:` manually instead of a standard Artsy colour (there were only a handful). @katarinabatina could you take a look at the changes and give the 👍/👎? They're at https://github.com/artsy/eigen/pull/1299/commits/a590505fd03a954baa5c32289db1dd3083c72eb8

**Comment by ashfurrow** [comment]
@katarinabatina let me know when you're happy with this, and I'll squash all the commits into one to keep our repository small.

**Comment by ashfurrow** [comment]
Closing in favour of #1309.

**Pull request closed without merging**
