### PR TITLE
fix: extract artist series title for alert criteria pills

### PR DESCRIPTION
**Pull request by anandaroop**
This PR resolves [ONYX-634] 

### Description

This implements @olerichter00 's suggestion for a workaround for better parsing of artist series titles from slugs.

Works as follows…

```ts
inferSeriesName("yayoi-kusama-pumpkins", ["Yayoi Kusama"])
// => "Pumpkins"
```

This is not the ideal solution, but a short-term expedient solution. Better long-term would be to make this work [as Force does](https://github.com/artsy/eigen/pull/9691#pullrequestreview-1803800447).

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- 

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- improve logic for inferring artists series titles in alert criteria pills

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-634]: https://artsyproduct.atlassian.net/browse/ONYX-634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by anandaroop** [comment]
@olerichter00 I took your idea of simply removing the artist name from the slugs and found there were a number of edge cases that prevented this from working reliably, so then I added workarounds for those.

I tested this against the 100 biggest artist series and eventually I was able to get a good result 93% of the time. Not pretty, but maybe an acceptable workaround for now? 🤷🏽 

Would definitely be better to make this work more like Force, but perhaps this could be an incremental step.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8b7abccd2f53f292afa454b892517fafe6f05246
</p>

**Review by olerichter00 — APPROVED** [review]
Looks good! 👍 

If I remember correctly, this is how we inject the pill labels (alert preview) in Force: https://github.com/artsy/force/blob/ee6be642acc434975a512045714909c3dd73d454/src/Components/Alert/AlertProvider.tsx#L187

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (improve logic for inferring artists series titles in alert criteria pills)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 65c29853e5fc8a19a2b102e252a9f460fd144426
</p>

**Comment by anandaroop** [comment]
Thanks @olerichter00, I've cleaned up the specs, and will merge this now.

**Pull request merged**
