### PR TITLE
feat: Sort artwork lists by updated at desc

### PR DESCRIPTION
**Pull request by olerichter00**
This PR resolves [ONYX-121] 

### Description

Sort artwork lists by updated at desc.

- Note: Because we use the fetch policy 'network-only', the data is refreshed every time the modal opens.

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Sort artwork lists by updated at desc. - ole

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-121]: https://artsyproduct.atlassian.net/browse/ONYX-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Sort artwork lists by updated at desc. - ole)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c339c73efb0583b8e368a7ca5729b8196eafbcd0
</p>

**Review by nickskalkin — APPROVED** [review]
Looks good to me. My only concern is that Dima [had a concern](https://artsy.slack.com/archives/C9SATFLUU/p1684353474289759), that this change could cause some bugs with pagination. I've tried your changes on my local and couldn't reproduce any bug, so idk.

Before I merge, @anandaroop since you were involved in this discussion, maybe you know what exactly should have become broken?

**Comment by olerichter00** [comment]
> Looks good to me. My only concern is that Dima [had a concern](https://artsy.slack.com/archives/C9SATFLUU/p1684353474289759), that this change could cause some bugs with pagination. I've tried your changes on my local and couldn't reproduce any bug, so idk.

I've tested it as well and it looks like the data gets prefetched every time.

**Comment by anandaroop** [comment]
I _think_ the pagination concern Dima mentioned was [elaborated in a comment](https://github.com/artsy/eigen/pull/8678#discussion_r1192792349) on a PR he opened to illustrate the different approaches.

**Pull request merged**
