### PR TITLE
feat: update relay version to 13 [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **Feature**

### Description
This PR upgrade relay to **v13**. For the few trials I made, the compiler has been 17% faster

**Note:**
- I played around the app for a while and everything was working fine 🤷‍♂️
- Please do not merge

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Upgrade to relay 13 - mounir

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Upgrade to relay 13 - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 245a607c823cedbf1103f81e879bb43c86dd3c06
</p>

**Review by pvinis — APPROVED** [review]

**Review by olerichter00 — COMMENTED** [review]
Are you planning to all other Relay packages as well? https://github.com/artsy/eigen/pull/5995 is an attempt to upgrade all packages to version 13.

**Comment by pvinis** [comment]
oh snap. thats totally right, yea we should upgrade all the relay things

**Comment by MounirDhahri** [comment]
@olerichter00 yes, I am just fooling around and wanted to see how much time it saves in ci and it's kind of the same performance so far

**Comment by MounirDhahri** [comment]
omg. I didn't see your PR before, I will close this one in favour of it then

**Pull request closed without merging**
