### PR TITLE
feat: add add-manual-submission tag to releases

### PR DESCRIPTION
**Pull request by MounirDhahri**
### Description

This PR adds the `-submission` tag to the android and iOS tags.

The way this script works is as follows:

```bash
node scripts/add-submission-tags.js  
```

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- add add-manual-submission-tag to releases - mounir

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by patrinoua — APPROVED** [review]
🙌🏻

**Review by MrSltun — APPROVED** [review]
🌟

**Comment by MounirDhahri** [comment]
@patrinoua @MrSltun Let's schedule a call to update our docs to include this update then merge this PR

**Comment by patrinoua** [comment]
Sent you both an invite!

**Comment by MounirDhahri** [comment]
Tested the script and it's working properly. Will also checkout to main after finishing

Screenshot 2022-08-10 at 13 22 27
Screenshot 2022-08-10 at 13 19 47

**Pull request merged**
