### PR TITLE
fix(ux): dont ask notif permissions  right after signin

### PR DESCRIPTION
**Pull request by pvinis**
### Description

Right after signing, we ask for push notif permissions. this ux feels bad. I checked if we ask for permission before doing anything that needs it, and we do. So we don't need to ask up front so early. We will ask when the users needs it anyway.

We ask here:
- https://github.com/artsy/eigen/blob/3ddbd6746cc233c1733b635c67c09319247b62f0/src/app/Scenes/SavedSearchAlert/helpers.ts#L22
- https://github.com/artsy/eigen/blob/e09d9f37f46264bf08bf9a85519362e413007bf4/src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx#L85

This PR resolves [MOPLAT-175]

#### Acceptance Criteria

-

#### Setup Instructions

-

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[MOPLAT-175]: https://artsyproduct.atlassian.net/browse/MOPLAT-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — COMMENTED** [review]
Nice - this looks good to me. Also thanks for starting the conversation at slack, let's wait for product approval then get this merged

**Comment by MounirDhahri** [comment]
@pvinis should we close this PR for now following Joey's comments on slack?

**Comment by pvinis** [comment]
ive missed the comments. if you could link it to me that would be great 🙏

**Comment by MounirDhahri** [comment]
Of course, here is it https://artsy.slack.com/archives/C01B2P6LJUU/p1662699539222859

**Comment by pvinis** [comment]
sadly closing this for now. docs on next steps https://artsyproduct.atlassian.net/browse/MOPLAT-516, and thread https://artsy.slack.com/archives/C01B2P6LJUU/p1662699539222859

**Pull request closed without merging**
