### PR TITLE
fix(DIA-310): empty state logic on Artist about tab

### PR DESCRIPTION
**Pull request by araujobarret**
This PR resolves [DIA-310] 

### Description

Fixes the logic of when or not to display the empty state. It's very similar to Force's implementation.

Before

After

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- fix: show correctly the empty state on Artists' about tab - araujobarret

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[DIA-310]: https://artsyproduct.atlassian.net/browse/DIA-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (fix: show correctly the empty state on Artists' about tab - araujobarret)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7b4d4ec81f9d82720b55025c72a53aab0d2a1a84
</p>

**Comment by egdbear** [comment]
nitpick (non-blocking): Since this is not part of this PR, I see that we are not using the same apostrophe (unicode) as we use on the force.
Screenshot 2023-11-13 at 09 52 51

**Review by egdbear — APPROVED** [review]

**Comment by araujobarret** [comment]
Should it be the apostrophe? (I can change in a follow-up PR)

**Comment by egdbear** [comment]
> Should it be the apostrophe? (I can change in a follow-up PR)

I don't have answer for that - we better ask designers whether we change this on force or eigen 😅

**Pull request merged**
