### PR TITLE
rename(text props): rename `size` to `variant` for text v3

### PR DESCRIPTION
**Pull request by pvinis**
The type of this PR is: **Enhancement**

This PR resolves []

### Description

After @MounirDhahri saw that eigen and force use different names for the same prop, based on the discussion here https://artsy.slack.com/archives/C9XJKPY9W/p1632234545035900, I have renamed the prop from `size` to `variant`.

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- rename `size` to `variant` in text v3 - pavlos

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (rename `size` to `variant` in text v3 - pavlos)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 71d4d318b30231f4d015306594fdddbca7cb30db
</p>

**Review by MounirDhahri — APPROVED** [review]
Awesome thanks! 🎉

**Review by olerichter00 — APPROVED** [review]
Nice 🚀 

Some tests are failing because of the `fontWeight`. Should this be `normal` instead of `medium`?



```
Invariant Violation: Invalid prop `fontWeight` of value `medium` supplied to `StyleSheet generated`, expected one of ["normal","bold","100","200","300","400","500","600","700","800","900"]
```

**Comment by pvinis** [comment]
Ah, silly tests, I missed them. I'll fix them.

**Comment by Serge0n** [comment]
If we are using TextV3 should we wrap it into ThemeV3?
https://github.com/artsy/eigen/blob/b385959df6ad5c4c71c3e4346b0877b39cbf5162/src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx#L100

image

**Pull request merged**
