### PR TITLE
feat: User can see Order Summary section PX-4071

### PR DESCRIPTION
**Pull request by Serge0n**
The type of this PR is: **Feature**

This PR resolves [PX-4071]

### Description

Added Order Summary section to Order Details page and covered by tests.

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.
Запись экрана 2021-06-02 в 18 44 13

[PX-4071]: https://artsyproduct.atlassian.net/browse/PX-4071

### CODE REVIEW

**Review by kiryl-zubarau — APPROVED** [review]

**Review by brainbicycle — APPROVED** [review]
Looks good, nice tests! Looks like some tests are failing on CI, if you can fix good to merge.

**Comment by Serge0n** [comment]
Thanks!) I have a question about testing SectionList. We have 6 sections in total. Only 3 sections can be placed on the screen. And this is the reason why tests are failed. How we can test SectionList better?

This works, but it seems to me it's wrong:
image

**Comment by Serge0n** [comment]
@MounirDhahri Can you help with correct <SectionList /> testing

**Comment by MounirDhahri** [comment]
@Serge0n I left a comment on the slack thread you jus shared on #dev-help

**Pull request merged**
