### PR TITLE
Adds Danger rule for sticker extension version

### PR DESCRIPTION
**Pull request by ashfurrow**
This is a work-in-progress because I want to verify it works. Once I've done that, I'll modify our `make` task to update it, and update the Info.plist file.

Fixes https://github.com/artsy/eigen/issues/2219

### CODE REVIEW

**Comment by ashfurrow** [comment]
Mmm, looks like the makefile task already exists as "update_bundle_version"; whoever updated the app's info.plist most recently must've not used the `make` command.

**Comment by ashfurrow** [comment]
Hmm, I expected Danger to fail. Will investigate.

**Comment by ashfurrow** [comment]
Okay, let's try again 😄

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">You need to set the Sticker extensions’s plist version to 3.2.0</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by ashfurrow** [comment]
Thanks Danger, will fix.

**Comment by alloy** [comment]
Isn’t the beta release process supposed to run that make task? I just push to the beta branch, didn’t think we needed to perform any tasks ourselves anymore.

**Comment by alloy** [comment]
Maybe the difference is that `3.2.0` isn’t a bundle version, it’s a marketing one?

**Comment by ashfurrow** [comment]
Correct, the beta release process doesn't change the marketing version number, that's usually done manually afterwards. The change that the beta task _does_ make doesn't even get committed back to the codebase, it's just re-applied during every deploy.

**Comment by ashfurrow** [comment]
Not sure why Danger is still failing, I'm rebuilding.

**Comment by ashfurrow** [comment]
Not sure, I might be confusing Danger with a force-push from earlier. I think we can just merge @alloy 👍

**Comment by alloy** [comment]
👍

**Comment by orta** [comment]
Those rules could indeed move into the deploy script, and removed from Danger 👍

**Pull request merged**
