### PR TITLE
feat(ONYX-511): move custom inputs below

### PR DESCRIPTION
**Pull request by dariakoko**
This PR resolves [ONYX-511] 

### Description

| Price Range screen | Create Alert modal |
| --- | --- | 
| simulator_screenshot_04036317-704B-4389-A320-3C6CDCFA644E | simulator_screenshot_10BE2C0F-677B-4737-8486-226C816388C1 |
### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Move custom min/max inputs of Price Range filter below slider - daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-511]: https://artsyproduct.atlassian.net/browse/ONYX-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Move custom min/max inputs of Price Range filter below slider - daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 53a77f6f09ea0e6dcb256ee8111b64509fd4ba66
</p>

**Review by gkartalis — COMMENTED** [review]
👀 could you also add some screenshots? It will be helpful for future reference

**Comment by dariakoko** [comment]
Done @gkartalis! Was editing the description and didn't save the changes initially 😶‍🌫️

**Comment by dariakoko** [comment]
FYI - we did the same on web
Discussion with the design: https://artsyproduct.atlassian.net/browse/ONYX-511?focusedCommentId=59493

**Review by dblandin — APPROVED** [review]
Awesome 👍🏼

**Pull request merged**
