### PR TITLE
chore: Clean up AREnableHomeScreenArtworkRecommendations

### PR DESCRIPTION
**Pull request by olerichter00**
This PR resolves [CX-3023] 

### Description
Clean up AREnableHomeScreenArtworkRecommendations.

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-3023]: https://artsyproduct.atlassian.net/browse/CX-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by gkartalis — APPROVED** [review]

**Comment by MounirDhahri** [comment]
Speaking of that - I am wondering if we should update the echo model in Eigen to keep the values to whatever they are if they're missing in the remote echo file.

**Comment by olerichter00** [comment]
> Speaking of that @pvinis - I am wondering if we should update the echo model in Eigen to keep the values to whatever they are if they're missing in the remote echo file.

That's a great idea! In the released app we could default to `true` if there is no flag in Echo and keep the warning when developing. 

I just wonder if there would be any risk of forgetting to add the remote flag for features that are not ready to be released 🤔

**Comment by pvinis** [comment]
I would not do much there, since echo should not be used anymore for features, but let's bring it up in mobile-practice and decide.

**Comment by MounirDhahri** [comment]
> I just wonder if there would be any risk of forgetting to add the remote flag for features that are not ready to be released 🤔

That's a valid point, I think we can raise a dev alert in that case. Anyway in my opinion, we should never remove ffs from Echo since after all. If we would like to keep the file small, maybe we can start generating it and separate the old and new flags.

**Pull request merged**
