### PR TITLE
fix: round down to one decimal in demand label #trivial

### PR DESCRIPTION
**Pull request by brainbicycle**
The type of this PR is: **Bugfix**

### Description

This is a quick follow-up to https://github.com/artsy/eigen/pull/4090, I noticed after the fact that @samchieng had asked to round down to one decimal place to avoid 10/10.

### Screenshots

DemandIndexiPad
### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

### CODE REVIEW

**Comment by admbtlr** [comment]
I think that @samchieng 's comment specifically addressed scores of 10. I don't think it's necessary to round down _everything_, but only to put in a special case that `score = score === 10 ? 9.9 : score`. At least that's how I understood it - but maybe I misunderstood?

**Comment by brainbicycle** [comment]
This feels a bit arbitrary to me and I think in general we should try to avoid arbitrary transformations of the data on the client, that said I don't feel too strongly about it so I will make the change 👍

**Comment by admbtlr** [comment]
Yeah, I hear you on that. But I guess it makes sense from a product perspective, and I also guess it's pretty unlikely that demand will round to 10.

**Review by admbtlr — APPROVED** [review]

**Comment by admbtlr** [comment]
#squashongreen

**Pull request merged**
