### PR TITLE
fix: text style incosistency on accepting bid terms

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [] 

### Description

This PR fixes some font size inconsistencies on the accept terms of bid screen. We found it during the Mobile QA meeting (card [here](https://www.notion.so/artsy/Text-link-for-agreeing-to-terms-of-auctions-bigger-than-it-is-supposed-to-be-when-bidding-8b5fb9c3dccd4e8e91a727a8a97e5dc0?pvs=4))

#### Screenshots

|Before|After|
|---|---|
|before1|after1| 
|before2|after2| 

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- fixed text style incosistency on accepting bid terms - gkartalis

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (fixed text style incosistency on accepting bid terms - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f7e4ee1caccf5cc662e4707bf6b370c4dee812c4
</p>

**Comment by gkartalis** [comment]
To be clear: this is not a launch blocking bug, no need to include into the release

**Review by MounirDhahri — COMMENTED** [review]
Thanks for fixing this @gkartalis. I am not sure though if I agree with this not being launch bloking. I think we should fix this in the upcoming release.

Btw, the checkbox is still not yet visible in the first screenshot. Did you maybe link the wrong screenshot?

**Comment by gkartalis** [comment]
Happy to merge and include then! The first one is without checkbox and the second one is with checkbox, don't have much context on the why we have both but you can see [here](https://github.com/artsy/eigen/blob/10b8c7878479f6cea2ff8668663199ec8cb50df1/src/app/Components/Bidding/Screens/ConfirmBid/index.tsx#L561) that we have two cases.

**Comment by MounirDhahri** [comment]
Sounds great. thanks a lot

**Comment by MounirDhahri** [comment]
@gkartalis no need to cherry pick this then. I though the checkbox was not visible

**Pull request merged**
