### PR TITLE
@orta -> fix ARCollapsableTextView relying on intrinsicContentSize

### PR DESCRIPTION
**Pull request by 1aurabrown**
I don't know what changed to make this view go from working to broken, but it seems that neither the view's `intrinsicContentSize` nor its `contentSize` accurately reflect the full height of the text at the time when we need it. This seems to be the popular solution on stackoverflow.

### CODE REVIEW

**Comment by orta** [comment]
Can I get some tests for this? Maybe put it in a view controller and do snapshots for collapsed and expand?

**Comment by 1aurabrown** [comment]
@orta yeah I think that's the only real way to test this

**Comment by alloy** [comment]
@1aurabrown This is partial test coverage in that it’s still missing the correct _after_ expansion snapshot?

**Comment by orta** [comment]
Yeah, there's chat about it in Slack, once I've got this WKWebKit stuff sorted I'll take a look in a few hours

**Comment by alloy** [comment]
Ah yeah, just saw it. Should :coffee: first!

**Comment by orta** [comment]
@1aurabrown - I've merged master, and I simplified the tests. My tests don't care about internals like whether the constraint is set up, but they care about the end result, "does it look like expected?" vs "is the expanded constraint working"

If you're happy. Merge :+1:

**Comment by alloy** [comment]
I’m not quite sure how this change affects the search view, I’m gonna assume it’s a fluke.

**Pull request merged**
