### PR TITLE
chore: hide network unavailable modal behind feature flag

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **chore**

This PR resolves [this comment](https://github.com/artsy/eigen/pull/5494#pullrequestreview-761221925) and [this comment](https://github.com/artsy/eigen/pull/5494#issuecomment-925279714)  on #5494 

### Description
Hide network unavailable modal behind feature flag

**Note:** Please only merge after https://github.com/artsy/echo/pull/129

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Hide network unavailable modal behind feature flag - mounir

</details>

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Hide network unavailable modal behind feature flag - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9977731e9fa5ddcc25963f51ec8f0baf54112bb0
</p>

**Review by brainbicycle — APPROVED** [review]
Thank you! 🏁

**Comment by brainbicycle** [comment]
Looks like test failure is because we don't have an echo flag yet

**Comment by MounirDhahri** [comment]
Good catch. I linked a PR with the echo in the description, would you mind if you take a look at it

**Review by olerichter00 — APPROVED** [review]
Thanks, @MounirDhahri 🌟

**Pull request merged**
