### PR TITLE
Updates Emission to version 1.11.4 #trivial

### PR DESCRIPTION
**Pull request by sweir27**
Includes some updates to the fledgling artwork view in Emission.

### CODE REVIEW

**Comment by alloy** [comment]
@sweir27 `#trivial` should go in the body of your PR message.

**Comment by alloy** [comment]
Merging this to possibly reduce build time when y’all wake up.

**Comment by alloy** [comment]
And great stuff on becoming a mobile dev!

**Comment by sweir27** [comment]
Oops, thanks @alloy !

**Pull request merged**
