### PR TITLE
[Pods] Update fonts again for OSS consumers #trivial

### PR DESCRIPTION
**Pull request by orta**
3.1.1 just is a fix for this - https://github.com/artsy/Artsy-OSSUIFonts/issues/11

### CODE REVIEW

**Comment by alloy** [comment]
Awww, needs conflicts resolved.

**Comment by orta** [comment]
its submodule bizniz

**Comment by orta** [comment]
this danger message is fixed, so can be ignored

**Comment by alloy** [comment]
👌

**Pull request merged**
