### PR TITLE
Deploy shenanigans

### PR DESCRIPTION
**Pull request by alloy**

### CODE REVIEW

**Comment by orta** [comment]
the fastlane thing means we get out of date reallllllly quickly, are you sure about that?

**Comment by alloy** [comment]
The purist in me doesn’t see the point of having Fastlane in the gem bundle and then not using the actual bundled versions. We could just as well leave it out of the Gemfile completely and install the gems as part of the CI distribution process?

**Comment by alloy** [comment]
(I’m fine to revert btw, this is all more a philosophical issue.)

**Comment by alloy** [comment]
My comment on https://forums.developer.apple.com/message/125506:

> In my 4th attempt I removed the `ITSAppUsesNonExemptEncryption` key from my Info.plist file and it succceeded, so I thought that that was the issue. However, after reading this thread I’m getting the feeling that it might have just been that the first 3 builds fail for those affected and the 4th succeeds.

So, maybe we shouldn’t remove it just yet.

**Comment by orta** [comment]
> We could just as well leave it out of the Gemfile completely and install the gems as part of the CI distribution process? 

is a good idea, I'm up for that, remember you need some of the tooling for app store metadata deployment

**Comment by alloy** [comment]
Deploying works again from CI including the info plist key, so punting on this for now.

**Pull request closed without merging**
