### PR TITLE
@ashfurrow=>Increased font size

### LINKED ISSUE #453: show details text too small
image

on both iphone and ipad these should be 32 px (retina) (also increase line spacing)

image

### PR DESCRIPTION
**Pull request by sarahscott**
This increases the font size for metadata in the ShowViewController

Fixes #453 

ios simulator screen shot may 22 2015 5 10 06 pm

ios simulator screen shot may 22 2015 5 19 05 pm

### CODE REVIEW

**Comment by orta** [comment]
@katarinabatina ^

**Comment by ashfurrow** [comment]
Looks good to me. Just want a :+1: from Katarina.

**Comment by katarinabatina** [comment]
@ashfurrow can we increase the line spacing as well? The size looks great

**Comment by sarahscott** [comment]
will do!

**Pull request merged**
