### PR TITLE
Max Bid Fixes

### PR DESCRIPTION
**Pull request by ashfurrow**
Related to #1631.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Looks like there was a mismatch after https://github.com/artsy/emission/pull/175 was merged, the Podfile was still pointing to an old version of React that had been updated in Emission. I `bundle exec pod install`'d, committed + pushed changes to eigen-artefacts ( https://github.com/artsy/eigen-artefacts/commit/09019c40ea3a7a22421903b564a1b684801b1c0d ) and updated the Podfile/.lock and submodule commit. Fingers crossed.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
        
            2 Warnings
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
    
    
  </tbody>
</table>
  

  



Time | Class | Function |
| --- | ----- | ----- |260.5ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-max-bid/Artsy/View_Controllers/Auction/AuctionViewController.swift#L181) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
197.4ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-max-bid/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
173.9ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-max-bid/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
77.7ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-max-bid/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
74.0ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-max-bid/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
71.6ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-max-bid/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, sideMargin: String)
71.3ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-max-bid/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
69.3ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-max-bid/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
61.4ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/ashfurrow-max-bid/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView




<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
dscf3150

**Pull request merged**
