### PR TITLE
User can see lot standings and fake registered sales (upcoming sales)

### PR DESCRIPTION
**Pull request by yuki24**
This PR wires up the My Bids screen with Metaphysics.

I don't have the GraphQL queires/fields for the screen just yet, but I thought we could probably assume that the schema is going to look alike so just wiring up basic query should not add too much overhead. Also since it uses the current `me.lotStandings` query you can actually already see your bids for online-only auctions.

## Todos

 * [x] Merge https://github.com/artsy/eigen/pull/3651
 * [x] Add more test coverage
 * [x] Update `CHANGELOG.md`

## Screenshot

AUCT-1158-graphql

 #skip_new_tests

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Missing Test Files:

- `src/lib/Scenes/MyBids/helpers/__tests__/index-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "#skip_new_tests".</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by bhoggard** [comment]
This is great! It looks fine to me, but I would like to wait for @ashfurrow's review tomorrow before we merge.

**Comment by yuki24** [comment]
Since this PR is still open I just decided to go ahead and finish https://artsyproduct.atlassian.net/browse/AUCT-1171. Here is a screenshot of the loading state:

Screen Shot 2020-08-05 at 12 37 17 PM
Screen Shot 2020-08-05 at 12 45 26 PM

**Comment by yuki24** [comment]
It seems like Ash is OOO this week, so I'll just go ahead and merge this PR since it's blocking other work https://github.com/artsy/eigen/pull/3684.

In the meantime, I will ping @ds300 or @brainbicycle in case they have any feedback.

**Pull request merged**
