### PR TITLE
feat(CX-2594): add my collection insights phases steps

### PR DESCRIPTION
**Pull request by MounirDhahri**
This PR resolves [CX-2594]

### Description
- Add my collection insights phases steps

Sorry for adding you all as reviewers, that's because we will be going step by step with the release, therefore I wanted you all to know about the feature flags we're going with and adjust your PRs according to that

**Note:** don't forgot to enable the feature flag after this PR gets merged

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [x] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [x] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- add my collection insights phase 1 different steps - mounir

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-2594]: https://artsyproduct.atlassian.net/browse/CX-2594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by olerichter00 — APPROVED** [review]
🔢   🚢   📈 

Let's make sure to add the phases to the tickets to not be confused about which feature belongs to which phase.

**Comment by MounirDhahri** [comment]
@olerichter00 I am thinking about renaming the insights flag to be the step1 flag, how does that sound? this will mean we won't need to update the tickets

**Review by dariakoko — APPROVED** [review]
🙌 🙌

**Review by MrSltun — APPROVED** [review]
🌟

**Comment by MounirDhahri** [comment]
Let's gooo

**Pull request merged**
