### PR TITLE
chore: Remove AROptionsNewSalePage feature flag

### PR DESCRIPTION
**Pull request by rajsam003**
The type of this PR is: chore

This PR resolves [CX-2367]

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Remove AROptionsNewSalePage feature flag - Sam

</details>

[CX-2367]: https://artsyproduct.atlassian.net/browse/CX-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Remove AROptionsNewSalePage feature flag - Sam)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against edc95d8f0db275ed1f7b4af1dee7d12c5326e687
</p>

**Review by olerichter00 — COMMENTED** [review]
@MounirDhahri does this ticket include removing the native code from the old auction screen?

**Comment by MounirDhahri** [comment]
@olerichter00 yes 😄 it should

**Comment by MounirDhahri** [comment]
Any updates on this @rajsam003 ?

**Review by olerichter00 — APPROVED** [review]

**Comment by pvinis** [comment]
nice!

**Pull request merged**
