### PR TITLE
[WFY] Add alternate copy for user following artists but empty WFY VC

### PR DESCRIPTION
**Pull request by mennenia**
Temporary fix for #1863, just for the beta. Continuing today (and weekend if necessary) to _actually_ fix it lol.

simulator screen shot 14 oct 2016 15 47 12

### CODE REVIEW

**Comment by alloy** [comment]
Good call 👍

**Comment by mennenia** [comment]
tests failing because I haven't stubbed the new call etc. I may just change the copy (rather than showing the original if you don't follow artists, and showing this if you do)

**Comment by mennenia** [comment]
Pushed a simpler change.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">There were <a href="https://eigen-ci.s3.amazonaws.com/3358/index.html">snapshot errors</a></td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |250.1ms | [AuctionViewController.swift](/artsy/eigen/tree/mc-wfypatch/Artsy/View_Controllers/Auction/AuctionViewController.swift#L199) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
215.8ms | [SwiftyJSON.swift](/artsy/eigen/tree/mc-wfypatch/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
206.5ms | [WebSocket.swift](/artsy/eigen/tree/mc-wfypatch/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
94.9ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/mc-wfypatch/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L47) | @objc override func viewDidLoad()
80.2ms | [Observable.swift](/artsy/eigen/tree/mc-wfypatch/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
74.1ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/mc-wfypatch/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
73.8ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/mc-wfypatch/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
71.4ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/mc-wfypatch/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
69.3ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/mc-wfypatch/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)


### Tests: 

Classname | Name|
--- | ---|
ARWorksForYouReloadingHostViewControllerSpec | test_reloads_all_the_data|
ARWorksForYouViewControllerSpec | test_as_iphone|
ARWorksForYouViewControllerSpec | test_as_ipad|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Pull request merged**
