### PR TITLE
[WIP] Updates to Xcode 8 / Swift 3

### PR DESCRIPTION
**Pull request by ashfurrow**
- [x] Get project compiling
- [x] Get unit tests compiling
- [x] Get unit tests to pass
- [x] Fix [this test](https://github.com/artsy/eigen/pull/1990/files#diff-8cba0c202251f5526820d74fc3ea0614R22)
- [ ] Test on device

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">PR is classed as Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |40.9ms | [Mutex.swift](/artsy/eigen/tree/xcode-8-update/Pods/Interstellar/Sources/Mutex.swift#L35) | func lock(closure: () -> Void)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by ashfurrow** [comment]
So the big issue now is that we were testing on iOS 9.3 but Circle only has 9.0 or 10.0. I'm looking into how hard it would be to move back to 9.0, but it's looking like 10.0 might be just a s much work (and a step forward, not back).

**Comment by ashfurrow** [comment]
Yeah, so there's work left to do if we're going to compile against iOS 10, which we'll need to do eventually. But most things look good. I'll talk to the rest of the team about their plans around this.

**Comment by alloy** [comment]
I’m thinking that it might make sense to run CI against the oldest version we support, as it’s likely that we’d normally dev on iOS 10. Does that make sense to you?

**Comment by ashfurrow** [comment]
Makes sense to me! 

Deploying from Xcode 8 on CI means there still might be some iOS 10 issues, I haven't thoroughly tested yet.

**Comment by ashfurrow** [comment]
Looks like it'll be easier to just install the simulator from the command line.

**Comment by joh1234** [comment]
https://goo.gl/JBljdR

**Comment by orta** [comment]
Note: the Pods dir will need work on a merge, a bunch of stuff has happened in there since this PR was started

**Comment by orta** [comment]
OK, I think that's everything.

**Comment by alloy** [comment]
`[WIP]`, an unchecked TODO, and merged. Living the danger life 🤘

**Pull request merged**
