### PR TITLE
Update CHANGELOG format a bit

### PR DESCRIPTION
**Pull request by orta**
Added a section for upcoming called `details` that gives an overview for an upcoming releases aim. Separates out developer related notes from user facing ones too. Was getting tough to see what affected a user and what is behind the scenes.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
&nbsp; | 4 Messages
    ------------- | ------------
        :book: | Insertions: 1
        :book: | Added: []
        :book: | LOC: 2
        :book: | Mod: ["CHANGELOG.yml"]
    

  


<p align="right" meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/KrauseFx/danger/">danger</a>
</p>

**Comment by alloy** [comment]
I don’t really know what that Danger message is trying to convey. Should I be able to understand it?

**Comment by orta** [comment]
Nah, I've fixed it in #1050

**Comment by alloy** [comment]
Very nice change!

**Comment by alloy** [comment]
> Nah, I've fixed it in #1050

Ok, but still, what does it mean? (This is Danger UX feedback btw)

**Comment by orta** [comment]
It echoes some metadata about the PR, modified files insertions ( which is wrong ), additional files and overall line of code changes. The commit references are wrong on this build, https://github.com/KrauseFx/danger/pull/36

**Pull request merged**
