### PR TITLE
fix: Add optional field directive to notification previewImages field

### PR DESCRIPTION
**Pull request by olerichter00**
This PR resolves [ONYX-780] 

### Description

Follow up for https://github.com/artsy/eigen/pull/10081

This adds the `@optionalField` directive to the notification `previewImages` field. I guess, that this could fail for various reasons, and thought it might be good to make the preview image optional to prevent the entire Activity panel query from failing.

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-780]: https://artsyproduct.atlassian.net/browse/ONYX-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 48dcbc7d5570c907e070d967cbccd6f66ca3a182
</p>

**Review by MounirDhahri — COMMENTED** [review]
I think we don't need to do this anymore because by default everything is optional unless specified by the `@principalField`. @gkartalis please correct me if I am wrong

**Comment by gkartalis** [comment]
thanks for the ping, yes you are right now we only rely on `@principalField` anything else is optional

**Review by gkartalis — COMMENTED** [review]
@MounirDhahri @olerichter00 

thanks for the ping, yes you are right now we only rely on `@principalField` anything else is optional

**Comment by olerichter00** [comment]
I will close this pull request because all fields are now optional by default.

**Pull request closed without merging**
