### PR TITLE
refactor(masonry): Replace artwork autosuggest results with Masonry

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [] 

### Description

Refactors the autosuggest results on adding an artwork in my collection to use MasonryFlashList.

No changes are expected ui wise.

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- 

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Replace artwork autosuggest results with Masonry - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (Replace artwork autosuggest results with Masonry - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d47e22482d5aae370fed497852f33dde7f3aeb15
</p>

**Review by MounirDhahri — APPROVED** [review]
Nice! Could be nice to create a canary build to try this out on both android and iOS

**Comment by gkartalis** [comment]
Good idea @MounirDhahri, will fix the broken tests from main in another pr will rebase and trigger one codepush build for this ~ will update below when ready

**Comment by gkartalis** [comment]
codepush canary versions were just uploaded `codepush-canary-android-8.29.1-2024.01.02.16` and  `codepush-canary-ios-8.29.1-2024.01.02.16`

**Comment by MounirDhahri** [comment]
Thanks!

**Comment by gkartalis** [comment]
seems safe to merge ~ will also add a QA scenario for this surface

**Pull request merged**
