### PR TITLE
chore(onyx-467): clean up alerts related feature flags

### PR DESCRIPTION
**Pull request by nickskalkin**
This PR resolves [ONYX-467]

### Description

Clean up old feature flags that are marked as release in Echo:

- [AREnableAlertsFiltersArtistSeriesFiltering](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L169)
- [AREnableArtistSeriesSuggestion](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L168)
- [AREnableAlertDetailsInput](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L161)
- [AREnableAlertsSuggestedFilters](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L163C14-L163C44)
- [AREnableAlertsFilters](https://github.com/artsy/echo/blob/b50122ea17f0701f3f0d8393a0ea85f5ff9dc00a/Echo.json5#L162)

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [x] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- chore: clean up alerts related feature flags - @nickskalkin 

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-467]: https://artsyproduct.atlassian.net/browse/ONYX-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (chore: clean up alerts related feature flags - @nickskalkin)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a99db4431ca112114dd25b850871da787f0d6d14
</p>

**Review by MounirDhahri — APPROVED** [review]
This feels good! thanks

**Review by dariakoko — APPROVED** [review]
Thank you 👏

**Review by anandaroop — APPROVED** [review]
Awesome!

**Pull request merged**
