### PR TITLE
[Tests] Fix master

### PR DESCRIPTION
**Pull request by orta**
Updates some snapshots, adds some imports.

@ashfurrow 
this test is flakey

screen shot 2016-06-03 at 21 32 28

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
        
            1 Warning
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
    
    
  </tbody>
</table>
  

  



Time | Class | Function |
| --- | ----- | ----- |268.8ms | [AuctionViewController.swift](/artsy/eigen/tree/orta-master_fix/Artsy/View_Controllers/Auction/AuctionViewController.swift#L181) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
197.1ms | [SwiftyJSON.swift](/artsy/eigen/tree/orta-master_fix/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
171.3ms | [WebSocket.swift](/artsy/eigen/tree/orta-master_fix/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
82.5ms | [Observable.swift](/artsy/eigen/tree/orta-master_fix/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
72.8ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/orta-master_fix/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
68.9ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/orta-master_fix/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, sideMargin: String)




<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
I take it back, it's always not working for me and circle

**Comment by orta** [comment]
Seriously `LiveAuctionsAdminViewController.swift` is slow to compile? It's like 8-9 lines of [really simple code](https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22-L42)

**Comment by orta** [comment]
The test _does_ pass on my Mac Pro, so I'm assuming it works by being on a really fast machine 🔥

**Comment by orta** [comment]
I increased the time :-/ - would prefer a better way of checking this, but green is green 👍

**Comment by ashfurrow** [comment]
Ah, the curse of a fast dev machine 😬 I've got an idea to make the test deterministic, will submit a PR.

**Pull request merged**
