### PR TITLE
fix(CX-2968): Do Not Hide StatusBar on Median Sale Price Chart Screen

### PR DESCRIPTION
**Pull request by lordkiz**
### Description
- This PR hides the status bar on the Median Sale Price Chart screen instead of hiding it when career highlight is selected.

This PR resolves [CX-2968]

https://user-images.githubusercontent.com/18648835/194526218-4744be2d-e16c-4e20-839d-4c29472fcdc9.mov

#### Acceptance Criteria

-

#### Setup Instructions

-

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Do Not Hide StatusBar on Median Sale Price Chart Screen - kizito

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[CX-2968]: https://artsyproduct.atlassian.net/browse/CX-2968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by MounirDhahri** [comment]
@lordkiz would you mind adding a video showing the new behaviour?

**Comment by lordkiz** [comment]
> @lordkiz would you mind adding a video showing the new behaviour?

Sure 👍

**Comment by MounirDhahri** [comment]
i don't feel like this is good UX, I find the first screen jump very weird. can you run it with Dascha

**Comment by lordkiz** [comment]
> i don't feel like this is good UX, I find the first screen jump very weird. can you run it with Dascha

Yes @MounirDhahri . The backdrop from the bottomsheet cannot overlay over the statusbar and that is the reason for hiding the StatusBar on this screen and that would inevitably cause a jump initially. It seems better than having multiple jumps whenever the bottomsheet shows up and whenever it closes.
Maybe what we can do differently is:
- Keep the StatusBar
- Remove the backdrop from BottomSheet
- Add our own overlay on the screen when the BottomSheet shows up which should then draw behind the StatusBar
I will try it this way.

**Comment by MounirDhahri** [comment]
Thanks for the suggested approach, I missed your comment because I was in meetings. Let's go with Pierluca's suggested approach then try out what you suggested later if it doesn't work. I am also interested in seeing the StatusBarOverlay approach, it might be the best one

**Comment by lordkiz** [comment]
@MounirDhahri @MrSltun reverted to not hiding StatusBar since we can't draw the overlay behind.

**Comment by lordkiz** [comment]
Updated the video.

**Comment by MounirDhahri** [comment]
Nice, thanks for making the changes. Something seems to off for me though on iOS 

https://user-images.githubusercontent.com/11945712/194528321-d51a66d2-cdde-45c9-a291-9b827ef1217a.mov

**Comment by lordkiz** [comment]
> Nice, thanks for making the changes. Something seems to be off for me though on iOS

Your simulator is still referencing an updated status bar.
You should kill it and reopen.

**Comment by MounirDhahri** [comment]
I did that already few times, let me try it out again

**Comment by MounirDhahri** [comment]
Same result on a fresh build from xcode after cleaning all data as well as a new session on packager with cache resetted. The good thing, is that now I know for a fact that the issue reported in the other ticket where the career highlights show up, is very accurate since the method is being called on screen load. Fixing it here will fix it for the other screen as well


https://user-images.githubusercontent.com/11945712/194531969-1047eeec-2f9b-43f7-a5b3-31ce1c52226a.mov

**Comment by lordkiz** [comment]
> Same result on a fresh build from xcode after cleaning all data as well as a new session on packager with cache resetted. The good thing, is that now I know for a fact that the issue reported in the other ticket where the career highlights show up, is very accurate since the method is being called on screen load. Fixing it here will fix it for the other screen as well

Hmmmm. Not happening on my simulator. It seems that it just sets the status bar style to `light-content` on your simulator. Weird, since nothing in this PR should trigger that.

**Comment by MounirDhahri** [comment]
I can check it out further later. I can see it being triggered though the same way the career highlights are showing up on Artist change. It will be fun to investigate, I will check it out

**Comment by lordkiz** [comment]
@MounirDhahri Can't reproduce it. Can you try running this branch on a different simulator - a simulator you had not used to run a branch that had StatusBar related changes.

**Comment by MounirDhahri** [comment]
Might be something with my setup then. Let's merge this and I will test it on my iPhone then

**Pull request merged**
