### PR TITLE
Fixes problem with current lot CTA in LAI 📱

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes https://github.com/artsy/auctions/issues/294

The gist is: we had an object taking responsibility for managing the position of the CTA but when the current lot and/or lot the user is looking at change, the order isn't guaranteed and some weird race conditions were happening. I had to give up the observable abstraction within `LiveAuctionCurrentLotCTAPositionManager` and instead rely on functions called directly from the lot set view controller.

I also deleted two functions that were dead code.

### CODE REVIEW

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
fails are released though

**Comment by ashfurrow** [comment]
Aye, will get to those tomorrow 👍

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">You need to set the App’s plist version to 3.1.1</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by ashfurrow** [comment]
That danger error will be fixed in https://github.com/artsy/eigen/pull/2131 . This should be good to review whenever (it's been deployed already).

**Pull request merged**
