### PR TITLE
Removes unnecessary field

### PR DESCRIPTION
**Pull request by ashfurrow**
Force [already includes this check](https://github.com/artsy/force/blob/master/desktop/apps/auction/templates/registration_component.jade#L3) for calculating the `qualified_for_bidding` field. I still need to run through the app and remove uses of this field. /cc @sweir27

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_travis">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
👍

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">There were <a href="https://eigen-ci.s3.amazonaws.com/4031/index.html">snapshot errors</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_circle">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
err, do we have a screenshot with an actual webpage rendered in it?!

**Comment by ashfurrow** [comment]
No, that's the failing one. The reference image is 
is_positioned_correctly 2x

**Comment by ashfurrow** [comment]
It's failing similarly on master, pinging @mennenia to get some help on this.

**Comment by ashfurrow** [comment]
Okay, failure appears intermittent. ¯\\_(ツ)_/¯

**Comment by mennenia** [comment]
Yeah sorry @ashfurrow no clue there :(

**Pull request merged**
