### PR TITLE
@alloy => Force cache all framework based Fonts on app launch

### PR DESCRIPTION
**Pull request by orta**
Fixes https://github.com/artsy/eigen/issues/588

When we first made Eigen, we debated using JSON files to set up all UI, so that we could make layout changes realtime. See [ARTheme](https://github.com/artsy/eigen/blob/master/Artsy/Theming/ARTheme.m#L101-L134) - [Example JSON](https://github.com/artsy/eigen/blob/master/Artsy/Theming/Theme.json). This is the “QA fix” rather than a  full fix which pre-caches fonts before the firstVC is set up.

### CODE REVIEW

**Comment by orta** [comment]
https://github.com/artsy/eigen/issues/602 is the issue for a full fix

**Comment by alloy** [comment]
Can you add a beta changelog?

**Comment by orta** [comment]
fpush'd

**Comment by alloy** [comment]
Superb!

**Pull request merged**
