### PR TITLE
Requires AROption set for native live auctions

### LINKED ISSUE #1466: Put native live integration behind an AROptions flag
It should be accessible only to developers and internal testers until it is complete, so we don't ship something half-done to the app store.

### PR DESCRIPTION
**Pull request by ashfurrow**
A few notes:

- Since Prediction staging is currently on a _non_ `.artsy.net` domain, it gets treated as an external link. When it gets moved to a proper domain, I'll check that move does indeed work.
- Because of the way routes are loaded on startup, after changing the Adoption, you need to restart the app. Wasn't sure how best to document this, open to suggestions.

Fixes #1466.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Eek, test failure is legit. Will fix tomorrow.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
        
            1 Warning
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
    
    
  </tbody>
</table>
  

  



Time | Class | Function |
| --- | ----- | ----- |263.4ms | [AuctionViewController.swift](/artsy/eigen/tree/live-auctions-option/Artsy/View_Controllers/Auction/AuctionViewController.swift#L176) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
185.6ms | [WebSocket.swift](/artsy/eigen/tree/live-auctions-option/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
58.7ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/live-auctions-option/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView




<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by ashfurrow** [comment]
🍏

**Comment by orta** [comment]
👍

**Pull request merged**
