### PR TITLE
fix(ONYX-175): remove FooterComponent from the InfiniteScrollArtworksGridContainer

### PR DESCRIPTION
**Pull request by dariakoko**
This PR resolves [ONYX-175] 

### Description

When adding new artwork to MyColleciton, on the artwork grid we are showing a button "Go to Add Artwork Details". This button is not reachable and is removed on this PR 

| before | after |
| --- | --- |
| https://github.com/artsy/eigen/assets/36167539/8843880c-c1e3-498e-97cf-962e4fe9e2e4 | https://github.com/artsy/eigen/assets/36167539/d4a6c783-5c9f-4511-871d-0b6b1b3918b5 | 
### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- remove FooterComponent from the InfiniteScrollArtworksGridContainer -daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[ONYX-175]: https://artsyproduct.atlassian.net/browse/ONYX-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 792bdf7ff50f902a130af9814925519210dc99bc
</p>

**Comment by MounirDhahri** [comment]
I think it's fine to remove this since we now allow users to create personal artists

Tagging @olerichter00 though here since he worked on this in the past and might have a different idea

**Comment by dariakoko** [comment]
+ we have the "Skip" button in the header and "Add artwork details" link under the search, they have the same functionality as the button I'm removing in this PR

**Review by MounirDhahri — APPROVED** [review]
Great- please feel free to merge @dariakoko then

**Pull request merged**
