### PR TITLE
ci: android specific releases

### PR DESCRIPTION
**Pull request by brainbicycle**
This PR resolves [MOPLAT-427]

### Description

Follow-up to:
https://github.com/artsy/eigen/pull/7284
https://github.com/artsy/eigen/pull/7353

Allow releasing specific past versions on Android.

- On uploading a beta to the playstore we will also upload the signed aab to s3
- On promoting a beta to prod we will allow selection/download from s3 and then upload the selected build to the play store 

TODO:
- [x] Test upload is working properly
- [x] Test promotion is working properly (using alpha lane not prod 😬 )

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Allow releasing specific builds on Android - Brian 

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[MOPLAT-427]: https://artsyproduct.atlassian.net/browse/MOPLAT-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by patrinoua** [comment]
🤩🎉💥

**Comment by pvinis** [comment]
Brian delivering at the nick of time 👏👏👏👏

**Comment by brainbicycle** [comment]
alright think this is ready!

**Comment by patrinoua** [comment]
@pvinis can we merge?

**Review by pvinis — APPROVED** [review]
looks good. let's merge and try it I guess

**Comment by patrinoua** [comment]
Best gift ever 😋

**Pull request merged**
