### PR TITLE
@orta -> Size Favorites cells relative to screen width

### PR DESCRIPTION
**Pull request by 1aurabrown**
I'm making a beta that includes this.

I noticed on iphone6, the Favorite Item cells (used for artist and gene favorites, as well as in related artists in the Artist view) were too small given the screen size because they were hard coded. This is more responsive -- results in slightly different pixel values.

### CODE REVIEW

**Comment by 1aurabrown** [comment]
will push snapshots

**Comment by 1aurabrown** [comment]
I just ran tests on my last commit twice -- the first time this failed:
```
 ARAppSearchViewControllerSpec
  test_searching__with_no_results__as_ipad, expected a matching snapshot named displays zero state as ipad
```

the second :
```
SiteHeroUnitSpec
  test_currentlyActive__current, expected: a truthy value, got: 0, which is falsy
  /Users/distiller/eigen/Artsy Tests/SiteHeroUnitTests.m:16
 ```

Not sure why these are failing some of the time but not all of the time. Maybe a leak from somewhere else.

**Comment by 1aurabrown** [comment]
yay! @orta

**Comment by 1aurabrown** [comment]
:green_heart:

**Comment by orta** [comment]
Looks great :+1:

**Pull request merged**
