### PR TITLE
feat(EMI-1603): Update Save Artwork flow to match the web

### PR DESCRIPTION
**Pull request by MrSltun**
This PR resolves [EMI-1603] 

> [!note]
> **Part** of the work on this PR is hidden behind the feature flag `AREnablePartnerOffer`

### Description

This PR updates the save artwork flow to match the one we have on Force, as well as styling the toasts in the same way
It also adds a description to the toast for the partner offer

### Videos & Screenshots
| | Android | iOS |
|---|---|---|
| Demo for changes | <video src="https://github.com/artsy/eigen/assets/20655703/52876563-145b-4781-bdde-a73995e2d535" /> | <video src="https://github.com/artsy/eigen/assets/20655703/729a5950-ba81-4b7e-af96-06b8bd56f616" /> |
| New Description (behind AREnablePartnerOffer) | image | image |

### PR Checklist

- [X] I have tested my changes on **iOS** and **Android**.
- [X] I hid my changes behind a **[feature flag]**, or they don't need one.
- [X] I have included **screenshots** or **videos**, or I have not changed the UI.
- [X] I have added **tests**, or my changes don't require any.
- [X] I added an **[app state migration]**, or my changes do not require one.
- [X] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [X] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Update save artwork flow - mrsltun
- add description to save artwork toast (ff: AREnablePartnerOffer) - mrsltun

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[EMI-1603]: https://artsyproduct.atlassian.net/browse/EMI-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Update save artwork flow - mrsltun, add description to save artwork toast (ff: AREnablePartnerOffer) - mrsltun)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 09fbcec50927c977019eb6cbe3128ce9a4091a09
</p>

**Review by gkartalis — COMMENTED** [review]
thanks for fixing the test linting changes as well, will leave the feature for review though to onyx devs

**Review by nickskalkin — APPROVED** [review]
looks good to me!

**Review by MounirDhahri — APPROVED** [review]
LGTM, only one minor UI comment, it looks like the toast placement is too high from the bottom of the screen, I believe we fixed that not long ago in Onyx

**Comment by MrSltun** [comment]
>  It looks like the toast placement is too high from the bottom of the screen, I believe we fixed that not long ago in Onyx

@MounirDhahri It does seem a bit high, but maybe to calculate for the bottom tabs. The screen in the video is "New Works For You" from the home screen.

image

**Comment by MounirDhahri** [comment]
Finally found this, I pushed [a commit](https://github.com/artsy/eigen/pull/9006/commits/67da1fa551f5fe48d443d7055a394ed9f6250402) a while ago to support dynamic toast placement that we can potentially use here. I am working on a similar issue in NWFY screen and I will tag you on a PR to address it

**Pull request merged**
