### PR TITLE
feat: Stick Save/Complete button on My collection artwork form

### PR DESCRIPTION
**Pull request by rajsam003**
The type of this PR is: Feature

This PR resolves [CX-2417]

### Description

Before

https://user-images.githubusercontent.com/17421923/157456422-76177ff6-3f62-4655-a8fb-3c6559762698.mov

After

https://user-images.githubusercontent.com/17421923/157456452-f1fdf5f4-9564-47a1-bec1-895483e262dd.mov

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- Sticky button at the bottom of My collection add/edit artwork form page - sam

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[CX-2417]: https://artsyproduct.atlassian.net/browse/CX-2417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (Sticky button at the bottom of My collection add/edit artwork form page - sam)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6e3a52d1c279c9fd294b1d715f05d4dec5f75783
</p>

**Review by MrSltun — APPROVED** [review]
Looks good to me, Thank you Sam 👏 !!

- side note: also curious about Ole's comment

**Comment by rajsam003** [comment]
> Looking at the ticket I don't see that this should affect the Edit Artwork screen as well. Are you sure it is only affecting the Create Artwork screen?

@olerichter00 The changes are for both Add and Edit screens.

**Comment by olerichter00** [comment]
Thanks a lot for the clarification 🙇 

Looking at the Edit Details screen the bottom border of the "Delete Artwork" button is party hidden below the "Save Changes" container (iOS, iPhone 12 mini). We might want to give it some bottom margin.

simulator_screenshot_34F6855D-A26A-4BA6-8BBB-17F8CCFE7944

**Comment by rajsam003** [comment]
@olerichter00  Let me confirm this from Pierluca.

**Review by olerichter00 — CHANGES_REQUESTED** [review]
Great solution!

**Review by dariakoko — APPROVED** [review]
Looks good to me 👍  Thanks Sam

**Review by olerichter00 — APPROVED** [review]
🚀

**Pull request merged**
