### PR TITLE
fix: android app crash

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [APPL-1108] 

### Description

Unfortunately we located the source of this issue to be the reanimated bump from 3.3.0 - 3.6.3.

Thus we are reverting in both [palette-mobile](https://github.com/artsy/palette-mobile/pull/254) and eigen in this PR.

We will revisit after the release.

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-  android app crash when switching from sell to inbox tab multiple times - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[APPL-1108]: https://artsyproduct.atlassian.net/browse/APPL-1108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (android app crash when switching from sell to inbox tab multiple times - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b7d49da87633b9044af6c8adb776ba7b521a6290
</p>

**Review by MrSltun — APPROVED** [review]

**Review by brainbicycle — APPROVED** [review]
damn, these updates are never easy. Thank you!

**Review by araujobarret — APPROVED** [review]

**Review by olerichter00 — APPROVED** [review]
Thanks 🙏

**Comment by gkartalis** [comment]
I need to bring back the patch
working on it now

**Pull request merged**
