### PR TITLE
[WIP] Deploy via pushing to the beta branch

### PR DESCRIPTION
**Pull request by orta**
I was having trouble deploying locally, so it felt like about time to do it properly. 

TODO:

- [ ] get CHANGELOG working
- [ ] Look at how/if we use the `.beta` or `.dev` prefix

Note, I am sending this to  #983 not to master, so it's predicated on that being merged.

### CODE REVIEW

**Comment by orta** [comment]
we should get boris blacklisted :dancers:

**Comment by neonichu** [comment]
hah, just had the [same thought](https://github.com/artsy/eigen/pull/984#issuecomment-164683965)

**Comment by alloy** [comment]
@orta We should add ‘only org’ support to @mention-bot.

**Comment by orta** [comment]
Moving to a new PR

**Pull request closed without merging**
