### PR TITLE
bug[SWA-248] Remove brackets to remove the country code bug

### PR DESCRIPTION
**Pull request by patrinoua**
The type of this PR is: **bug**

[SWA-248] erase the area code of US phone numbers

**bug**

https://user-images.githubusercontent.com/36475005/155716606-16a3b6a8-b36e-44b9-b24e-5462986e52d9.mov

**resolution**

https://user-images.githubusercontent.com/36475005/155716631-08c215e2-0523-4c32-8a38-40dfee61bd7c.mov

This PR resolves []

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

ⓘ 'User-facing' changes will be published as release notes.

#### Cross-platform user-facing changes

- Rename modal title - patrinoua

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[SWA-248]: https://artsyproduct.atlassian.net/browse/SWA-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5202a146ae28cd68b4f2c53554f61aacd676038f
</p>

**Comment by admbtlr** [comment]
But don't we actually want to keep the brackets? I think that, from a product perspective, they're pretty important.

**Comment by kiryl-zubarau** [comment]
Agree with @admbtlr. I think the problem happens because before phone saving we remove only one non-number sign from the end of the number. 
https://github.com/artsy/eigen/blob/33baadf8788443ff2e4078ff8a5c48380b45898c/src/app/Components/PhoneInput/PhoneInput.tsx#L52

It removes only space sign from the number like **'+1 (123) '** will be saved as **'+1 (123)'**.

We can fix that by removing all non-numeric signs from the end of the number by replacing the row with

```
setPhoneNumber(formattedPhoneNumber.replace(/\D+$/, ""))
```

@patrinoua could you please try this variant?

**Comment by patrinoua** [comment]
replaced by https://github.com/artsy/eigen/pull/6335

**Pull request closed without merging**
