### PR TITLE
Removes apply functions

### PR DESCRIPTION
**Pull request by ashfurrow**
While I'm clever enough to write these functions, I am not clever enough to debug them. Especially as Swift changes under our feet. So I "fixed the glitch" and just did things manually.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_travis">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by acjay** [comment]
Ah, interesting. This is what they call [eta expansion](http://blog.jaceklaskowski.pl/2013/11/23/how-much-one-ought-to-know-eta-expansion.html) in Scala, and it conveniently just happens implicitly.

**Comment by orta** [comment]
Cool!

**Comment by orta** [comment]
OK, this isn't going to master, but my branch so it's fine on red

**Comment by ashfurrow** [comment]
_Eta tu, Scala?_

Interesting, I'll take a look! I think generally speaking that eschewing a garbage collector made sense for the iPhone in 2007, but makes less sense today. Maybe the arguments about having to manually break reference cycles apply in a GC setting too, but I can't help but feel like having to explicitly say "weakly reference this object" is kind of a leaky abstraction.

**Pull request merged**
