### PR TITLE
[Live] Use a spinner for the max bid instead of buttons

### PR DESCRIPTION
**Pull request by orta**
Converts the Max Bid UI to be a custom native spinner, instead of using our buttons.

screen shot 2016-06-21 at 11 09 46 am

WIP cause I want sign-off on the iPhone 4S screenshot, feels right to me, but I reduced the size of the "set up your max bid" label to make it feel right

screen shot 2016-06-20 at 5 58 16 pm

screen shot 2016-06-20 at 5 58 19 pm

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">There were <a href="https://eigen-ci.s3.amazonaws.com/3022/index.html">snapshot errors</a></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">PR is classed as Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |253.6ms | [AuctionViewController.swift](/artsy/eigen/tree/orta-max/Artsy/View_Controllers/Auction/AuctionViewController.swift#L183) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
239.7ms | [SwiftyJSON.swift](/artsy/eigen/tree/orta-max/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
180.9ms | [WebSocket.swift](/artsy/eigen/tree/orta-max/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
82.1ms | [Observable.swift](/artsy/eigen/tree/orta-max/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
78.1ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/orta-max/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
75.2ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/orta-max/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
70.8ms | [AuctionBannerView.swift](/artsy/eigen/tree/orta-max/Artsy/Views/Auction/AuctionBannerView.swift#L41) | private func setupViews()
67.5ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-max/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
65.2ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-max/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
65.0ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/orta-max/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L49) | @objc override func viewDidLoad()
60.5ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/orta-max/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
@katarinabatina we also discussed switching the max bid copy to "Artsy will bid up to this maximum amount on your behalf" [in slack](https://artsy.slack.com/archives/auctions-dev/p1466452154000921)

**Comment by orta** [comment]
This commit is worth highlighting, https://github.com/artsy/eigen/pull/1737/commits/99d6e3297b878aaba259c583667fd1f0f4953529

We've never tested on Live on iOS8 until today. 📛 
Need to think about how we can improve our flow around that.

**Comment by alloy** [comment]
Will you assign this to someone?

**Comment by ashfurrow** [comment]
Weird, failures in snapshot tests but Danger isn't reporting them. In fact, I don't see second curtain reporting any either.

**Comment by ashfurrow** [comment]
LGTM once 🍏

**Comment by orta** [comment]
Failures were legit regardless  👍

**Comment by ashfurrow** [comment]
Interesting!

**Comment by orta** [comment]
I was running a subset of all tests ;)

**Pull request merged**
