### PR TITLE
Fixes winning bid events disappearing from bid history.

### PR DESCRIPTION
**Pull request by ashfurrow**
This is a very small change, but it has a large impact. It highlights the importance of bringing over @orta's tests from #1700, which would have caught this. 

Basically, we were removing the winning bid event from our full event list, which I had forgotten is not computed fresh, but maintains state over the course of the app. Every time there's a new event, we'd remove the winning event from the list and put it at the top. But the next time there was a new event, the winning event we removed would still be removed from the full event list, so it'd essentially disappear until the entire live interface was refreshed. The solution was to create a local copy of the full event list that we can mutate without longterm consequence.

### CODE REVIEW

**Comment by orta** [comment]
Ah, interesting, yeah I see the problem 👍 makes sense

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">There were <a href="https://eigen-ci.s3.amazonaws.com/2947/index.html">snapshot errors</a></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |242.4ms | [AuctionViewController.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Artsy/View_Controllers/Auction/AuctionViewController.swift#L183) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
196.0ms | [SwiftyJSON.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
180.6ms | [WebSocket.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
76.8ms | [Observable.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
73.1ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, sideMargin: String)
73.1ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
64.3ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
63.3ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L49) | @objc override func viewDidLoad()
62.3ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
59.7ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/ashfurrow-event-fixes/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by orta** [comment]
Snapshot changes are because the maxbidVC is looking only at the number of derived events, to fix correctly it needs to add +1 if there's a topbid

**Comment by ashfurrow** [comment]
Good catch! Will fix.

**Comment by ashfurrow** [comment]
Ah, wait. I changed these same snapshots yesterday when I couldn't figure out why the # of bids change, should have double-checked it wasn't a bug 😬 So the 3 is incorrect and the 4 is actually correct, I'll swap them back.

**Comment by orta** [comment]
👍

**Pull request merged**
