### PR TITLE
@alloy => show an unpublished banner

### PR DESCRIPTION
**Pull request by orta**
Want to guess who spent 30 minutes trying to figure out why things weren't working with an artwork's sales details because it wasn't published?

selfie-0

So I've fixed this, it should be green, but I'd like to add some tests:

screen shot 2015-02-05 at 6 14 45 pm

### CODE REVIEW

**Comment by alloy** [comment]
Hah, I’m gonna guess it’s that handsome fellow in the animated jif.

I’m unclear as to what the issue was, is it that you did not get to see the warning about the artwork being unpublished?

Tests are failing, though.

**Comment by orta** [comment]
Yeah, before this PR there is no visual indication that an artwork you're looking at is unpublished ( and thus admin only )

**Comment by orta** [comment]
un WIP'd

**Comment by orta** [comment]
this is greeeeen locallylyyyyyy

Giphy

**Comment by alloy** [comment]
I ran them locally and had both device permutations of 1 test fail. The difference seems to be the grey tint used in the tab bar. Any thoughts on why that fails?

artsy-unpublished-failing

**Comment by orta** [comment]
you need to do a `pod install` to ensure you have the right `Artsy+UIButtons` commit

**Comment by alloy** [comment]
Oh I see. Will try again.

**Comment by alloy** [comment]
Yup, very green locally! :+1:

**Pull request merged**
