### PR TITLE
fix(text): consistent font rendering on ios and android

### PR DESCRIPTION
**Pull request by pvinis**
The type of this PR is: **Bugfix**

This PR resolves [CX-1913]

### Description

ios and android handle custom fonts slightly differently, and after reading and investigating, here are the fixes for the two main things: 
- created a repo https://github.com/artsy/mobile-fonts to manage font files. I changed the ios fonts slightly so that custom fonts render the same as system fonts. for android the custom fonts render consistently with the system font.
- added `textAlignVertical` to our `Text`. that helps with the consistency between ios and android. it needs to be adjusted per font, but for us now with unica, the only font, we are good as it is. i added a story for the system font too, and you can see there that it needs a different value for that prop, in order for everything to be consistent, between platforms and between system and custom fonts.

Screenshots of results. left ios, right android.

Screenshot 2021-10-12 at 18 27 35

Screenshot 2021-10-12 at 16 31 46

Screenshot 2021-10-12 at 18 24 07
Screenshot 2021-10-12 at 17 30 56
Screenshot 2021-10-12 at 18 18 49

For reference: https://www.figma.com/file/m6gDpKHEWDbYJyrwsVZDBr/Artsy-3.0-Design-System?node-id=1007%3A289

Followup:
- [ ] lines with `##` can be removed, like https://github.com/artsy/mobile-fonts/blob/main/scripts/upload-to-s3.sh#L8.

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀
- [x] I would like at least one of the reviewers to run this PR on the simulator or device.
You can just run the storybook, but looking around the app would be great too.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

- consistent vertical text rendering - pavlos

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[CX-1913]: https://artsyproduct.atlassian.net/browse/CX-1913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Cross-platform user-facing changes (consistent vertical text rendering - pavlos)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 10dbb7116d1dc3e21cf894701a34ee4cae1ff1cd
</p>

**Comment by dimatretyak** [comment]
Tested it on my device. Is this PR supposed to fix the problem of vertical text alignment on android (there are problems with vertical alignment for the "create alert" button)?

<details><summary>Screenshots</summary>
photo_2021-10-12 15 08 26
photo_2021-10-12 15 08 28
photo_2021-10-12 15 08 29
</details>

**Comment by pvinis** [comment]
after talking to jonathan, i will make some adjustments to this first.

**Comment by pvinis** [comment]
ok all checked with jonathan, we are good to go!

**Pull request merged**
