### PR TITLE
chore: Update your Play Core Maven dependency to an Android 14 compatible version

### PR DESCRIPTION
**Pull request by dariakoko**
This PR resolves [] 

### Description

There was an email from Google play colsole to update Play Core Maven dependency to an Android 14 compatible version.

We don't have a direct dependency with com.google.android.play:core, but we have a transitive one through react-native-in-app-review lib 

To update the transitive dependency I update the react-native-in-app-review to the latest version of com.google.android.play:core

react-native-in-app-review dependencies before
```
+--- project :react-native-in-app-review
|    +--- com.facebook.react:react-native:+ -> com.facebook.react:react-android:0.72.12 (*)
|    +--- com.google.android.play:core:1.9.0
|    \--- com.google.android.gms:play-services-base:17.5.0 -> 18.0.1 (*)
```
react-native-in-app-review dependencies after:
```
+--- project :react-native-in-app-review
|    +--- com.facebook.react:react-native:+ -> com.facebook.react:react-android:0.72.12 (*)
|    +--- com.google.android.play:review:2.0.1
|    |    +--- com.google.android.gms:play-services-basement:18.1.0 (*)
|    |    +--- com.google.android.gms:play-services-tasks:18.0.2 (*)
|    |    \--- com.google.android.play:core-common:2.0.2
|    \--- com.google.android.gms:play-services-base:17.5.0 -> 18.0.1 (*)
```

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- update react-native-in-app-review to use the latest version of com.google.android.play:core

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by gkartalis — COMMENTED** [review]
looks good, could you also run `yarn install:all` or install the pods and commit the diff to refresh also the ios native dep that this library is linked with?

**Comment by ArtsyOpenSource** [comment]
### This PR contains the following changes:

- Dev changes (update react-native-in-app-review to use the laters version of com.google.android.play:core)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4b58f8cb65c0f9b93ca3398f09197527616fd436
</p>

**Review by brainbicycle — APPROVED** [review]
thanks @dariakoko !

**Comment by gkartalis** [comment]
Merginggggg 🌪️ thanks @dariakoko ✨

**Pull request merged**
