### PR TITLE
[RN] Add an option for staging the React via AppHub

### PR DESCRIPTION
**Pull request by orta**
This adds an admin panel that defaults to off

screen shot 2016-09-09 at 5 03 59 pm

Toggling it adds:

screen shot 2016-09-09 at 5 04 58 pm

Which offers a way to see:

* When the current build of RN was deployed, as it's continuously deployed, this is pretty often
* What version of Emission is running
* An option to open a React component
* The ability to run any specific build
* A way to turn it off
 
---

This links to `:head`, which can mean that the Eigen Obj-C Emission can be out of date with what Emission expects to be exposed to the JS. E.g. the module providers here:

head
screen shot 2016-09-09 at 5 09 49 pm

eigen
screen shot 2016-09-09 at 5 10 08 pm

Do I have any long term answers, not really, I mean we did do a minor patch for this, so it _does_ make sense. I've noted in [slack](https://artsy.slack.com/archives/gmv-ios-dev/p1473454637000261) that maybe an answer is to have deploys of Emission that are only the obj-c and to keep the same JS shipped with it, and have that run on eigen. 

It's hard to say whether we'd expect a lot of change over the bridging there. 

---

Opening any container

screen shot 2016-09-09 at 5 14 16 pm

I've got Eigen grabbing the list of exposed containers in the app registry, and puts those as clickable buttons. Then you can input any initial JSON state you want,

screen shot 2016-09-09 at 5 15 17 pm

which will push you through into that view controller

screen shot 2016-09-09 at 5 15 25 pm

this should make it much easier for beta testers to try out views before they're shipped into our `ARSwitchboard`.

---

TODO:

- [x] Verifying it works
- [x] The `AppHub` dependency needs to check for what subspecs it needs, currently it drags in the rest of React Native, which isn't optimal. PR sent  https://github.com/AppHubPlatform/apphub/pull/32
- [x] undoing the damage for space commander on `ARAppDelegate+Emission.m`
- [x] Ship a version of Emission that updates the Obj-C bridging side

Other than that, this is all you need to run the master commit for artsy/Emission  inside eigen

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG changes made</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">PR is classed as Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Needs testing on a Phone if change is non-trivial</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Detected some Swift building time outliers</td>
    </tr>
  </tbody>
</table>

Time | Class | Function |
| --- | ----- | ----- |267.3ms | [AuctionViewController.swift](/artsy/eigen/tree/orta-apphub/Artsy/View_Controllers/Auction/AuctionViewController.swift#L199) | @objc dynamic func showRefineTappedAnimated(animated: Bool)
210.2ms | [SwiftyJSON.swift](/artsy/eigen/tree/orta-apphub/Pods/SwiftyJSON/Source/SwiftyJSON.swift#L445) | get {}
198.2ms | [WebSocket.swift](/artsy/eigen/tree/orta-apphub/Pods/Starscream/Source/WebSocket.swift#L528) | private func processRawMessage(buffer: UnsafePointer<UInt8>, bufferLen: Int)
95.8ms | [Observable.swift](/artsy/eigen/tree/orta-apphub/Pods/Interstellar/Sources/Observable.swift#L71) | private final func nextTokenHash() -> Int
73.5ms | [AuctionLotMetadataStackScrollView.swift](/artsy/eigen/tree/orta-apphub/Artsy/View_Controllers/Live_Auctions/Views/AuctionLotMetadataStackScrollView.swift#L18) | required init(viewModel: LiveAuctionLotViewModelType, salesPerson: LiveAuctionsSalesPersonType, sideMargin: String)
72.8ms | [LiveAuctionsAdminViewController.swift](/artsy/eigen/tree/orta-apphub/Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift#L22) | @objc override func viewDidLoad()
69.8ms | [LiveAuctionLotViewController.swift](/artsy/eigen/tree/orta-apphub/Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift#L49) | @objc override func viewDidLoad()
67.9ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-apphub/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L25) | func ar_presentBlurredOverlayWithTitle(title: String, subtitle: String, buttonState: BlurredStatusOverlayViewCloseButtonState = default)
65.5ms | [UIViewController+BlurredStatusView.swift](/artsy/eigen/tree/orta-apphub/Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift#L31) | (closure)
60.1ms | [RefinementOptionsViewController+Private.swift](/artsy/eigen/tree/orta-apphub/Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift#L63) | func stackView() -> ORStackView


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by alloy** [comment]
Impressive :clap:

Let me know when this good to go!

**Comment by orta** [comment]
OK, this is good to go

**Comment by alloy** [comment]
Sahweet!

**Pull request merged**
