### PR TITLE
Fixes label overflow on auction title view

### LINKED ISSUE #1263: Misplaced Info Button
On Auctions native views. Reported at https://rink.hockeyapp.net/manage/apps/37020/feedback/454937

Example:

image_0-4

### PR DESCRIPTION
**Pull request by ashfurrow**
The fix is to set a low compression resistance priority, and to constrain the label to the top/bottom of its superview (so it can stretch).

This actually fixed a problem with ascenders/descenders getting cut off that we had never noticed (see all the 🎉 emojis that changed?). I did have to manually constrain the width of a related test, as its intrinsic content size wasn't sufficient to show the content (now that the label doesn't resist compression).

Fixes #1263.

### CODE REVIEW

**Comment by sarahscott** [comment]
I restarted circle because the fail looked suspicious - this looks great to me otherwise! Looks like there's a merge conflict though

**Comment by orta** [comment]
ah, I see, it's the cropping on the emoji :+1:

**Comment by ashfurrow** [comment]
Yeah, changelog update from master caused a conflict. 

I think the danger failure was because I pushed, then made a change and force-pushed before making the PR. I've seen Travis have a hard time handling that too.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">1 Warning</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td><h4>Found unstubbbed networking requests</h4>

<ul>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
<li><a href="https://github.com/search?q=ARFairFavoritesNetworkModel+repo%3Aartsy%2Feigen&amp;ref=searchresults&amp;type=Code&amp;utf8=%E2%9C%93">ARFairFavoritesNetworkModelSpec</a> in <code>test_ignores_artworks_without_a_partner</code></li>
</ul>
</td>
    </tr>
    
  </tbody>
</table>
  

  


<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by alloy** [comment]
food for future thought:

In a case like [this](https://github.com/artsy/eigen/blob/ashfurrow-label-overflow/Artsy_Tests/ReferenceImages/AuctionViewControllerTests/wraps_auction_name_correctly%402x.png) it would be nice if the label had a background color so that we can see that it does indeed go all the way up to the button.

**Comment by alloy** [comment]
Actually, a background color is more of a patch fix, the better fix would be for the title in the test to be formatted exactly so that it clearly demonstrates the correct wrapping.

**Pull request merged**
