### PR TITLE
[Project] Remove staging domain from associated domains in Store build.

### LINKED ISSUE #905: Extraneous calls to apple-app-site-association
Made to staging as well as `/api/v1/profile/apple-app-site-association`.

### PR DESCRIPTION
**Pull request by alloy**
Fixes #905.

### CODE REVIEW

**Comment by sarahscott** [comment]
:+1:

**Comment by orta** [comment]
Do the old ones still exist? this just shows new files

**Comment by alloy** [comment]
Yeah, the shame… removed it here https://github.com/artsy/eigen/commit/743cbe110812074dad53ab711b8d700910b36d86

**Comment by orta** [comment]
hah, cool cool

**Pull request merged**
