### PR TITLE
fix: add JQ to Brewfile

### PR DESCRIPTION
**Pull request by MounirDhahri**
### Description
- after the latest app shell changes, I noticed that the `init-metaflags` script is breaking because of the missing `jq` dependency in my macbook - this PR adds it to Brewfile ot make sure everyone gets it once they run the initial install script.

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- fix: add jq to Brewfile - mounir

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

### CODE REVIEW

**Review by pvinis — APPROVED** [review]

**Comment by pvinis** [comment]
@MounirDhahri can you run `yarn install:all` so the lockfile updates too?

**Comment by pvinis** [comment]
actually wait, let me fix something here

**Comment by MounirDhahri** [comment]
done

**Comment by MounirDhahri** [comment]
@pvinis sure I noticed as well we were not running brew bundle - that's why it was updating, I added it to the install script

**Comment by pvinis** [comment]
wow second time we do the exact same thing lol. i added the comment too, and ill merge

**Comment by MounirDhahri** [comment]
@pvinis awesome 😄 thanks a lot

**Pull request merged**
