### PR TITLE
@wrgoldstein => [Notifications] Limit count to unread notifications.

### PR DESCRIPTION
**Pull request by alloy**
Our side of the fix for #673.

### CODE REVIEW

**Comment by alloy** [comment]
Specifically https://github.com/artsy/eigen/pull/698/files#diff-fdbf8411f7728fb905bc8e6e2ba13d43R728

**Comment by wrgoldstein** [comment]
endpoint use looks right, spec failures look unrelated?

**Comment by alloy** [comment]
Yup, those 6 are known. Sorry, should've said that :)

**Comment by wrgoldstein** [comment]
"Only those with write access to this repository can merge pull requests" it says, better pull the trigger yourself :)

**Comment by alloy** [comment]
Boh! Will do, thanks for the sanity check :+1:

**Pull request merged**
